import type {LeaderPost} from './types';
export const editionDate='2026-09-26';
const base={status:'published' as const,featured:true,highlight:false,published_at:'2026-09-26T09:00:00Z',created_at:'2026-09-26T09:00:00Z',expires_at:null,media_path:null,media_type:null,seed:true};
export const editionPosts:LeaderPost[]=[
 {...base,id:'edition-20260926-darpa',kind:'note',topic:'innovation',
 title:'قبل أن تموّل الفكرة: ما التجربة التي تستحق المال؟',title_en:'Before funding the idea, define the test.',
 body:'المرجع: تستخدم DARPA أسئلة هايلماير لفحص أهداف البرامج وحدود الأساليب الحالية والجِدّة والمخاطر والتكلفة والمدة واختبارات النجاح.\n\nما يهم مؤسستك: يمكنك تحويل المقترح الكبير إلى تجربة تكشف إن كان المسار يستحق الاستثمار.\n\nخطوة عملية: اختر مقترحًا واحدًا، واكتب النتيجة المطلوبة وخط الأساس واختبارًا أوليًا ومعيار التوقف. هذه توصية تحريرية مستلهمة من المنهج، وليست برنامجًا مشتركًا مع DARPA.',
 body_en:'The reference: DARPA uses the Heilmeier questions to examine program goals, current limitations, novelty, risks, cost, time and tests of success.\n\nWhy it matters: a large proposal can start with a test that reveals whether further investment is warranted.\n\nTry this: select one proposal and write its outcome, baseline, first test and stop condition. This is an editorial application of the method, not a joint DARPA program.',
 source_url:'https://www.darpa.mil/about/heilmeier-catechism',source_label:'DARPA · Heilmeier Catechism'},
 {...base,id:'edition-20260926-ontology',kind:'image',topic:'ai',media_type:'image/jpeg',media_url:'/field-industry.jpg',
 title:'بين رؤية البيانات وتغيير ما يحدث في المصنع.',title_en:'From seeing the data to changing what happens in the factory.',
 body:'المرجع: تربط Ontology لدى Palantir الأصول الرقمية بكيانات العالم الحقيقي، وتضم علاقات وإجراءات ومنطق عمل وصلاحيات.\n\nما يهم مؤسستك: في مثال صيانة مصنع، القيمة تبدأ حين ترتبط الآلة بالعطل وقطعة الغيار ومسؤول الإجراء، وتصل المعلومة إلى عمل يمكن تتبعه.\n\nخطوة عملية: ارسم رحلة عطل واحد من اكتشافه إلى إغلاقه. أين تضيع المعلومة؟ وأين يتعطل الإجراء؟ مثال المصنع توضيح من VisionSeek، وليس نتيجة عميل أو ادعاء امتلاك منصة Palantir.',
 body_en:'The reference: Palantir’s Ontology connects digital assets to real-world entities and includes relationships, actions, business logic and permissions.\n\nWhy it matters: in an illustrative maintenance workflow, value comes from connecting equipment, faults, spare parts and responsible people to traceable action.\n\nTry this: map one fault from detection to closure. Where is information lost? Where does action stall? This factory example is VisionSeek’s illustration, not a customer result or a claim to operate Palantir.',
 source_url:'https://www.palantir.com/docs/foundry/ontology/overview/',source_label:'Palantir · Ontology overview'},
 {...base,id:'edition-20260926-transfer',kind:'image',topic:'capabilities',media_type:'image/jpeg',media_url:'/field-space.jpg',
 title:'قد تبدأ فرصتك بتقنية طوّرها فريق آخر لسنوات.',title_en:'Your opportunity may start with technology another team spent years developing.',
 body:'المرجع: يتيح برنامج نقل التكنولوجيا في NASA التقدم لترخيص تقنيات، ومنها تراخيص تجارية لمؤسسات أمريكية ودولية بشروط تفاوضية. الإتاحة لا تعني الحصول على الحقوق أو جاهزية التقنية لسوقك.\n\nما يهم مؤسستك: ابحث عن تقنية تلائم احتياجًا واضحًا، ثم افحص نضجها وحقوق استخدامها وتكلفة تكييفها.\n\nخطوة عملية: حدد احتياجًا واحدًا وقارن بناء الحل من البداية بترخيص تقنية مناسبة. لا توجد هنا شراكة أو حقوق حصلت عليها VisionSeek.',
 body_en:'The reference: NASA’s Technology Transfer program accepts technology-license applications, including commercial licenses for domestic and international organizations with negotiated terms. Availability does not establish rights or readiness for your market.\n\nWhy it matters: start with a specific need, then examine technology maturity, rights and adaptation cost.\n\nTry this: compare building from scratch with licensing a suitable technology for one defined need. VisionSeek is not claiming a NASA partnership or acquired rights.',
 source_url:'https://technology.nasa.gov/license',source_label:'NASA · Technology licensing'},
];
export const editionVideos:LeaderPost[]=[
 {...editionPosts[0],id:'edition-20260926-proof-video',kind:'video',cover_url:'/field-science.jpg',media_type:'video/mp4',media_url:'/leaders/proof-ar.mp4',media_url_en:'/leaders/proof-en.mp4',title:'من فكرة كبيرة إلى اختبار واضح — في 30 ثانية.',title_en:'From a big idea to a clear test — in 30 seconds.',poster_url:'/leaders/proof-ar.jpg',poster_url_en:'/leaders/proof-en.jpg',caption_url:'/leaders/proof-ar.vtt',caption_url_en:'/leaders/proof-en.vtt'},
 {...editionPosts[1],id:'edition-20260926-action-video',kind:'video',cover_url:'/field-industry.jpg',media_type:'video/mp4',media_url:'/leaders/action-ar.mp4',media_url_en:'/leaders/action-en.mp4',title:'هل تنتهي بياناتك عند لوحة العرض؟',title_en:'Does your data journey end at the dashboard?',poster_url:'/leaders/action-ar.jpg',poster_url_en:'/leaders/action-en.jpg',caption_url:'/leaders/action-ar.vtt',caption_url_en:'/leaders/action-en.vtt'},
];
export const editionStories:LeaderPost[]=editionPosts.map(p=>({...p,id:`story-${p.id}`,kind:'story',highlight:true,media_url:undefined,media_type:null,body:p.topic==='innovation'?'ابدأ بالنتيجة المطلوبة. حدّد اختبارًا ومعيار نجاح وقرارًا تتخذه بعده. اقرأ الإحاطة ومصدرها في مختارات هذه النسخة.':p.topic==='ai'?'تتبّع قرارًا واحدًا من البيانات إلى الإجراء. أين يتوقف؟ اقرأ الإحاطة ومصدرها في مختارات هذه النسخة.':'قد تكون التقنية موجودة، وتحتاج إلى مسار ترخيص وتكييف. اقرأ الإحاطة ومصدرها في مختارات هذه النسخة.',body_en:p.topic==='innovation'?'Start with the outcome. Define a test, a success measure and the decision that follows. Find the brief and source in this edition.':p.topic==='ai'?'Follow one decision from data to action. Where does it stop? Find the brief and source in this edition.':'The technology may exist already. Licensing and adaptation still need work. Find the brief and source in this edition.'}));
export const editionAll=[...editionPosts,...editionVideos,...editionStories];
