import type {LeaderPost} from './types';

// Original preview copy, independently researched. Publication requires founder review.
export const editionDate = '2026-10-04';
const base = {status:'published' as const, featured:false, highlight:false, character_id:'medo',sector_ids:['medo'],published_at:'2026-10-04T15:00:00Z',created_at:'2026-10-04T15:00:00Z',expires_at:null,media_path:null,media_type:'image/jpeg',seed:true};
export const editionPosts:LeaderPost[] = [
 {...base,id:'kapsula-transfer',kind:'image',topic:'capabilities',featured:true,media_url:'/leaders/kapsula-transfer-ar.jpg',media_url_en:'/leaders/kapsula-transfer-en.jpg',
 title:'القدرة الدوائية لا تنتقل داخل صندوق.',title_en:'A pharmaceutical capability does not arrive in a box.',
 body:'المصدر: تصف Samsung Biologics نقل التقنية باعتباره عملًا يجمع خبراء العمليات والجودة، وتبادل المعرفة، والتحقق من ملاءمة المنشأة. هذا وصف الشركة لممارساتها.\n\nما يهم مؤسستك: قد تكون التقنية موجودة، لكن امتلاك القدرة يتطلب معرفة تشغّلها وفريقًا يستوعبها. هذه قراءة كبسولة للمثال.\n\nما الذي يستحق الدراسة: ما المعرفة التي ستبقى داخل مؤسستك بعد انتهاء مشروع النقل؟',
 body_en:'Source: Samsung Biologics describes technology transfer as involving process and quality specialists, knowledge exchange and facility-fit verification. This is the company’s account of its practice.\n\nWhy it matters: access to technology also needs operating knowledge and a team able to absorb it. This is Kapsula’s interpretation.\n\nWorth exploring: what knowledge will remain inside your institution after the transfer project ends?',
 source_url:'https://samsungbiologics.com/media/bio-story/agile-and-reliable-technology-transfer-for-complex-modalities',source_label:'Samsung Biologics · Technology transfer'},
 {...base,id:'kapsula-korea-training',kind:'image',topic:'leadership',featured:true,media_url:'/leaders/kapsula-training-ar.jpg',media_url_en:'/leaders/kapsula-training-en.jpg',
 title:'قد يبدأ التوطين بفريق يتعلّم في كوريا.',title_en:'Local capability can start with a team learning in Korea.',
 body:'المصدر: يقدّم المركز العالمي للتدريب على التصنيع الحيوي في كوريا برامج لبناء مهارات العاملين، تشمل تدريبًا عمليًا داخل منشآت التصنيع، وفق منظمة الصحة العالمية.\n\nما يهم مؤسستك: نقل المعرفة إلى الفريق قد يكون جزءًا أساسيًا من نقل القدرة نفسها.\n\nما الذي يستحق الدراسة: أي مهارة يحتاج فريقك إلى امتلاكها؟ هذه قراءة في نموذج التدريب؛ لا تعني أن التقديم متاح الآن أو أن VisionSeek تنظم البرنامج.',
 body_en:'Source: WHO describes Korea’s Global Training Hub for Biomanufacturing as providing workforce programmes, including hands-on training in manufacturing facilities.\n\nWhy it matters: transferring knowledge to a team can be central to transferring the capability itself.\n\nWorth exploring: which skill does your team need? This examines the training model; it does not announce open applications or a VisionSeek-run programme.',
 source_url:'https://www.who.int/initiatives/biomanufacturing-workforce-training-initiative',source_label:'WHO · Biomanufacturing workforce'},
 {...base,id:'kapsula-ai-discovery',kind:'image',topic:'ai',featured:true,media_url:'/leaders/kapsula-ai-ar.jpg',media_url_en:'/leaders/kapsula-ai-en.jpg',
 title:'ما الذي يحدث حين يعمل الذكاء الاصطناعي إلى جوار المختبر؟',title_en:'What changes when AI works alongside the laboratory?',
 body:'المصدر: أعلنت Lilly وNVIDIA في يناير 2026 تعاونًا بحثيًا يجمع خبرات تطوير الدواء والذكاء الاصطناعي. الإعلان يصف طموحًا وخطة عمل، وليس دواءً ثبت نجاحه.\n\nما يهم مؤسستك: القيمة المحتملة في اتصال النماذج بالخبرة والبيانات والتجارب، لا في النموذج وحده. هذه قراءة كبسولة.\n\nما الذي يستحق الدراسة: أين يمكن لقدرة حسابية أن تساعد فريق البحث على اختيار ما يختبره؟',
 body_en:'Source: Lilly and NVIDIA announced a research collaboration in January 2026 combining drug-development expertise and AI. The announcement describes ambitions and plans, not a proven medicine.\n\nWhy it matters: potential value lies in connecting models with expertise, data and experiments. This is Kapsula’s interpretation.\n\nWorth exploring: where could computational capability help a research team choose what to test?',
 source_url:'https://nvidianews.nvidia.com/news/nvidia-and-lilly-announce-co-innovation-lab-to-reinvent-drug-discovery-in-the-age-of-ai',source_label:'NVIDIA / Lilly · Research announcement'},
 {...base,id:'kapsula-manufacturing',kind:'image',topic:'strategy',media_url:'/leaders/kapsula-manufacturing-ar.jpg',media_url_en:'/leaders/kapsula-manufacturing-en.jpg',
 title:'مستقبل مصنع الدواء يُعاد تصميمه الآن.',title_en:'The pharmaceutical factory is being rethought.',
 body:'المصدر: تضع مبادرة FRAME لدى FDA التصنيع المستمر والموزّع والذكاء الاصطناعي ضمن أولوياتها لدراسة التصنيع الدوائي المتقدم.\n\nما يهم مؤسستك: توجد بدائل تستحق الفهم قبل قرار التوسع في خطوط الإنتاج. إدراج التقنية ضمن المبادرة لا يعني اعتماد كل تطبيق لها.\n\nما الذي يستحق الدراسة: أي قيود في مصنعك قد تستحق دراسة تقنية مختلفة؟ هذه قراءة لاتجاه تقني، وليست توصية تنظيمية أو وعدًا بتوفير محدد.',
 body_en:'Source: FDA’s FRAME initiative prioritizes continuous and distributed manufacturing and AI in its work on advanced pharmaceutical manufacturing.\n\nWhy it matters: alternatives deserve attention before expanding production. Inclusion in the initiative does not approve every application.\n\nWorth exploring: which factory constraint might justify examining another technology? This is a technology perspective, not regulatory advice or a savings claim.',
 source_url:'https://www.fda.gov/about-fda/center-drug-evaluation-and-research-cder/cders-framework-regulatory-advanced-manufacturing-evaluation-frame-initiative',source_label:'FDA · FRAME initiative'},
 {...base,id:'kapsula-mrna',kind:'note',topic:'innovation',media_type:null,
 title:'وصول التقنية بداية. استمرار الإنتاج هو الاختبار.',title_en:'Access to technology is a beginning. Sustained production is the test.',
 body:'المصدر: في تحديث يونيو 2025 لبرنامج نقل تقنية mRNA، عرضت WHO الانتقال نحو تصنيع مستدام، مع اهتمام بالجدوى والأسواق وقدرات الجهات المستقبلة.\n\nما يهم مؤسستك: القدرة تحتاج ظروفًا تسمح باستمرار تشغيلها، بجانب المعرفة العلمية. هذه قراءة كبسولة، وليست إعلانًا عن مشروع لنا.\n\nما الذي يستحق الدراسة: ما الذي يجعل القدرة المنقولة قابلة للاستمرار داخل مؤسستك؟ التوجه المعلن للبرنامج لا يثبت نجاح كل منتج أو موقع.',
 body_en:'Source: WHO’s June 2025 mRNA technology-transfer update described a move toward sustainable manufacturing, considering viability, markets and recipient capabilities.\n\nWhy it matters: a capability needs conditions for continued operation alongside scientific knowledge. This is Kapsula’s reading, not an announcement of our own project.\n\nWorth exploring: what would make a transferred capability sustainable in your institution? Programme ambitions do not establish success for every product or site.',
 source_url:'https://www.who.int/news/item/13-06-2025-mrna-technology-transfer-programme-s-phase-2.0-discussed-with-partners-on-the-sidelines-of-g20-summit',source_label:'WHO · mRNA programme update · 2025'},
];
export const editionVideos:LeaderPost[] = [editionPosts[0],editionPosts[2]].map((p,i)=>({...p,id:`${p.id}-video`,kind:'video',featured:false,media_type:'video/mp4',media_url:`/leaders/kapsula-${i===0?'transfer':'ai'}-ar.mp4`,media_url_en:`/leaders/kapsula-${i===0?'transfer':'ai'}-en.mp4`,poster_url:`/leaders/kapsula-${i===0?'transfer':'ai'}-ar-poster.jpg`,poster_url_en:`/leaders/kapsula-${i===0?'transfer':'ai'}-en-poster.jpg`,caption_url:`/leaders/kapsula-${i===0?'transfer':'ai'}-ar.vtt`,caption_url_en:`/leaders/kapsula-${i===0?'transfer':'ai'}-en.vtt`}));
export const editionStories:LeaderPost[] = editionPosts.slice(0,3).map(p=>({...p,id:`story-${p.id}`,kind:'story',highlight:true,featured:false,body:p.body.split('\n\n')[1],body_en:p.body_en?.split('\n\n')[1]||null}));
export const editionAll = [...editionPosts,...editionVideos,...editionStories];
