import type {LeaderPost} from './types';
type Language='ar'|'en'|'ko';
type Copy=Record<Language,string>;
export type MedicalChannel='all'|'korea'|'transfer'|'manufacturing'|'people';
export type MedicalReading={id:string;channel:MedicalChannel;title:Copy;intro:Copy;body:Copy;question:Copy;source?:{label:string;url:string;date?:string};visual:'lab'|'knowledge'|'network'|'quality';};
export const medicalChannels:{id:MedicalChannel;label:Copy}[]=[
 {id:'all',label:{ar:'كل القراءات',en:'All readings',ko:'모든 글'}},
 {id:'korea',label:{ar:'من كوريا',en:'From Korea',ko:'한국에서'}},
 {id:'transfer',label:{ar:'نقل التقنية',en:'Technology transfer',ko:'기술 이전'}},
 {id:'manufacturing',label:{ar:'التصنيع المحلي',en:'Local manufacturing',ko:'현지 제조'}},
 {id:'people',label:{ar:'المعرفة والفرق',en:'Knowledge & teams',ko:'지식·인재'}},
];
// These are editorial readings about independent institutions, not affiliations.
export const medicalReadings:MedicalReading[]=[
 {id:'korea-biomanufacturing',channel:'korea',visual:'lab',
 title:{ar:'في كوريا، المعرفة الدوائية نفسها تعبر الحدود.',en:'In Korea, pharmaceutical know-how crosses borders too.',ko:'한국에서는 제약 지식도 국경을 넘습니다.'},
 intro:{ar:'الفرصة لا تنتهي عند منتج يمكن استيراده. قد تبدأ من معرفة يستطيع فريقك امتلاكها.',en:'The opportunity extends beyond a product you can import, to knowledge your team can acquire.',ko:'기회는 수입 가능한 제품을 넘어 우리 팀이 습득할 수 있는 지식으로 이어집니다.'},
 body:{ar:'من المصدر: أعلنت منظمة الصحة العالمية في فبراير 2022 إنشاء مركز عالمي للتدريب على التصنيع الحيوي في كوريا، يجمع التدريب التقني والتطبيق العملي.\n\nقراءة VisionSeek: عندما تنظر مؤسسة إلى كوريا، يستحق رصيد المعرفة اهتمامًا مثل رصيد المنتجات. ما يتعلمه الفريق ويستطيع استخدامه محليًا قد يوسّع اختيارات المؤسسة لسنوات.\n\nهذه قراءة في تجربة قائمة؛ مواعيد البرامج وشروطها تُراجع لدى الجهة المنظمة.',en:'From the source: in February 2022, WHO announced a global biomanufacturing training hub in Korea, combining technical and practical training.\n\nVisionSeek perspective: institutions looking at Korea can consider its knowledge base alongside its products. What a team learns and can use locally may broaden its options for years.\n\nThis is a reading of an established initiative. Check programme dates and eligibility with the organiser.',ko:'출처에서: WHO는 2022년 2월 한국에 기술 교육과 실습을 결합한 글로벌 바이오 제조 교육 허브 설립을 발표했습니다.\n\nVisionSeek의 관점: 한국의 제품과 함께 축적된 지식에도 주목할 수 있습니다. 팀이 배우고 현지에서 활용하는 지식은 기관의 선택지를 넓힐 수 있습니다.\n\n기존 사례를 살펴보는 글입니다. 일정과 지원 자격은 주관 기관에서 확인하세요.'},
 question:{ar:'أي معرفة لو امتلكها فريقك، ستغيّر ما تستطيع مؤسستك فعله؟',en:'What knowledge would change what your institution can do?',ko:'어떤 지식이 귀 기관이 할 수 있는 일을 바꿀까요?'},
 source:{label:'WHO · Global biomanufacturing training hub',date:'2022-02-23',url:'https://www.who.int/news/item/23-02-2022-moving-forward-on-goal-to-boost-local-pharmaceutical-production-who-establishes-global-biomanufacturing-training-hub-in-republic-of-korea'}},
 {id:'beyond-the-license',channel:'transfer',visual:'network',
 title:{ar:'الترخيص يفتح الباب. ما الذي يجعل القدرة تعمل؟',en:'A licence opens the door. What makes the capability work?',ko:'라이선스는 문을 엽니다. 역량을 작동시키는 것은 무엇일까요?'},
 intro:{ar:'من حق الاستخدام إلى معرفة يستطيع فريق محلي تطبيقها؛ هنا يتّسع معنى نقل التقنية.',en:'From permission to use a technology to know-how a local team can apply.',ko:'기술 사용 권리에서 현지 팀이 활용할 수 있는 노하우까지.'},
 body:{ar:'من المصدر: يعرض برنامج HTAP التابع لمنظمة الصحة العالمية نقل التقنية في سياق يشمل الحقوق والمعرفة والتدريب والتصنيع والوصول إلى السوق.\n\nقراءة VisionSeek: الاتفاق على إتاحة تقنية بداية مهمة. لكن القيمة للمؤسسة تظهر فيما يصبح ممكنًا داخلها: فريق يفهم، ومعرفة تتراكم، وقدرة تستطيع الاستمرار.\n\nقراءة نموذج عالمي تساعدنا على رؤية الصورة الأوسع، مع اختلاف نطاق كل مؤسسة ودورها.',en:'From the source: WHO’s HTAP places technology transfer in a context that includes rights, know-how, training, manufacturing and market access.\n\nVisionSeek perspective: access to a technology is an important start. Institutional value emerges in what becomes possible internally: understanding, accumulated knowledge and a capability that can be sustained.\n\nGlobal models help us see the wider picture, while each institution’s role and scope differ.',ko:'출처에서: WHO의 HTAP는 권리, 노하우, 교육, 제조, 시장 접근을 함께 고려하며 기술 이전을 다룹니다.\n\nVisionSeek의 관점: 기술 접근은 중요한 출발점입니다. 기관의 가치는 내부에서 가능해지는 이해, 지식 축적, 지속 가능한 역량에서 드러납니다.\n\n글로벌 모델은 더 넓은 시야를 제공하지만 각 기관의 역할과 범위는 다릅니다.'},
 question:{ar:'ما الذي سيبقى داخل مؤسستك بعد توقيع الاتفاق؟',en:'What will remain inside your institution after the agreement?',ko:'계약 이후 귀 기관 안에는 무엇이 남을까요?'},
 source:{label:'WHO · How HTAP works',url:'https://www.who.int/initiatives/who-health-technology-access-programme/how-htap-works'}},
 {id:'manufacturing-access',channel:'manufacturing',visual:'quality',
 title:{ar:'التصنيع المحلي يبدأ أحيانًا بباب كان مغلقًا.',en:'Local manufacturing can begin by opening a closed door.',ko:'현지 제조는 닫혀 있던 문을 여는 데서 시작될 수 있습니다.'},
 intro:{ar:'كيف تساعد إتاحة الحقوق ونقل التقنية على توسيع خريطة التصنيع؟',en:'How can access to rights and technology transfer broaden the manufacturing map?',ko:'권리 확보와 기술 이전은 제조 기반을 어떻게 넓힐 수 있을까요?'},
 body:{ar:'من المصدر: تربط Medicines Patent Pool الترخيص الطوعي وتيسير نقل التقنية بدعم التصنيع المحلي والإقليمي. وتعرض مسارات للعمل مع أصحاب الابتكار والمصنّعين.\n\nقراءة VisionSeek: امتلاك السوق للاحتياج لا يكفي وحده. قد تحتاج الفرصة إلى اتصال بين حق الاستخدام والمعرفة والمؤسسة القادرة على استيعابها.\n\nالدرس للقائد: حين ترى قدرة مهمة في الخارج، وسّع السؤال من «هل نشتري المنتج؟» إلى «هل توجد مساحة لامتلاك القدرة محليًا؟».',en:'From the source: Medicines Patent Pool connects voluntary licensing and facilitated technology transfer with local and regional manufacturing, working with innovators and manufacturers.\n\nVisionSeek perspective: demand alone is not enough. An opportunity may depend on connecting rights, know-how and an institution able to absorb them.\n\nFor a leader, this widens the question from buying a product to exploring whether local capability is possible.',ko:'출처에서: Medicines Patent Pool은 자발적 라이선싱과 기술 이전 지원을 현지·지역 제조와 연결하며 혁신 기업 및 제조사와 협력합니다.\n\nVisionSeek의 관점: 수요만으로는 충분하지 않습니다. 기회는 사용 권리, 노하우, 이를 받아들일 기관의 연결에 달려 있을 수 있습니다.\n\n리더에게는 제품 구매를 넘어 현지 역량 구축의 가능성을 살펴보는 질문이 됩니다.'},
 question:{ar:'ما الباب الذي ينقص مؤسستك: التقنية، المعرفة، أم الوصول إلى صاحبها؟',en:'What is missing: the technology, the know-how, or access to its owner?',ko:'기술, 노하우, 보유 기관에 대한 접근 중 무엇이 부족한가요?'},
 source:{label:'Medicines Patent Pool · Local & regional manufacturing',url:'https://medicinespatentpool.org/what-we-do/local-and-regional-manufacturing'}},
 {id:'knowledge-stays',channel:'people',visual:'knowledge',
 title:{ar:'التدريب الأقوى يعود مع صاحبه إلى المصنع.',en:'The strongest learning travels back to the factory.',ko:'가장 강력한 배움은 현장으로 돌아갑니다.'},
 intro:{ar:'ما قيمة المعرفة إذا انتهت بانتهاء الدورة؟',en:'What does learning leave behind when a course ends?',ko:'교육이 끝난 뒤 어떤 지식이 남을까요?'},
 body:{ar:'من المصدر: يعرض IVI في كوريا بناء القدرات من خلال التدريب العملي، والتدريب داخل المواقع، والاستشارات، ومصادر التعلم.\n\nقراءة VisionSeek: قيمة التعلم لا تُختزل في حضور برنامج. الأهم ما يستطيع الفريق فهمه واستخدامه ومشاركته بعد عودته.\n\nلهذا يستحق التدريب أن يظهر في نقاش نقل القدرة باعتباره جزءًا من المعرفة التي تبقى داخل المؤسسة، لا نشاطًا منفصلًا عنها.',en:'From the source: Korea’s IVI describes capacity building through hands-on learning, on-site training, consultation and learning resources.\n\nVisionSeek perspective: learning is more than attending a programme. What matters is what a team can understand, use and share afterwards.\n\nTraining deserves a place in the capability-transfer conversation as knowledge that remains in an institution.',ko:'출처에서: 한국의 IVI는 실습, 현장 교육, 자문, 학습 자료를 통한 역량 강화를 소개합니다.\n\nVisionSeek의 관점: 배움은 프로그램 참석 그 이상입니다. 이후 팀이 이해하고 활용하며 공유할 수 있는 것이 중요합니다.\n\n교육은 기관 안에 남는 지식으로서 역량 이전에 관한 대화에 포함될 가치가 있습니다.'},
 question:{ar:'ما الخبرة التي تريد أن تبقى مع فريقك، لا مع شخص واحد فقط؟',en:'What expertise should remain with your team, not just one person?',ko:'한 사람을 넘어 팀에 남아야 할 전문성은 무엇인가요?'},
 source:{label:'International Vaccine Institute · Build Capacity',url:'https://www.ivi.int/what-we-do/build-capacity/'}},
 {id:'read-the-announcement',channel:'transfer',visual:'network',
 title:{ar:'خبر عن اختراق علمي. ماذا يعني لمؤسستك؟',en:'A scientific breakthrough. What does it mean for your institution?',ko:'과학적 돌파구는 귀 기관에 어떤 의미일까요?'},
 intro:{ar:'بين البحث المنشور، والتقنية المستخدمة، والقدرة القابلة للنقل فروق تستحق الانتباه.',en:'Published research, technology in use and a transferable capability are different things.',ko:'발표된 연구, 실제 활용되는 기술, 이전 가능한 역량은 서로 다릅니다.'},
 body:{ar:'قد يلهمك عنوان علمي قوي، لكنه وحده لا يخبرك أن مؤسستك تستطيع الاستفادة من النتيجة الآن.\n\nنقرأ الخبر ونحتفظ بالفضول، مع الانتباه إلى حالته: هل نتحدث عن بحث، أم استخدام قائم، أم معرفة يمكن نقلها؟ كل حالة تفتح نقاشًا مختلفًا.\n\nهذا تمييز يساعد على فهم حركة القطاع وتوسيع زاوية القرار.',en:'A strong scientific headline can inspire without showing that an institution can use the result today.\n\nWe can stay curious while noticing its status: research, an existing application, or transferable know-how. Each opens a different conversation.\n\nThis distinction helps us read the sector and broaden the decision perspective.',ko:'인상적인 과학 뉴스가 영감을 줄 수 있지만 기관이 지금 그 결과를 활용할 수 있음을 보여 주는 것은 아닙니다.\n\n호기심을 유지하며 연구인지, 기존 적용 사례인지, 이전 가능한 노하우인지 살펴볼 수 있습니다. 각 상태는 서로 다른 대화를 엽니다.\n\n이 구분은 산업 흐름을 읽고 의사결정의 시야를 넓히는 데 도움이 됩니다.'},
 question:{ar:'ما الفرق بين ما قرأناه، وما أصبح متاحًا لمؤسستنا فعلًا؟',en:'What separates what we read from what our institution can actually access?',ko:'읽은 내용과 우리 기관이 실제로 접근할 수 있는 것 사이의 차이는 무엇인가요?'}},
];
export function readingPost(r:MedicalReading,locale:Language):LeaderPost {
 return {id:r.id,title:r.title.ar,title_en:r.title[locale],body:r.intro.ar+'\n\n'+r.body.ar,body_en:r.intro[locale]+'\n\n'+r.body[locale],kind:'note',topic:'capabilities',media_path:null,media_type:null,source_url:r.source?.url||null,source_label:r.source?.label||null,status:'published',featured:false,highlight:false,published_at:null,expires_at:null,created_at:'2026-10-03T18:00:00Z',seed:true};
}
export function medicalChannel(post:LeaderPost):MedicalChannel {
 const known=medicalReadings.find(r=>r.id===post.id);if(known)return known.channel;
 return post.topic==='leadership'?'people':post.topic==='innovation'?'manufacturing':'transfer';
}
