'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState,type FormEvent,type MouseEvent} from 'react';
import type {Session} from '@supabase/supabase-js';
import {Plus,Save,Eye,ArrowLeft,LogOut,Archive,RefreshCw,FileText} from 'lucide-react';
import {leadersClient} from '@/lib/leaders/client';
import {draftContentSchema,emptyReportDraft,reviewGaps,type ReportDraft,type ReportDraftContent} from '@/lib/reports/drafts';
import styles from './studio.module.css';

const messages:Record<string,[string,string]>={SIGN_IN_REQUIRED:['سجّل الدخول بحساب الإدارة.','Sign in with an editor account.'],EDITOR_REQUIRED:['هذا الحساب لا يملك صلاحية إدارة التقارير.','This account is not an editor.'],REPORTS_NOT_INSTALLED:['حفظ التقارير ينتظر إعداد قاعدة البيانات.','Report storage is not installed yet.'],DATABASE_UNAVAILABLE:['تعذّر الاتصال بالحفظ. تعديلاتك ما زالت في النموذج؛ حاول مجددًا.','Storage unavailable. Your edits remain in the form; retry.'],REVISION_CONFLICT:['تغيّرت المسودة في جلسة أخرى. صدّر تعديلاتك قبل تحديث القائمة حتى لا تفقدها.','Draft changed in another session. Export your edits before refreshing.'],DRAFT_EXISTS:['حُفظ هذا المعرف من قبل. حدّث القائمة وافتح المسودة الموجودة.','This draft ID already exists. Refresh and open it.'],INCOMPLETE_REVIEW_DRAFT:['أكمل العنوان والملخص والمتن والمنهج والحدود بلغة واحدة على الأقل، وأضف الكاتب ومصدرًا.','Complete title, summary, body, methods and limitations in at least one language, with an author and a source.'],INVALID_INPUT:['راجع الحقول وروابط HTTPS وأطوال النصوص.','Check field lengths and HTTPS links.'],INPUT_TOO_LARGE:['المسودة كبيرة جدًا. قلّل حجم النص قبل الحفظ؛ الحد الحالي 100 كيلوبايت.','Draft exceeds the current 100 KB save limit. Shorten the text.']};
const kinds=[['report','تقرير بحثي','Research report'],['brief','إحاطة','Brief'],['working_paper','ورقة عمل','Working paper'],['evidence_review','مراجعة أدلة','Evidence review']];
export default function ReportsStudio({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar',base=ar?'/ar':'';const t=(a:string,e:string)=>ar?a:e;
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[authorized,setAuthorized]=useState(false);
 const [email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [items,setItems]=useState<ReportDraft[]>([]),[current,setCurrent]=useState<ReportDraft|null>(null),[newId,setNewId]=useState('');
 const [draft,setDraft]=useState<ReportDraftContent>(emptyReportDraft),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState(false),[language,setLanguage]=useState<'ar'|'en'>(locale),[filter,setFilter]=useState('active');
 const msg=useCallback((code:string)=>messages[code]?.[locale==='ar'?0:1]||(locale==='ar'?'تعذّر إتمام العملية. حاول مجددًا.':'Could not complete the action. Retry.'),[locale]);
 const api=useCallback(async(path='',method='GET',body?:unknown)=>{const {data}=await leadersClient().auth.getSession();if(!data.session)throw new Error('SIGN_IN_REQUIRED');const response=await fetch(`/api/reports/drafts${path}`,{method,headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'REQUEST_FAILED');return value;},[]);
 useEffect(()=>{let alive=true;try{const client=leadersClient();void client.auth.getSession().then(({data})=>{if(alive){setSession(data.session);setChecking(false);}}).catch(()=>{if(alive){setError(msg('DATABASE_UNAVAILABLE'));setChecking(false);}});const {data}=client.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setAuthorized(false);setItems([]);setCurrent(null);setDraft(emptyReportDraft());setDirty(false);}});return()=>{alive=false;data.subscription.unsubscribe();};}catch{queueMicrotask(()=>{setChecking(false);setError(msg('DATABASE_UNAVAILABLE'));});}},[msg]);
 useEffect(()=>{if(!session)return;let alive=true;void api().then(data=>{if(alive){setItems(data.items);setAuthorized(true);setError('');}}).catch(e=>{if(alive){setAuthorized(false);setError(msg(e instanceof Error?e.message:''));}});return()=>{alive=false;};},[session,api,msg]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function canLeave(){return !dirty||window.confirm(t('توجد تعديلات غير محفوظة. هل تريد تركها؟','Discard unsaved changes?'));}
 function navigate(e:MouseEvent<HTMLAnchorElement>){if(busy||!canLeave())e.preventDefault();}
 function edit(item:ReportDraft){if(!canLeave())return;setCurrent(item);setDraft(item.content);setNewId('');setDirty(false);setPreview(false);setError('');setNotice('');}
 function create(){if(!canLeave())return;setCurrent(null);setDraft(emptyReportDraft());setNewId(crypto.randomUUID());setDirty(false);setPreview(false);setError('');setNotice('');}
 function change<K extends keyof ReportDraftContent>(key:K,value:ReportDraftContent[K]){setDraft(old=>({...old,[key]:value}));setDirty(true);setNotice('');}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await leadersClient().auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword('');}catch{setError(t('تعذّر الدخول. راجع بيانات الحساب داخل الصفحة وحاول مجددًا.','Could not sign in. Check your account details and retry.'));}finally{setBusy(false);}}
 async function refresh(){if(!canLeave())return;setLoading(true);setError('');try{const data=await api();setItems(data.items);setCurrent(null);setNewId('');setDraft(emptyReportDraft());setDirty(false);setPreview(false);setAuthorized(true);}catch(e){setError(msg(e instanceof Error?e.message:''));}finally{setLoading(false);}}
 async function save(status:ReportDraft['status']='draft'){
  setError('');setNotice('');const parsed=draftContentSchema.safeParse(draft);if(!parsed.success){setError(msg('INVALID_INPUT'));return;}
  if(status==='review'&&!Object.values(reviewGaps(parsed.data)).every(Boolean)){setError(msg('INCOMPLETE_REVIEW_DRAFT'));return;}
  setBusy(true);try{const body=current?{content:parsed.data,status,revision:current.revision}:{id:newId||crypto.randomUUID(),content:parsed.data};const data=await api(current?`/${current.id}`:'',current?'PATCH':'POST',body);const item=data.item as ReportDraft;setItems(old=>[item,...old.filter(x=>x.id!==item.id)]);setCurrent(item);setDraft(item.content);setNewId('');setDirty(false);setNotice(t('تم الحفظ في حسابك. التقرير غير منشور للجمهور.','Saved to your account. This report is not public.'));}catch(e){setError(msg(e instanceof Error?e.message:''));}finally{setBusy(false);}
 }
 function exportDraft(){const blob=new Blob([JSON.stringify({format:'visionseek-report-draft',version:1,content:draft},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='visionseek-report-draft.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const label=(state:string)=>state==='review'?t('جاهز للمراجعة','Ready for review'):state==='archived'?t('مؤرشف','Archived'):t('مسودة','Draft');
 const selected=!!current||!!newId;const key=(prefix:'title'|'summary'|'methodology'|'limitations')=>`${prefix}_${language}` as keyof ReportDraftContent;
 return <div className={styles.page} dir={ar?'rtl':'ltr'} lang={locale}><header className={styles.header}><Link href={`${base}/reports`} onClick={navigate}>VISIONSEEK <span>/ {t('إدارة التقارير','REPORTS STUDIO')}</span></Link><nav><Link href={`${base}/reports`} onClick={navigate}>{t('عرض القسم','View reports')}</Link><Link href={`${ar?'':'/ar'}/reports/studio`} onClick={navigate}>{ar?'EN':'العربية'}</Link>{session&&<button onClick={async()=>{if(canLeave()){const {error}=await leadersClient().auth.signOut();if(error)setError(t('تعذّر تسجيل الخروج. حاول مجددًا.','Sign-out failed. Retry.'));}}}><LogOut size={16}/>{t('خروج','Sign out')}</button>}</nav></header>
 <main className={styles.main} id="main-content">
 <div className={styles.title}><div><p>RESEARCH / EDITORIAL WORKSPACE</p><h1>{t('إدارة التقارير','Reports studio')}</h1><span>{t('جهّز الإصدار، واحفظ أدلته، وراجعه قبل النشر.','Prepare an edition, preserve its evidence and review it before publication.')}</span></div><span className={styles.private}>{t('مساحة خاصة بالمحررين','Private editor workspace')}</span></div>
 {error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
 {checking?<p role="status">{t('جاري التحقق من الدخول…','Checking sign-in…')}</p>:!session?<form className={styles.login} onSubmit={login}><h2>{t('دخول الإدارة','Editor sign-in')}</h2><p>{t('استخدم حساب الموقع المصرّح له بتحرير التقارير.','Use your existing account with website editor access.')}</p><label>{t('البريد الإلكتروني','Email')}<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('كلمة المرور','Password')}<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} className={styles.primary}>{busy?t('جاري الدخول…','Signing in…'):t('دخول','Sign in')}</button></form>:!authorized?<section className={styles.login}><h2>{t('التحقق من صلاحية الإدارة','Checking editor access')}</h2><p>{t('تظهر التقارير الخاصة بعد التحقق من صلاحية حسابك.','Private drafts load once editor access is verified.')}</p><button onClick={()=>void refresh()} disabled={loading||busy}>{t('إعادة المحاولة','Retry')}</button></section>:<>
 <div className={styles.layout}><aside className={styles.sidebar}><button className={styles.primary} onClick={create} disabled={busy}><Plus size={18}/>{t('تقرير جديد','New report')}</button><div className={styles.queueHead}><h2>{t('تقاريري','My reports')}</h2><button onClick={()=>void refresh()} disabled={busy||loading} aria-label={t('تحديث القائمة','Refresh list')}><RefreshCw size={16}/></button></div><label>{t('عرض','Show')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">{t('المسودات والمراجعة','Drafts & review')}</option><option value="archived">{t('الأرشيف','Archive')}</option></select></label><p className={styles.queueNote}>{t('أحدث 200 مسودة في حسابك','Your latest 200 drafts')}</p>{items.filter(item=>filter==='archived'?item.status==='archived':item.status!=='archived').map(item=><button key={item.id} className={styles.queueItem} aria-pressed={current?.id===item.id} onClick={()=>edit(item)} disabled={busy}><span>{label(item.status)}</span><strong>{item.content[`title_${locale}`]||item.content.title_ar||item.content.title_en}</strong><small>{new Date(item.updated_at).toLocaleDateString(ar?'ar-EG':'en-GB')} · {t('تعديل','Revision')} {item.revision}</small></button>)}{!items.length&&<p className={styles.queueNote}>{t('ابدأ بإضافة تقريرك الأول.','Create your first report to begin.')}</p>}</aside>
 <section className={styles.workspace} aria-label={t('محرر التقرير','Report editor')}>
 {!selected?<div className={styles.welcome}><FileText size={44}/><h2>{t('كل إصدار يبدأ هنا.','Every edition starts here.')}</h2><p>{t('أدخل المحتوى بالعربية أو الإنجليزية، وأضف الأقسام والمراجع والمنهج وحدود النتائج. الحفظ خاص بحسابك ولا ينشر التقرير.','Write in Arabic or English. Add sections, references, methods and limitations. Saving keeps the report private to your account.')}</p><button className={styles.primary} onClick={create}><Plus size={18}/>{t('إدخال تقرير جديد','Create a report')}</button></div>:<>
 <div className={styles.toolbar}><strong>{current?label(current.status):t('تقرير جديد','New report')}{dirty?' •':''}</strong><div><button aria-pressed={!preview} onClick={()=>setPreview(false)}>{t('تحرير','Edit')}</button><button aria-pressed={preview} onClick={()=>setPreview(true)}><Eye size={16}/>{t('معاينة','Preview')}</button></div><div role="group" aria-label={t('لغة المحتوى','Content language')}><button aria-pressed={language==='ar'} onClick={()=>setLanguage('ar')}>العربية</button><button aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>English</button></div></div>
 {preview?<article className={styles.preview} dir={language==='ar'?'rtl':'ltr'} lang={language}><span>{t('معاينة خاصة · غير منشور','Private preview · unpublished')}</span><h2>{String(draft[key('title')])||t('عنوان التقرير','Report title')}</h2><p className={styles.summary}>{String(draft[key('summary')])}</p><p>{draft.author}</p>{draft.cover_url&&/^https:\/\//.test(draft.cover_url)&&<a href={draft.cover_url} target="_blank" rel="noreferrer">{t('فتح صورة الغلاف','Open cover image')} ↗</a>}{draft.sections.map((section,i)=><section key={i}><h3>{section[`heading_${language}`]}</h3><p>{section[`body_${language}`]}</p></section>)}<h3>{language==='ar'?'المنهج':'Methodology'}</h3><p>{String(draft[key('methodology')])}</p><h3>{language==='ar'?'الحدود':'Limitations'}</h3><p>{String(draft[key('limitations')])}</p><h3>{language==='ar'?'المصادر':'Sources'}</h3><ol>{draft.sources.map((s,i)=><li key={i}>{/^https:\/\//.test(s.url)?<a href={s.url} target="_blank" rel="noreferrer">{s.title||s.url}</a>:s.title}<p>{s.note}</p></li>)}</ol></article>:<form className={styles.form} onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}>
 <div className={styles.formSection}><h2>{t('01 / بطاقة الإصدار','01 / Publication details')}</h2><label>{t('العنوان','Title')} · {language==='ar'?'العربية':'English'}<input dir={language==='ar'?'rtl':'ltr'} value={String(draft[key('title')])} maxLength={240} onChange={e=>change(key('title'),e.target.value)}/></label><label>{t('الملخص التنفيذي','Executive summary')}<textarea dir={language==='ar'?'rtl':'ltr'} rows={5} maxLength={4000} value={String(draft[key('summary')])} onChange={e=>change(key('summary'),e.target.value)}/></label><div className={styles.twoCols}><label>{t('نوع الإصدار','Publication type')}<select value={draft.kind} onChange={e=>change('kind',e.target.value as ReportDraftContent['kind'])}>{kinds.map(([id,a,en])=><option key={id} value={id}>{t(a,en)}</option>)}</select></label><label>{t('الكاتب / فريق البحث','Author / research team')}<input value={draft.author} maxLength={200} onChange={e=>change('author',e.target.value)}/></label><label>{t('الموضوعات','Topics')}<input value={draft.topics} maxLength={300} onChange={e=>change('topics',e.target.value)}/></label><label>{t('النطاق الجغرافي','Geographic scope')}<input value={draft.country} maxLength={150} onChange={e=>change('country',e.target.value)}/></label></div></div>
 <div className={styles.formSection}><h2>{t('02 / متن التقرير','02 / Report sections')}</h2>{draft.sections.map((s,i)=><div className={styles.sectionEditor} key={i}><div className={styles.sectionBar}><strong>{t('قسم','Section')} {i+1}</strong><div><button type="button" disabled={!i} onClick={()=>{const v=[...draft.sections];[v[i-1],v[i]]=[v[i],v[i-1]];change('sections',v);}}>{t('لأعلى','Move up')}</button><button type="button" onClick={()=>change('sections',draft.sections.filter((_,n)=>n!==i))}>{t('حذف القسم','Remove')}</button></div></div><label>{t('عنوان القسم','Section heading')}<input dir={language==='ar'?'rtl':'ltr'} value={s[`heading_${language}`]} maxLength={240} onChange={e=>change('sections',draft.sections.map((v,n)=>n===i?{...v,[`heading_${language}`]:e.target.value}:v))}/></label><label>{t('النص','Text')}<textarea dir={language==='ar'?'rtl':'ltr'} rows={9} maxLength={25000} value={s[`body_${language}`]} onChange={e=>change('sections',draft.sections.map((v,n)=>n===i?{...v,[`body_${language}`]:e.target.value}:v))}/></label></div>)}<button type="button" disabled={draft.sections.length>=40} onClick={()=>change('sections',[...draft.sections,{heading_ar:'',heading_en:'',body_ar:'',body_en:''}])}><Plus size={16}/>{t('إضافة قسم','Add section')}</button></div>
 <div className={styles.formSection}><h2>{t('03 / الأدلة والمنهج','03 / Evidence and methods')}</h2><label>{t('المنهج المستخدم','Methodology')}<textarea dir={language==='ar'?'rtl':'ltr'} rows={4} maxLength={8000} value={String(draft[key('methodology')])} onChange={e=>change(key('methodology'),e.target.value)}/></label><label>{t('حدود النتائج وما لم يُحسم','Limitations and unknowns')}<textarea dir={language==='ar'?'rtl':'ltr'} rows={4} maxLength={6000} value={String(draft[key('limitations')])} onChange={e=>change(key('limitations'),e.target.value)}/></label>{draft.sources.map((s,i)=><div className={styles.sectionEditor} key={i}><div className={styles.sectionBar}><strong>{t('مرجع','Source')} {i+1}</strong><button type="button" onClick={()=>change('sources',draft.sources.filter((_,n)=>n!==i))}>{t('حذف','Remove')}</button></div>{(['title','url','note'] as const).map((k,n)=><label key={k}>{[t('عنوان المرجع والجهة','Title and publisher'),t('رابط المرجع','Source URL'),t('ما الذي يدعمه هذا المصدر؟','What does this source support?')][n]}<input dir={k==='url'?'ltr':'auto'} type={k==='url'?'url':'text'} value={s[k]} maxLength={k==='url'?2000:k==='note'?1200:300} onChange={e=>change('sources',draft.sources.map((v,idx)=>idx===i?{...v,[k]:e.target.value}:v))}/></label>)}</div>)}<button type="button" disabled={draft.sources.length>=100} onClick={()=>change('sources',[...draft.sources,{title:'',url:'',note:''}])}><Plus size={16}/>{t('إضافة مرجع','Add reference')}</button></div>
 <div className={styles.formSection}><h2>{t('04 / الغلاف والملفات','04 / Cover and files')}</h2><p>{t('أضف روابط HTTPS للملفات المتاحة لديك. رفع الملفات مباشرة غير متاح في هذه النسخة.','Add HTTPS links to your existing files. Direct file upload is not available in this version.')}</p><label>{t('رابط صورة الغلاف','Cover image URL')}<input dir="ltr" type="url" value={draft.cover_url} maxLength={2000} onChange={e=>change('cover_url',e.target.value)}/></label><label>{t('وصف الغلاف','Cover description')}<input value={draft.cover_alt} maxLength={300} onChange={e=>change('cover_alt',e.target.value)}/></label><label>{t('رابط ملف التقرير PDF','Report PDF URL')}<input dir="ltr" type="url" value={draft.report_file_url} maxLength={2000} onChange={e=>change('report_file_url',e.target.value)}/></label></div>
 </fieldset></form>}
 <div className={styles.saveBar}><div><button className={styles.primary} onClick={()=>void save()} disabled={busy}><Save size={17}/>{busy?t('جاري الحفظ…','Saving…'):t('حفظ مسودة','Save draft')}</button>{current&&<button disabled={busy||current.status==='archived'} onClick={()=>void save('review')}>{t('جاهز للمراجعة','Ready for review')}</button>}<button onClick={exportDraft} disabled={busy}>{t('تصدير نسخة JSON','Export JSON')}</button>{current&&<button disabled={busy} onClick={()=>void save(current.status==='archived'?'draft':'archived')}><Archive size={16}/>{current.status==='archived'?t('استعادة','Restore'):t('أرشفة','Archive')}</button>}</div><p>{t('«جاهز للمراجعة» حالة تنظيمية، وليست اعتمادًا علميًا أو نشرًا.','“Ready for review” is a workflow state, not scientific approval or publication.')}</p></div>
 </>}
 </section></div></>}
 <footer className={styles.footer}><Link href={`${base}/reports`} onClick={navigate}><ArrowLeft size={16}/>{t('العودة إلى التقارير','Back to reports')}</Link><span>{t('الحفظ خاص بحسابك · النشر مرحلة منفصلة','Private account storage · Publication is a separate step')}</span></footer>
 </main></div>;
}
