// Generated by npm run manage:registry. Edit modules/*.json and handovers/*.json.
export const manifestInputs: unknown[] = [
  {
    "schemaVersion": 1,
    "moduleId": "collaboration",
    "nameAr": "اعمل معنا",
    "nameEn": "Work with us",
    "description": "مسارات التعاون وطلب بناء القدرات.",
    "icon": "graduation",
    "sortOrder": 90,
    "publicRoutes": [
      "/ar/work-with-us"
    ],
    "adminEntryPoint": null,
    "owner": "مساحة اعمل معنا",
    "codeRef": "main @ ed7cb36",
    "docsUrl": null,
    "readiness": "development",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر التشغيلي لم يُسلّم بعد."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  },
  {
    "schemaVersion": 1,
    "moduleId": "leaders",
    "nameAr": "بيت القادة",
    "nameEn": "Leaders House",
    "description": "المحتوى والمنشورات والشخصيات التحريرية.",
    "icon": "newspaper",
    "sortOrder": 10,
    "publicRoutes": [
      "/ar/insights"
    ],
    "adminEntryPoint": "/ar/insights/studio",
    "owner": "مساحة بيت القادة",
    "codeRef": "main @ 108c883",
    "docsUrl": null,
    "readiness": "review",
    "capabilities": [
      {
        "action": "read",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "createDraft",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "editDraft",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "publish",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "archive",
        "enabled": true,
        "disabledReason": null
      }
    ],
    "permissions": [
      "read",
      "createDraft",
      "editDraft",
      "review",
      "publish",
      "archive"
    ],
    "agentTools": [],
    "editorAvailable": true,
    "workflowEnabled": true,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [
      "صلاحيات leaders_editors مستقلة عن الغرفة"
    ],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": [
      "كود المحرر موجود؛ الحفظ الحي عبر الغرفة غير متحقق."
    ]
  },
  {
    "schemaVersion": 1,
    "moduleId": "management",
    "nameAr": "غرفة الإدارة",
    "nameEn": "Management room",
    "description": "متابعة التكليفات والتسليمات والتكامل بين مساحات العمل.",
    "icon": "graduation",
    "sortOrder": 100,
    "publicRoutes": [],
    "adminEntryPoint": null,
    "owner": "مساحة غرفة الإدارة",
    "codeRef": "main @ ed7cb36",
    "docsUrl": null,
    "readiness": "review",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر التشغيلي لم يُسلّم بعد."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  },
  {
    "schemaVersion": 1,
    "moduleId": "opportunities",
    "nameAr": "فرص البحث والتطوير",
    "nameEn": "R&D opportunities",
    "description": "عرض الفرص ومسارات المشاركة الحالية.",
    "icon": "graduation",
    "sortOrder": 70,
    "publicRoutes": [
      "/ar/opportunities"
    ],
    "adminEntryPoint": null,
    "owner": "مساحة الفرص",
    "codeRef": "main @ ed7cb36",
    "docsUrl": null,
    "readiness": "development",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر التشغيلي لم يُسلّم بعد."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  },
  {
    "schemaVersion": 1,
    "moduleId": "programs",
    "nameAr": "البرامج",
    "nameEn": "Programs",
    "description": "تصميم البرامج ومتابعة تطوير الخدمة.",
    "icon": "compass",
    "sortOrder": 30,
    "publicRoutes": [
      "/ar/programs"
    ],
    "adminEntryPoint": null,
    "owner": "مساحة البرامج وHLO",
    "codeRef": "feat/ihsan-program-system @ dcaa5eb1b8a186a8b2c6280e21b6039300b2a4f6",
    "docsUrl": null,
    "readiness": "development",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر لم يندمج في هذا الإصدار بعد."
      }
    ],
    "permissions": [
      "read",
      "createDraft",
      "editDraft",
      "review",
      "publish",
      "archive"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": true,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  },
  {
    "schemaVersion": 1,
    "moduleId": "projects",
    "nameAr": "المشروعات",
    "nameEn": "Projects",
    "description": "ملفات المشروعات وتحديثاتها العامة؛ تحريرها التشغيلي قيد التكامل.",
    "icon": "graduation",
    "sortOrder": 50,
    "publicRoutes": [
      "/ar/projects",
      "/projects"
    ],
    "adminEntryPoint": null,
    "owner": "مساحة المشروعات",
    "codeRef": "main @ ed7cb36",
    "docsUrl": "https://github.com/visionseek1/visionseek-platform/blob/main/docs/projects/MANAGEMENT_ROOM_INTEGRATION.md",
    "readiness": "development",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر التشغيلي لم يُسلّم بعد."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [
      "معرّفات المشروعات ثابتة: VS-P07 وVS-P08",
      "المصدر العام: lib/projects؛ لا نسخ للسجلات الخاصة"
    ],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": [
      "ملفات المشروعات موجودة في main؛ محرر المسودات والنشر لم يُبنَ بعد."
    ]
  },
  {
    "schemaVersion": 1,
    "moduleId": "reports",
    "nameAr": "التقارير",
    "nameEn": "Reports",
    "description": "الأبحاث والتقارير ومراجعة الأدلة.",
    "icon": "chart",
    "sortOrder": 20,
    "publicRoutes": [
      "/ar/reports",
      "/reports"
    ],
    "adminEntryPoint": "/ar/reports/studio",
    "owner": "مساحة التقارير",
    "codeRef": "main @ 8feafd696046dece5fa7da3a69572efb4a3a8c81",
    "docsUrl": null,
    "readiness": "review",
    "capabilities": [
      {
        "action": "read",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "createDraft",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "editDraft",
        "enabled": true,
        "disabledReason": null
      },
      {
        "action": "archive",
        "enabled": true,
        "disabledReason": null
      }
    ],
    "permissions": [
      "read",
      "createDraft",
      "editDraft",
      "review",
      "publish",
      "archive"
    ],
    "agentTools": [],
    "editorAvailable": true,
    "workflowEnabled": true,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [
      "صلاحيات محرر التقارير مستقلة عن الغرفة"
    ],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": [
      "كود المحرر مدمج؛ الحفظ الحي عبر الغرفة غير متحقق."
    ]
  },
  {
    "schemaVersion": 1,
    "moduleId": "training",
    "nameAr": "التدريب",
    "nameEn": "Training",
    "description": "وحدة تجريبية لاختبار إضافة أقسام جديدة.",
    "icon": "graduation",
    "sortOrder": 40,
    "publicRoutes": [],
    "adminEntryPoint": null,
    "owner": "مساحة التدريب — بانتظار التأسيس",
    "codeRef": "docs/manage-room/MODULE-CONTRACT.md",
    "docsUrl": null,
    "readiness": "planned",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "لا توجد عمليات تشغيلية."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  },
  {
    "schemaVersion": 1,
    "moduleId": "website",
    "nameAr": "الموقع والهوية",
    "nameEn": "Website and positioning",
    "description": "صفحات المؤسسة ورحلة HLO والهوية والتنقّل.",
    "icon": "graduation",
    "sortOrder": 60,
    "publicRoutes": [
      "/ar",
      "/ar/about/what-we-do",
      "/ar/start"
    ],
    "adminEntryPoint": null,
    "owner": "مساحة محرر الموقع",
    "codeRef": "main @ ed7cb36",
    "docsUrl": null,
    "readiness": "development",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر التشغيلي لم يُسلّم بعد."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  },
  {
    "schemaVersion": 1,
    "moduleId": "workshops",
    "nameAr": "الورش",
    "nameEn": "Workshops",
    "description": "الورش ومحتواها في المصدر المشترك للموقع.",
    "icon": "graduation",
    "sortOrder": 80,
    "publicRoutes": [
      "/ar/workshops"
    ],
    "adminEntryPoint": null,
    "owner": "مساحة الورش",
    "codeRef": "main @ ed7cb36",
    "docsUrl": null,
    "readiness": "development",
    "capabilities": [
      {
        "action": "read",
        "enabled": false,
        "disabledReason": "المحرر التشغيلي لم يُسلّم بعد."
      }
    ],
    "permissions": [
      "read"
    ],
    "agentTools": [],
    "editorAvailable": false,
    "workflowEnabled": false,
    "healthEvidence": {
      "check": "فتح المحرر وحفظ مخرج بحساب مصرح",
      "checkedAt": null,
      "result": "unknown",
      "evidence": null
    },
    "migrations": [],
    "dependencies": [],
    "rollbackNotes": "إلغاء التسجيل لا يحذف المحتوى. الاستعادة مسؤولية الوحدة.",
    "acceptanceEvidence": []
  }
];
export const handoverInputs: unknown[] = [
  {
    "schemaVersion": 1,
    "id": "shared-workspace-integration",
    "moduleIds": [
      "management",
      "projects",
      "website",
      "leaders",
      "reports",
      "programs",
      "training",
      "opportunities",
      "workshops",
      "collaboration"
    ],
    "workspace": "مساحة غرفة الإدارة",
    "summary": "ربط الوحدات والتسليمات بمصدر مشترك، ورصد طلبات التغيير وآخر تحديثات main تلقائيًا داخل الغرفة.",
    "changedPaths": [
      "app/manage/",
      "app/api/manage/",
      "components/manage/",
      "lib/manage/",
      "db/visionseek-manage.sql",
      "modules/"
    ],
    "acceptance": [
      "كل وحدة تُكتشف من ملف تسجيلها دون تعديل قائمة في الغرفة.",
      "تظهر طلبات التغيير الحالية وتحديثات main بحالتها الفعلية.",
      "قراءة التكامل متاحة للمؤسس بعد التحقق من حسابه وصلاحيته الحالية.",
      "طلب تغيير الكود أو دمجه لا يعني نشره أو اعتماده تشغيليًا."
    ],
    "evidence": [
      "https://github.com/visionseek1/visionseek-platform/pull/41",
      "https://github.com/visionseek1/visionseek-platform/blob/main/docs/projects/MANAGEMENT_ROOM_INTEGRATION.md"
    ],
    "dependencies": [
      "GitHub العام للمشروع",
      "حساب Supabase الحالي",
      "التزام مساحات العمل بعقد التسليم المشترك"
    ],
    "remaining": [
      "مراجعة الواجهة بحساب المؤسس عبر حماية Vercel.",
      "محرر تحديثات المشروعات يحتاج تسليمًا مستقلًا وفق عقده.",
      "محتوى محادثات GPT لا ينتقل تلقائيًا؛ تُودع المخرجات في المستودع أو في مهمة بالغرفة."
    ]
  }
];
