export const hloSteps = [
  {
    ar: 'دراسة المؤسسة',
    en: 'Study the institution',
    titleAr: 'واقعها، قرارها، ومن يستطيع التحرك',
    titleEn: 'Its reality, its decision, and who can move',
    bodyAr: 'نبدأ بدراسة المؤسسة دراسة عميقة: واقعها، والقرار الذي تملكه، ومن يستطيع التحرك داخلها.',
    bodyEn: 'Begin by studying the institution deeply: its reality, the decision it holds, and who can move inside it.',
    noteAr: 'الدراسة بوابة دخول، وليست المنتج.',
    noteEn: 'The study is an entry gate, not the product.',
  },
  {
    ar: 'رصد المتاح الآن',
    en: 'See what is possible now',
    titleAr: 'ما الذي يعمل فعلًا، لا ما يُبنى من الصفر',
    titleEn: 'What is actually running, not what would be built from scratch',
    bodyAr: 'ندرُس القدرات والفرص المتاحة الآن. الرصد واسع، مثل البحث والتطوير. المصدر أي نظام شغال فعلًا في العالم، بمصدر أولي. كوريا مكان الرصد والجسر، وليست سقف العرض، وليست المنتج.',
    bodyEn: 'Study the capabilities and opportunities available now. The scan is wide, as research and development is. The source is any system actually running in the world, from a primary source. Korea is where we watch and the bridge — not the ceiling of the offer, and not the product.',
    noteAr: 'الذكاء الاصطناعي يرفع سقف المتاح. ليس اسم المنتج، وليس الخدمة التي تُباع.',
    noteEn: 'AI raises the ceiling of what is available. It is not the product name, and it is not the service being sold.',
  },
  {
    ar: 'قدرة واحدة',
    en: 'One capability',
    titleAr: 'ما يرفع فاعلية هذه المؤسسة',
    titleEn: 'What raises this institution’s effectiveness',
    bodyAr: 'الاختيار ضيق: قدرة واحدة تجعل هذه المؤسسة أكثر فاعلية. ما لا يرفع فاعليتها يُترك، حتى لو كان قويًا في مكان آخر.',
    bodyEn: 'The choice is narrow: one capability that makes this institution more effective. What does not raise its effectiveness is left, even if it is strong somewhere else.',
    noteAr: 'لا كتالوج، ولا قدرة تُنقل لأنها نجحت عند غيركم.',
    noteEn: 'Not a catalog, and not a capability moved only because it worked for someone else.',
  },
  {
    ar: 'دخول وتركيب',
    en: 'Enter and install',
    titleAr: 'القدرة تُركَّب على أرض الواقع',
    titleEn: 'The capability is installed on the ground',
    bodyAr: 'ندخل على أرض الواقع ونركّب هذه القدرة داخل المؤسسة. هذا جوهر HLO، لا ملحق اختياري.',
    bodyEn: 'We enter on the ground and install this capability inside the institution. This is the essence of HLO, not an optional appendix.',
    noteAr: 'التقرير ورقة داخل المسار. ليس العرض، وليس نقطة توقف.',
    noteEn: 'The report is a paper inside the path. It is not the offer, and not a place to stop.',
  },
  {
    ar: 'بقاء بعد التشغيل',
    en: 'Stay after it runs',
    titleAr: 'ما رُكّب يتطور من الاستخدام الحقيقي',
    titleEn: 'What was installed evolves from real use',
    bodyAr: 'نبقى مرتبطين بالمؤسسة، نتابع التنفيذ، ونطوّر ما تم تنفيذه بعد أن يشتغل.',
    bodyEn: 'We stay connected to the institution, follow the implementation, and develop what was implemented after it is running.',
    noteAr: 'التشغيل بداية التطوير، لا نهاية المسار.',
    noteEn: 'Operation is the start of development, not the end of the path.',
  },
] as const;

export const hloFields = [
  {ar: 'الجهة والدولة', en: 'The entity and the country'},
  {ar: 'دور المرسِل، وهل يفتح الباب', en: 'The sender’s role, and whether they open the door'},
  {ar: 'القرار، أو ما الذي يجب أن يتحسن', en: 'The decision, or what must improve'},
  {ar: 'ماذا يفشل اليوم', en: 'What fails today'},
  {ar: 'هل الدخول إلى أرض الواقع متاح', en: 'Whether entry on the ground is available'},
] as const;
