import {t,type Entry,type SectionId,type Text,type Block} from './schema';
import {communities} from '@/components/capability/content';
const guide=(section:SectionId,slug:string,title:Text,summary:Text,blocks:Block[],related:string[]=[],image='cities'):Entry=>({section,slug,title,summary,blocks,related,image,category:t('Guide & operating model','دليل ونموذج تشغيل'),status:t('VisionSeek approach','منهج VisionSeek')});
export const guideEntries:Entry[]=[
 guide('work-with-us','new-to-visionseek',t('New to VisionSeek','ابدأ مع VisionSeek'),t('Find where your need, knowledge or capability fits.','اعرف أين يناسب احتياجك أو معرفتك أو قدرتك.'),[
 {title:t('Start with your contribution','ابدأ بمساهمتك'),items:[t('An institution: describe an important capability you cannot achieve today.','مؤسسة: صف قدرة مهمة لا تستطيع تحقيقها اليوم.'),t('An expert: show the knowledge or judgment you can bring to a mission.','خبير: اعرض المعرفة أو الحكم المتخصص الذي تقدمه للمهمة.'),t('A research or technology team: show what exists, what is proven and what remains uncertain.','فريق بحث أو تقنية: وضّح ما هو موجود وما ثبت وما لم يُحسم.'),t('A partner: identify an operating context, route to adoption or resource you can contribute.','شريك: حدد سياق تشغيل أو مسار تبنٍ أو موردًا يمكنك المساهمة به.')]},
 {title:t('Then follow the evidence','ثم اتبع الأدلة'),body:t('Read the method, explore a relevant program concept and prepare a short note. A scoping discussion should determine whether a meaningful next test exists. Commitments are agreed separately.','اقرأ المنهج، واستكشف تصور برنامج مناسبًا، وجهّز مذكرة قصيرة. تحدد مناقشة النطاق إن كان هناك اختبار تالٍ مفيد. تُتفق الالتزامات بصورة منفصلة.')}
 ],['/method','/programs','/work-with-us/prepare-a-concept']),
 guide('work-with-us','how-to-respond',t('How to respond','كيف تشارك؟'),t('Prepare a contribution that can be assessed on its evidence.','جهّز مساهمة يمكن تقييمها بأدلتها.'),[
 {title:t('The concept note','مذكرة التصور'),items:[t('Define the capability and the beneficiary in ordinary language.','حدد القدرة والمستفيد بلغة واضحة.'),t('Describe the current limit and the evidence behind it.','صف الحد الحالي والدليل عليه.'),t('Explain your approach, contribution and relevant experience.','اشرح المسار ومساهمتك وخبرتك المرتبطة.'),t('Propose a first test, measures, resources and a time estimate.','اقترح اختبارًا أولًا ومقاييس وموارد وتقديرًا زمنيًا.'),t('Identify risks, dependencies and what would make you stop.','حدد المخاطر والاعتماديات وما الذي يجعلك تتوقف.')]},
 {title:t('Submission route','طريقة الإرسال'),body:t('The preparation tool creates a note you can download or open in your email app. You review and send it yourself. The website does not store or automatically submit it, and does not issue a receipt or selection promise.','تجهّز الأداة مذكرة يمكنك تنزيلها أو فتحها في بريدك. تراجعها وترسلها بنفسك. الموقع لا يخزنها أو يرسلها تلقائيًا، ولا يصدر إيصال استلام أو وعد اختيار.')},
 {title:t('Information to include','المعلومات المناسبة'),body:t('Use public or shareable evidence for the first conversation. Detailed confidential material can be handled later through an agreed process.','استخدم أدلة عامة أو مسموحًا بمشاركتها في النقاش الأول. يمكن التعامل مع التفاصيل السرية لاحقًا عبر إجراء متفق عليه.')}
 ],['/work-with-us/prepare-a-concept','/work-with-us/review-and-selection','/opportunities']),
 guide('work-with-us','prepare-a-concept',t('Prepare a concept note','جهّز مذكرة تصور'),t('Turn an important possibility into a clear, reviewable proposal.','حوّل احتمالًا مهمًا إلى مقترح واضح وقابل للمراجعة.'),[
 {title:t('A useful first conversation','نقاش أول مفيد'),body:t('Complete the fields below with what you know. Mark unknowns explicitly. Download a Markdown note for your records or prepare an email to VisionSeek. Nothing is sent or saved to a server by this tool.','املأ الحقول بما تعرفه وحدد المجهول صراحة. نزّل مذكرة Markdown للاحتفاظ بها أو جهّز بريدًا إلى VisionSeek. الأداة لا ترسل أو تحفظ شيئًا على خادم.')}
 ],['/about/program-questions','/opportunities']),
 guide('work-with-us','review-and-selection',t('Review & selection','المراجعة والاختيار'),t('A proposed evidence-led path from first contact to an authorized test.','مسار مقترح تقوده الأدلة من التواصل الأول إلى اختبار معتمد.'),[
 {title:t('Five review gates','خمس بوابات للمراجعة'),items:[t('Fit: an important capability, identifiable beneficiary and alignment with VisionSeek.','الملاءمة: قدرة مهمة ومستفيد محدد واتساق مع VisionSeek.'),t('Evidence: a real constraint and a plausible way to change it.','الأدلة: مانع حقيقي ومسار معقول لتغييره.'),t('Team: the expertise and access needed to attempt the work.','الفريق: الخبرة والوصول اللازمان لمحاولة التنفيذ.'),t('Test: measurable outcomes, baseline and stop conditions.','الاختبار: نتائج مقاسة وخط أساس وشروط توقف.'),t('Authorization: an owner, scope, resources, terms and explicit approvals.','الاعتماد: مسؤول ونطاق وموارد وشروط واعتمادات صريحة.')]},
 {title:t('Decision record','سجل القرار'),body:t('Each review should record accept, decline, clarify or hold; the evidence used; the responsible reviewer; unresolved conditions; and the next action. Conflicted reviewers do not approve their own work. No response-time guarantee has been adopted.','تسجل المراجعة قبولًا أو رفضًا أو طلب توضيح أو تعليقًا، والأدلة المستخدمة والمراجع المسؤول والشروط غير المحسومة والخطوة التالية. لا يعتمد صاحب التعارض عمله بنفسه. لم يُعتمد ضمان لزمن الرد.')}
 ],['/about/governance','/programs/program-lifecycle']),
 guide('work-with-us','transition',t('From proof to operation','من الإثبات إلى التشغيل'),t('Plan for the institution that will use the capability from the beginning.','خطط منذ البداية للمؤسسة التي ستستخدم القدرة.'),[
 {title:t('Before handover','قبل التسليم'),items:[t('Name the operating owner and the person authorized to accept the result.','سمِّ مسؤول التشغيل والشخص المخول بقبول النتيجة.'),t('Agree the operating envelope, performance measures and known limitations.','اتفق على حدود التشغيل ومقاييس الأداء والقيود المعروفة.'),t('Document training, maintenance, costs, access rights and support responsibilities.','وثق التدريب والصيانة والتكاليف والصلاحيات ومسؤوليات الدعم.'),t('Test fallback, incident response and continuity when a key person is absent.','اختبر البديل والاستجابة للحوادث والاستمرار عند غياب شخص أساسي.')]},
 {title:t('Acceptance and learning','القبول والتعلم'),body:t('A demonstration is not acceptance. The operator reviews evidence in the intended context and records a decision. After acceptance, the capability enters an agreed measurement and improvement cycle.','العرض التجريبي ليس قبولًا. يراجع المشغّل الأدلة في السياق المستهدف ويسجل قراره. بعد القبول تدخل القدرة دورة قياس وتطوير متفقًا عليها.')}
 ],['/workshops/operating-owner','/method#operate']),
 guide('programs','program-lifecycle',t('How a program works','كيف يعمل البرنامج؟'),t('A bounded mission with evidence, ownership and a route to use.','مهمة محددة لها أدلة ومسؤول ومسار إلى الاستخدام.'),[
 {title:t('From idea to program','من الفكرة إلى البرنامج'),items:[t('Explore: gather signals and understand the unmet capability.','استكشاف: جمع الإشارات وفهم القدرة غير المتحققة.'),t('Incubate: challenge assumptions with users and specialists.','إنضاج: نقد الافتراضات مع المستفيدين والمتخصصين.'),t('Authorize: approve the owner, baseline, scope, resources and tests.','اعتماد: إقرار المسؤول وخط الأساس والنطاق والموارد والاختبارات.'),t('Execute: work in phases with evidence reviews.','تنفيذ: العمل على مراحل تتخللها مراجعات أدلة.'),t('Transition or close: transfer a usable capability, or preserve what was learned.','نقل أو إغلاق: تسليم قدرة قابلة للاستخدام أو حفظ ما تعلمناه.')]},
 {title:t('The program record','ملف البرنامج'),body:t('Keep one versioned record of the capability, accountable owner, team, milestones, evidence, decisions, budget assumptions, risks and intended acceptor. An unresolved critical dependency should be visible, not hidden by progress reporting.','احتفظ بملف ذي نسخ للقدرة والمسؤول والفريق والمراحل والأدلة والقرارات وافتراضات الميزانية والمخاطر وجهة القبول. يجب إظهار الاعتماديات الحرجة غير المحسومة، لا إخفاؤها بتقارير النشاط.')}
 ],['/about/program-questions','/work-with-us/transition']),
 guide('programs','ideas',t('Ideas under exploration','أفكار قيد الاستكشاف'),t('Questions worth investigating before committing to a program.','أسئلة تستحق البحث قبل الالتزام ببرنامج.'),[
 {title:t('The incubation record','ملف إنضاج الفكرة'),body:t('An idea begins with a capability question, an initial evidence map and the people who could challenge it. The next step should remove an important uncertainty. An idea becomes a program only after ownership, a test and resources are authorized.','تبدأ الفكرة بسؤال قدرة وخريطة أدلة أولية وأشخاص يستطيعون نقدها. تزيل الخطوة التالية وجهًا مهمًا لعدم اليقين. لا تصبح الفكرة برنامجًا إلا بعد اعتماد المسؤول والاختبار والموارد.')},
 {title:t('Questions currently proposed for exploration','أسئلة مقترحة للاستكشاف'),items:[t('Can an institution operate a bounded AI workflow with traceable evidence?','هل تستطيع مؤسسة تشغيل مسار ذكاء اصطناعي محدود بأدلة قابلة للتتبع؟'),t('Can an existing industrial capability solve a task in a new market?','هل تحل قدرة صناعية موجودة مهمة في سوق جديد؟'),t('Which first capability makes a larger compute or materials ambition credible?','ما القدرة الأولى التي تجعل طموح الحوسبة أو المواد الأكبر قابلًا للتصديق؟')]}
 ],['/programs/institutional-ai','/programs/trusted-sourcing','/programs/compute-capability']),
 guide('programs','challenges',t('Challenges & proof sprints','التحديات وتجارب الإثبات'),t('Create a fair test around a hard, clearly defined capability.','صمم اختبارًا عادلًا لقدرة صعبة ومحددة بوضوح.'),[
 {title:t('A proposed challenge format','صيغة تحدٍ مقترحة'),items:[t('One task, a clear baseline and a shared evaluation environment.','مهمة واحدة وخط أساس واضح وبيئة تقييم مشتركة.'),t('Published success measures and known operating limits.','مقاييس نجاح معلنة وحدود تشغيل معروفة.'),t('Independent review and evidence that can be checked.','مراجعة مستقلة وأدلة يمكن فحصها.'),t('A plan for what a successful result would enable next.','خطة لما تتيحه النتيجة الناجحة لاحقًا.')]},
 {title:t('Initial proof sprint','تجربة إثبات أولى'),body:t('Suggested exercise: compare two approaches to preparing a sourced institutional decision brief on the same non-sensitive cases. Measure time, evidence traceability and reviewer corrections. This is a proposed exercise, not an announced competition or prize.','تمرين مقترح: مقارنة مسارين لإعداد مذكرة قرار مؤسسي مسندة على الحالات غير الحساسة نفسها. نقيس الزمن وقابلية تتبع الأدلة وتصحيحات المراجع. هذا تمرين مقترح وليس مسابقة أو جائزة معلنة.')}
 ],['/workshops/design-the-proof','/programs/institutional-ai']),
 guide('programs','spotlights',t('Research spotlights','تحت المجهر'),t('Look closely at the connection between a technical advance and an institutional capability.','افحص العلاقة بين تقدم تقني وقدرة مؤسسية.'),[
 {title:t('Beyond the demonstration','ما وراء النموذج التجريبي'),body:t('The spotlight format asks what has been demonstrated, under which conditions, what remains uncertain and who could use the capability. Read the existing Physical AI report and the proposed industrial autonomy program together to distinguish a research signal from an operating claim.','يسأل هذا القسم عمّا جرى إثباته وفي أي ظروف، وما بقي مجهولًا، ومَن يستطيع استخدام القدرة. اقرأ تقرير الذكاء الاصطناعي المادي الموجود وتصور برنامج الاستقلالية الصناعية معًا للفصل بين الإشارة البحثية والادعاء التشغيلي.')}
 ],['/insights/physical-ai','/programs/industrial-autonomy','/news/learning-from-challenges'],'industry'),
 guide('workshops','how-workshops-work',t('How the weekly workshops work','كيف تعمل الورش الأسبوعية؟'),t('A recurring working rhythm that produces evidence and decisions.','إيقاع عمل متكرر ينتج أدلة وقرارات.'),[
 {title:t('A six-week cycle','دورة من ستة أسابيع'),body:t('The proposed cadence is one 90-minute workshop each week: frame the capability, map the limit, assemble the best available, design proof, plan operation, and review learning. Dates, hosts and delivery format are announced only after confirmation.','الإيقاع المقترح ورشة واحدة مدتها 90 دقيقة كل أسبوع: صياغة القدرة، ورسم الحد، وتجميع أفضل المتاح، وتصميم الإثبات، والتخطيط للتشغيل، ثم مراجعة التعلم. تُعلن المواعيد والميسّر وطريقة الانعقاد بعد التأكيد.')},
 {title:t('Every session leaves an artifact','كل جلسة تنتج مخرجًا'),items:[t('A defined question and preparation task before the meeting.','سؤال محدد ومهمة تحضير قبل الاجتماع.'),t('A facilitator, recorder and relevant expert roles.','أدوار ميسّر وموثّق وخبير مناسب.'),t('A usable brief, map, test card or decision record.','Brief أو خريطة أو بطاقة اختبار أو سجل قرار قابل للاستخدام.'),t('A next action with an owner and a due date agreed in the session.','فعل تالٍ له مسؤول وموعد متفق عليه داخل الجلسة.')]},
 {title:t('Interest is not registration','الاهتمام ليس تسجيلًا مؤكدًا'),body:t('You can prepare an email expressing interest in a session. Attendance is confirmed separately when a date and host are assigned. No seat is reserved by clicking the website button.','يمكنك تجهيز بريد لإبداء الاهتمام بجلسة. يُؤكد الحضور بصورة منفصلة عند تحديد الموعد والميسّر. الضغط على زر الموقع لا يحجز مقعدًا.')}
 ],['/workshops/capability-question','/workshops/rewinds']),
 guide('workshops','rewinds',t('Workshop notes & outcomes','سجلات الورش ومخرجاتها'),t('A place for the evidence created by completed sessions.','مكان للأدلة التي تنتجها الجلسات المنعقدة.'),[
 {title:t('Before the first session','قبل الجلسة الأولى'),body:t('No completed workshop is published yet. The six session pages contain preparation guides and intended outputs that can already be used to plan a cycle.','لم يُنشر سجل ورشة منعقدة بعد. تتضمن صفحات الجلسات الست أدلة التحضير والمخرجات المستهدفة التي يمكن استخدامها الآن للتخطيط لدورة.')},
 {title:t('The record we will publish','السجل المطلوب نشره'),items:[t('The question, date and confirmed contributors.','السؤال والموعد والمساهمون المؤكدون.'),t('Approved non-confidential outputs and source references.','المخرجات غير السرية المعتمدة ومراجع المصادر.'),t('Decisions, unresolved questions and the next working step.','القرارات والأسئلة غير المحسومة والخطوة التنفيذية التالية.') ]}
 ],['/workshops','/workshops/review-and-evolve']),
 guide('about','operating-model',t('Our operating model','نموذج تشغيلنا'),t('A proposed institution organized around capabilities and accountable programs.','مؤسسة مقترحة التنظيم حول القدرات والبرامج واضحة المسؤولية.'),[
 {title:t('Four connected layers','أربع طبقات مترابطة'),items:[t('Strategy chooses the important capability and the reason to pursue it.','الاستراتيجية تختار القدرة المهمة وسبب العمل عليها.'),t('Specialists contribute domain knowledge and independent review.','يساهم المتخصصون بمعرفة المجال والمراجعة المستقلة.'),t('Program managers own the path, team, tests and evidence.','مديرو البرامج مسؤولون عن المسار والفريق والاختبارات والأدلة.'),t('Operating partners accept and sustain capabilities in the real world.','شركاء التشغيل يقبلون القدرات ويحافظون عليها في الواقع.')]},
 {title:t('What happens each week','ماذا يحدث كل أسبوع؟'),body:t('Review the evidence and blockers for each authorized mission. Run a focused workshop or experiment. Update the program record, obtain required decisions and assign the next measurable step. Reconsider whether the mission remains worth pursuing.','تُراجع الأدلة والعوائق لكل مهمة معتمدة. تُنفذ ورشة مركزة أو تجربة. يُحدّث ملف البرنامج وتُطلب القرارات اللازمة وتُعيّن الخطوة التالية القابلة للقياس. ويُعاد النظر في استحقاق المهمة للاستمرار.')},
 {title:t('Continuity without the founder','الاستمرار دون حضور المؤسس'),body:t('Each authorized program needs a responsible owner, an approval substitute, a current evidence record and a documented refusal or escalation path. These assignments must be real before independent operation is claimed.','يحتاج كل برنامج معتمد إلى مسؤول وبديل للاعتماد وسجل أدلة محدث ومسار رفض أو تصعيد موثق. يجب تثبيت هذه الأدوار فعليًا قبل الادعاء بالتشغيل المستقل.')}
 ],['/programs/program-lifecycle','/about/governance']),
 guide('about','governance',t('Evidence, governance & decision rights','الأدلة والحوكمة وحقوق القرار'),t('Make ownership and authority as explicit as the technical ambition.','اجعل المسؤولية والصلاحية واضحتين مثل الطموح التقني.'),[
 {title:t('Roles that must be named','أدوار يجب تسميتها'),items:[t('Owner: accountable for the capability and its value.','المالك: مسؤول عن القدرة وقيمتها.'),t('Executor: performs the scoped work and records the evidence.','المنفذ: يؤدي العمل المحدد ويوثق الأدلة.'),t('Reviewer: challenges the evidence and declares conflicts.','المراجع: ينقد الأدلة ويعلن التعارضات.'),t('Approver: authorizes a defined decision within explicit limits.','المعتمد: يجيز قرارًا محددًا ضمن حدود صريحة.'),t('Acceptor and operator: accept the result and sustain real use.','جهة القبول والمشغّل: يقبلان النتيجة ويحافظان على استخدامها الفعلي.')]},
 {title:t('Evidence labels','حالات الأدلة'),items:[t('Verified: independently checked against an identified source.','مثبت: فُحص بصورة مستقلة مقابل مصدر محدد.'),t('Confirmed by the responsible party: stated by an accountable person.','مؤكد من المسؤول: صرّح به شخص مسؤول.'),t('Hypothesis: a proposition to be tested.','فرضية: طرح يحتاج اختبارًا.'),t('Unknown: evidence is missing or conflicting.','مجهول: الأدلة ناقصة أو متعارضة.')]},
 {title:t('Human decision points','قرارات بشرية'),body:t('Financial commitments, hiring, policy exceptions, specialist judgments and public claims require a named human authority. An AI recommendation is not an approval. Proposed responsibilities are activated only when assigned and accepted.','الالتزامات المالية والتوظيف واستثناءات السياسات والأحكام المتخصصة والادعاءات العامة تحتاج صاحب صلاحية بشريًا محددًا. توصية الذكاء الاصطناعي ليست اعتمادًا. تُفعّل المسؤوليات المقترحة بعد تعيينها وقبولها.')}
 ],['/work-with-us/review-and-selection','/about/operating-model']),
 guide('about','program-questions',t('Questions before a program','أسئلة تسبق البرنامج'),t('Make the ambition understandable and the proof assessable.','اجعل الطموح مفهومًا والإثبات قابلًا للتقييم.'),[
 {title:t('The core questions','الأسئلة الأساسية'),items:[t('What should someone become able to do, and why does it matter?','ما الذي يجب أن يصبح شخص أو مؤسسة قادرًا عليه، ولماذا يهم؟'),t('What happens today, and where is the actual limit?','ماذا يحدث اليوم، وأين الحد الحقيقي؟'),t('What change in approach could overcome that limit?','ما التغيير في المسار الذي قد يتجاوز الحد؟'),t('What evidence, risks, resources and time does the attempt involve?','ما أدلة المحاولة ومخاطرها ومواردها ووقتها؟'),t('Which intermediate and final tests would justify the next decision?','ما الاختبارات المرحلية والنهائية التي تبرر القرار التالي؟')]},
 {title:t('The VisionSeek extension','إضافة VisionSeek'),items:[t('Who are the best people to assemble around the capability?','مَن أفضل الأشخاص الذين ينبغي جمعهم حول القدرة؟'),t('What is the best usable knowledge, technology and opportunity already available?','ما أفضل معرفة وتقنية وفرصة متاحة يمكن توظيفها؟'),t('Who will own and operate the capability after proof?','مَن سيمتلك مسؤولية القدرة ويشغّلها بعد الإثبات؟'),t('How will operating evidence change the next iteration?','كيف ستغيّر أدلة التشغيل دورة التطوير التالية؟')]},
 {title:t('Learning reference','مرجع التعلم'),body:t('DARPA publishes the Heilmeier Catechism as a way to assess proposed research programs. The questions above are a VisionSeek adaptation, not a claim of affiliation or a replacement for its nine-stage method.','تنشر DARPA أسئلة Heilmeier لتقييم البرامج البحثية المقترحة. الأسئلة هنا تكييف لـVisionSeek، وليست ادعاء ارتباط مؤسسي أو بديلًا عن منهجها ذي المراحل التسع.')}
 ],['/method','/work-with-us/prepare-a-concept']),
 guide('about','people',t('People & leadership','الأشخاص والقيادة'),t('A founder-led vision and a team assembled around each capability.','رؤية يقودها المؤسس وفريق يُجمع حول كل قدرة.'),[
 {title:t('Dr. Ahmed Abdelalim','د. أحمد عبدالعليم'),body:t('Founder of VisionSeek; responsible for vision and strategy. Based in Incheon, South Korea.','مؤسس VisionSeek ومسؤول الرؤية والاستراتيجية. مقيم في إنتشون بكوريا الجنوبية.')},
 {title:t('Program leadership','قيادة البرامج'),body:t('Program-manager appointments are not yet published. The operating model describes proposed responsibilities, not appointed staff.','لم تُنشر تعيينات مديري البرامج. يشرح نموذج التشغيل المسؤوليات المقترحة، ولا يمثل موظفين معينين.')}
 ],['/about#founder']),
 guide('about','learning-from-darpa',t('Learning from DARPA','التعلم من DARPA'),t('Use established institutional knowledge to improve how we build capabilities.','توظيف معرفة مؤسسية متراكمة لتحسين طريقة بناء القدرات.'),[
 {title:t('What we learn','ما الذي نتعلمه؟'),items:[t('Frame ambitious work as a program with a clear question and evidence.','صياغة العمل الطموح كبرنامج له سؤال واضح وأدلة.'),t('Give a program manager responsibility for the mission and its milestones.','إسناد مسؤولية المهمة ومراحلها إلى مدير برنامج.'),t('Connect specialists, institutions and an eventual operating context.','ربط المتخصصين والمؤسسات وسياق التشغيل المستقبلي.') ]},
 {title:t('What VisionSeek adds','ما الذي تضيفه VisionSeek؟'),body:t('Our scope is institutional capability building. Highest Level One explicitly searches for the best people, knowledge, technologies and opportunities already available. The resulting form may be a system, platform, partnership, program or new venture.','نطاقنا هو بناء القدرات المؤسسية. يبحث Highest Level One صراحة عن أفضل الأشخاص والمعرفة والتقنيات والفرص المتاحة. وقد يكون الشكل الناتج منظومة أو منصة أو شراكة أو برنامجًا أو مشروعًا جديدًا.')},
 {title:t('Proportionate adoption','تبنٍ يناسب المرحلة'),body:t('A public framework can inform a small team, but a website does not create staff, funding or delivery history. Proposed programs become operational only through named people, approved resources and tested routines.','يمكن لإطار منشور أن يفيد فريقًا صغيرًا، لكن الموقع لا ينشئ موظفين أو تمويلًا أو سجل إنجاز. تتحول البرامج المقترحة إلى تشغيل بأشخاص محددين وموارد معتمدة وإجراءات مجرّبة.')}
 ],['/about/operating-model','/about/program-questions','/news/program-manager-model']),
 guide('news','media',t('Media & inquiries','الإعلام والاستفسارات'),t('Find the public identity, contact route and publication approach.','تعرّف على الهوية العامة والتواصل ومنهج النشر.'),[
 {title:t('About VisionSeek','عن VisionSeek'),body:t('VisionSeek builds new capabilities for institutions and governments by connecting people, technology, knowledge, systems, partners and opportunities. Founder: Dr. Ahmed Abdelalim. Location: Incheon, South Korea.','تبني VisionSeek قدرات جديدة للمؤسسات والحكومات عبر ربط الأشخاص والتكنولوجيا والمعرفة والأنظمة والشركاء والفرص. المؤسس: د. أحمد عبدالعليم. الموقع: إنتشون، كوريا الجنوبية.')},
 {title:t('Publication standards','معايير النشر'),body:t('Editorial perspectives are distinguished from external source reports and completed results. A proposed program is labelled as proposed. Named partnerships and delivery claims require approval and supporting evidence.','تُفصل الرؤى التحريرية عن تقارير المصادر الخارجية والنتائج المنجزة. يُسمى البرنامج المقترح مقترحًا. تتطلب الشراكات المسماة وادعاءات الإنجاز اعتمادًا وأدلة داعمة.')},
 {title:t('Contact','تواصل'),body:t('For media, speaking or institutional inquiries: abdelalim@visionseek.org.','للاستفسارات الإعلامية أو طلب متحدث أو التواصل المؤسسي: abdelalim@visionseek.org.')}
 ],['/about','/about/people','/about/governance'])
];
for(const c of communities){guideEntries.push(guide('work-with-us',c.id,t(c.en,c.ar),t(c.textEn,c.textAr),[{title:t('Where we can begin','من أين نبدأ؟'),body:t(c.detailEn,c.detailAr)},{title:t('A useful contribution','مساهمة مفيدة'),items:[t('Define the capability or expertise you want to bring.','حدد القدرة أو الخبرة التي تريد تقديمها.'),t('Share relevant, verifiable evidence and the conditions for collaboration.','شارك أدلة مرتبطة قابلة للتحقق وشروط التعاون.'),t('Choose a bounded next step with a responsible owner.','اختر خطوة تالية محددة لها مسؤول واضح.')]}],['/programs','/opportunities','/work-with-us/prepare-a-concept']));}
const questions=guideEntries.find(e=>e.slug==='program-questions');if(questions) questions.source={title:'DARPA · The Heilmeier Catechism',url:'https://www.darpa.mil/about/heilmeier-catechism'};
const learning=guideEntries.find(e=>e.slug==='learning-from-darpa');if(learning) learning.source={title:'DARPA · Programs',url:'https://www.darpa.mil/research/programs'};
