import {t,type Entry,type Section} from './schema';
import {programEntries,opportunityEntries} from './programs';
import {officeEntries,careerEntries} from './organization';
import {workshopEntries} from './workshops';
import {guideEntries} from './guides';
import {newsEntries} from './news';
export * from './schema';
export const entries:Entry[]=[...programEntries,...opportunityEntries,...officeEntries,...careerEntries,...workshopEntries,...guideEntries,...newsEntries];
const link=(href:string,en:string,ar:string)=>({href,label:t(en,ar)});
export const sections:Section[]=[
 {id:'work-with-us',title:t('Work with Us','اعمل معنا'),eyebrow:t('CONNECT · CONTRIBUTE · BUILD','تواصل · ساهم · ابنِ'),intro:t('Bring an important need, a deep expertise or a capability the world should use. Find your path into a mission.','قدّم احتياجًا مهمًا أو خبرة عميقة أو قدرة تستحق الاستخدام. اكتشف مسارك للمشاركة في مهمة.'),image:'industry',links:[link('/work-with-us/new-to-visionseek','New to VisionSeek','ابدأ مع VisionSeek'),link('/work-with-us/how-to-respond','How to respond','كيف تشارك؟'),link('/work-with-us/prepare-a-concept','Prepare a concept','جهّز تصورًا'),link('/work-with-us/review-and-selection','Review & selection','المراجعة والاختيار'),link('/work-with-us/transition','Transition to use','النقل للتشغيل')]},
 {id:'opportunities',title:t('R&D Opportunities','فرص البحث والتطوير'),eyebrow:t('BRING THE CAPABILITY CLOSER','قرّب القدرة من الواقع'),intro:t('Find a question where your research, expertise, technology or operating context could make a difference.','اكتشف سؤالًا يمكن لبحثك أو خبرتك أو تقنيتك أو سياق التشغيل لديك أن يساهم في حله.'),image:'chips',notice:t('Exploratory expressions of interest. No funded calls, awards or deadlines are announced.','مسارات لإبداء الاهتمام الاستكشافي. لا توجد دعوات ممولة أو جوائز أو مواعيد نهائية معلنة.'),links:[link('/opportunities','All opportunities','كل الفرص'),link('/work-with-us/how-to-respond','How to respond','كيف تشارك؟'),link('/work-with-us/review-and-selection','Review process','مسار المراجعة'),link('/work-with-us/prepare-a-concept','Prepare your note','جهّز مذكرتك')]},
 {id:'programs',title:t('Programs','البرامج'),eyebrow:t('MISSIONS THAT EXPAND POSSIBILITY','مهام توسّع الممكن'),intro:t('From an important capability question to a bounded program with people, tests and a route to operation.','من سؤال قدرة مهم إلى برنامج محدد بأشخاص واختبارات ومسار إلى التشغيل.'),image:'space',notice:t('The six program concepts are proposed for exploration. They are not launched or funded programs.','تصورات البرامج الستة مقترحة للاستكشاف، وليست برامج أُطلقت أو اعتُمد تمويلها.'),links:[link('/programs','All programs','كل البرامج'),link('/programs/ideas','Ideas under exploration','أفكار قيد الاستكشاف'),link('/programs/challenges','Challenges','التحديات'),link('/programs/spotlights','Research spotlights','تحت المجهر'),link('/programs/program-lifecycle','How programs work','كيف تعمل البرامج؟')]},
 {id:'offices',title:t('Offices','المكاتب'),eyebrow:t('ORGANIZE AROUND THE MISSION','تنظيم حول المهمة'),intro:t('Technical, strategic and supporting mandates for an institution that builds capabilities across disciplines.','اختصاصات تقنية واستراتيجية ومساندة لمؤسسة تبني قدرات تتجاوز حدود التخصصات.'),image:'cities',notice:t('A proposed functional structure. Office leads and teams are not yet appointed.','هيكل وظيفي مقترح. لم تُعيّن قيادات المكاتب وفرقها بعد.'),links:[link('/offices','All offices','كل المكاتب'),link('/offices/strategy-and-governance','Strategy & governance','الاستراتيجية والحوكمة'),link('/offices/program-support','Program support','دعم البرامج'),link('/about/operating-model','Operating model','نموذج التشغيل')]},
 {id:'news',title:t('News','الأخبار'),eyebrow:t('IDEAS · RESEARCH · INSTITUTIONAL LEARNING','أفكار · بحث · تعلم مؤسسي'),intro:t('VisionSeek perspectives and attributed research references on building what should become possible.','رؤى VisionSeek ومراجع بحثية منسوبة إلى مصادرها حول بناء ما ينبغي أن يصبح ممكنًا.'),image:'science',links:[link('/news','All news & notes','كل الأخبار والمقالات'),link('/news/media','Media & inquiries','الإعلام والاستفسارات'),link('/insights','Leaders House','بيت القادة'),link('/programs/spotlights','Research spotlights','تحت المجهر')]},
 {id:'workshops',title:t('Workshops','ورش العمل'),eyebrow:t('ONE WEEK. ONE QUESTION. ONE USEFUL OUTPUT.','كل أسبوع. سؤال محدد. مخرج مفيد.'),intro:t('A weekly working rhythm to frame capabilities, assemble knowledge, design proof and learn from reality.','إيقاع عمل أسبوعي لصياغة القدرات وتجميع المعرفة وتصميم الإثبات والتعلم من الواقع.'),image:'industry',notice:t('Six planned workshop formats. Dates, hosts and attendance are confirmed separately.','ست صيغ لورش مخططة. تُؤكد المواعيد والميسّرون والحضور بصورة منفصلة.'),links:[link('/workshops','The weekly cycle','الدورة الأسبوعية'),link('/workshops/how-workshops-work','How it works','كيف تعمل الورش؟'),link('/workshops/rewinds','Notes & outcomes','السجلات والمخرجات')]},
 {id:'careers',title:t('Careers','المسارات المهنية'),eyebrow:t('BRING WHAT ONLY YOU CAN','قدّم ما تتميز به'),intro:t('Explore the roles that turn a mission into a capability: program leaders, researchers, builders, reviewers and operators.','استكشف الأدوار التي تحول المهمة إلى قدرة: قادة برامج وباحثون ومنفذون ومراجعون ومسؤولو تشغيل.'),image:'chips',notice:t('Role profiles and expressions of interest. No specific vacancy or employment offer is announced.','ملفات أدوار وإبداء اهتمام. لا توجد وظيفة محددة أو عروض توظيف معلنة.'),links:[link('/careers','Where you fit','أين تناسبك المشاركة؟'),link('/careers/program-manager','Program manager','مدير البرنامج'),link('/careers/fellows','Fellows','الزمالات'),link('/about/people','People & leadership','الأشخاص والقيادة')]},
 {id:'about',title:t('About','عن VisionSeek'),eyebrow:t('SEE WHAT COULD BE. MAKE IT POSSIBLE.','نرى ما يمكن أن يكون. ونجعله ممكنًا.'),intro:t('The vision, people and operating principles behind VisionSeek.','الرؤية والأشخاص ومبادئ التشغيل وراء VisionSeek.'),image:'space',links:[link('/about','Our vision','رؤيتنا'),link('/method','Our method','منهجنا'),link('/about/operating-model','Operating model','نموذج التشغيل'),link('/about/program-questions','Program questions','أسئلة البرنامج'),link('/about/people','People','الأشخاص'),link('/about/governance','Governance','الحوكمة'),link('/about/learning-from-darpa','Learning from DARPA','التعلم من DARPA')]}
];
export const getSection=(id:string)=>sections.find(s=>s.id===id);
export const getEntry=(section:string,slug:string)=>entries.find(e=>e.section===section&&e.slug===slug);
export const entryPath=(e:Entry)=>`/${e.section}/${e.slug}`;
export const titleForPath=(path:string,locale:'en'|'ar')=>{
 const [section,slug]=path.split('/').filter(Boolean);
 if(!slug)return getSection(section)?.title[locale]??({'method':locale==='ar'?'منهجنا':'Our method','insights':locale==='ar'?'بيت القادة':'Leaders House'} as Record<string,string>)[section]??section;
 return getEntry(section,slug)?.title[locale]??(path.includes('physical-ai')?(locale==='ar'?'تقرير الذكاء الاصطناعي المادي':'Physical AI report'):locale==='ar'?'اكتشف المزيد':'Explore more');
};
