export const institutionNav = [
 {path:'/work-with-us',en:'Work with Us',ar:'اعمل معنا',children:[['/work-with-us/new-to-visionseek','New to VisionSeek','ابدأ مع VisionSeek'],['/work-with-us/how-to-respond','How to respond','كيف تشارك؟'],['/work-with-us/prepare-a-concept','Prepare a concept','جهّز تصورًا'],['/work-with-us/review-and-selection','Review & selection','المراجعة والاختيار'],['/work-with-us/transition','Transition to use','النقل للتشغيل']]},
 {path:'/opportunities',en:'R&D Opportunities',ar:'فرص البحث والتطوير',children:[['/opportunities','Explore opportunities','استكشف الفرص'],['/work-with-us/how-to-respond','Response guide','دليل المشاركة'],['/work-with-us/prepare-a-concept','Prepare your note','جهّز مذكرتك']]},
 {path:'/programs',en:'Programs',ar:'البرامج',children:[['/programs','Program concepts','تصورات البرامج'],['/programs/ideas','Ideas under exploration','أفكار قيد الاستكشاف'],['/programs/challenges','Challenges','التحديات'],['/programs/spotlights','Research spotlights','تحت المجهر'],['/programs/program-lifecycle','How programs work','كيف تعمل البرامج؟']]},
 {path:'/offices',en:'Offices',ar:'المكاتب',children:[['/offices','Technical offices','المكاتب التقنية'],['/offices/strategy-and-governance','Strategy & governance','الاستراتيجية والحوكمة'],['/offices/program-support','Program support','دعم البرامج'],['/about/operating-model','Operating model','نموذج التشغيل']]},
 {path:'/news',en:'News',ar:'الأخبار',children:[['/news','All news & notes','كل الأخبار والمقالات'],['/insights','Leaders House','بيت القادة'],['/news/media','Media & inquiries','الإعلام والاستفسارات']]},
 {path:'/workshops',en:'Workshops',ar:'ورش العمل',children:[['/workshops','Weekly workshops','الورش الأسبوعية'],['/workshops/how-workshops-work','How it works','كيف تعمل الورش؟'],['/workshops/rewinds','Notes & outcomes','السجلات والمخرجات']]},
 {path:'/careers',en:'Careers',ar:'المسارات المهنية',children:[['/careers','Where you fit','أين تناسبك المشاركة؟'],['/careers/program-manager','Program manager','مدير البرنامج'],['/careers/research-engineer','Research & engineering','البحث والهندسة'],['/careers/fellows','Fellows','الزمالات']]},
 {path:'/about',en:'About',ar:'عن VisionSeek',children:[['/about','Our vision','رؤيتنا'],['/method','Our method','منهجنا'],['/about/operating-model','Operating model','نموذج التشغيل'],['/about/program-questions','Program questions','أسئلة البرنامج'],['/about/people','People','الأشخاص'],['/about/governance','Governance','الحوكمة'],['/about/learning-from-darpa','Learning from DARPA','التعلم من DARPA']]},
];
