import {t, type Entry, type Text} from './schema';

type Concept={slug:string;code:string;title:Text;summary:Text;image:string;beneficiary:Text;constraint:Text;hypothesis:Text;test:Text;stop:Text;transfer:Text};
export const concepts:Concept[]=[
 {slug:'institutional-ai',code:'VS-P01',title:t('Institutional AI that can be trusted','ذكاء اصطناعي مؤسسي يمكن الاعتماد عليه'),summary:t('Enable an institutional team to turn approved information into evidence-backed decisions and accountable actions.','تمكين فريق مؤسسي من تحويل معلومات معتمدة إلى قرارات مسندة وأفعال لها مسؤول واضح.'),image:'cities',beneficiary:t('Operations and decision teams in institutions.','فرق التشغيل واتخاذ القرار داخل المؤسسات.'),constraint:t('Knowledge is scattered; evidence and decision rights get lost between tools.','المعرفة متفرقة، وتضيع الأدلة وصلاحيات القرار بين الأدوات.'),hypothesis:t('A bounded AI workflow with explicit sources and human checkpoints can reduce decision preparation time without reducing evidence quality.','يمكن لمسار ذكاء اصطناعي محدود النطاق، بمصادر واضحة ونقاط اعتماد بشرية، تقليل زمن إعداد القرار دون خفض جودة الأدلة.'),test:t('Proposed test: compare 30 non-sensitive cases against the current process. Measure preparation time, unsupported claims, reviewer corrections and unauthorized actions. Targets are agreed before testing.','اختبار مقترح: مقارنة 30 حالة غير حساسة بالعملية الحالية، وقياس زمن الإعداد والادعاءات بلا سند وتصحيحات المراجع والأفعال غير المصرح بها. تُعتمد الأهداف قبل الاختبار.'),stop:t('Stop if the system cannot trace a material claim to evidence or performs an action outside its permission boundary.','إيقاف المسار إذا تعذر إسناد ادعاء مؤثر إلى دليل أو نُفذ فعل خارج حدود الصلاحيات.'),transfer:t('A named process owner accepts the workflow, permission matrix, evaluation set and manual fallback before live use.','يتسلم مسؤول العملية المسار ومصفوفة الصلاحيات ومجموعة التقييم والبديل اليدوي قبل الاستخدام الفعلي.')},
 {slug:'industrial-autonomy',code:'VS-P02',title:t('Autonomy for real industrial work','الاستقلالية في العمل الصناعي الحقيقي'),summary:t('Make one repetitive inspection task reliably executable by a supervised robotic or computer-vision system.','جعل مهمة فحص متكررة قابلة للتنفيذ الموثوق بنظام روبوتي أو رؤية حاسوبية تحت الإشراف.'),image:'industry',beneficiary:t('Factories, inspection teams and industrial operators.','المصانع وفرق الفحص ومشغلو المنشآت الصناعية.'),constraint:t('Demonstrations often fail when lighting, objects, procedures or working conditions change.','قد تتعطل النماذج التجريبية مع تغير الإضاءة أو الأجسام أو الإجراءات أو ظروف العمل.'),hypothesis:t('A narrowly defined task, explicit operating envelope and operator intervention can turn available components into a useful inspection capability.','يمكن لمهمة محددة وحدود تشغيل واضحة وتدخل مشغّل أن تحول مكونات متاحة إلى قدرة فحص مفيدة.'),test:t('Proposed test: representative normal and difficult cases in a controlled environment. Measure missed defects, false alarms, cycle time and human interventions against the agreed baseline.','اختبار مقترح: حالات طبيعية وصعبة ممثلة للواقع في بيئة مضبوطة. نقيس العيوب الفائتة والإنذارات الخاطئة وزمن الدورة وتدخل الإنسان مقارنة بخط الأساس المعتمد.'),stop:t('Stop for unsafe behavior, unbounded failure modes or inability to meet the operator’s acceptance criteria.','إيقاف المسار عند سلوك غير آمن أو أعطال غير مفهومة أو العجز عن تحقيق معايير قبول المشغّل.'),transfer:t('The industrial operator approves the safety case, maintenance requirements, training and fallback process.','يعتمد المشغّل الصناعي ملف السلامة ومتطلبات الصيانة والتدريب وخطة الرجوع.')},
 {slug:'trusted-sourcing',code:'VS-P03',title:t('Evidence-led cross-border sourcing','توريد عابر للحدود تقوده الأدلة'),summary:t('Help a buyer determine whether a sourcing path is eligible, verifiable and worth pursuing before committing resources.','مساعدة المشتري على تحديد أهلية مسار التوريد وقابليته للتحقق وجدواه قبل الالتزام بالموارد.'),image:'drones',beneficiary:t('Institutional buyers and specialist sourcing teams.','المشترون المؤسسيون وفرق التوريد المتخصصة.'),constraint:t('A listing, an indicative price and a supplier claim are easily mistaken for available stock, a complete landed cost or proven suitability.','قد يُخلط بين الإعلان والمخزون المتاح، وبين السعر المبدئي والتكلفة الكاملة، وبين ادعاء المورد والملاءمة المثبتة.'),hypothesis:t('Eligibility-first research and structured evidence can eliminate unsuitable paths earlier and make quote comparison more reliable.','يمكن للبحث الذي يبدأ بالأهلية والأدلة المنظمة استبعاد المسارات غير المناسبة مبكرًا وتحسين مقارنة العروض.'),test:t('Proposed test: use synthetic or permissioned historical requests. Track evidence completeness, unresolved cost items, disqualified paths and review time. No live purchase is required.','اختبار مقترح: طلبات اصطناعية أو تاريخية مصرح بها. نقيس اكتمال الأدلة وعناصر التكلفة المجهولة والمسارات المستبعدة وزمن المراجعة، دون شراء فعلي.'),stop:t('Pause when eligibility, product identity, availability or a material cost remains unknown.','تعليق المسار عندما تبقى الأهلية أو هوية المنتج أو التوافر أو تكلفة مؤثرة مجهولة.'),transfer:t('A sourcing owner accepts the evidence checklist, named pricing points and specialist review requirements.','يعتمد مسؤول التوريد قائمة الأدلة ونقاط التسعير المسماة ومتطلبات المراجعة المتخصصة.')},
 {slug:'resource-resilience',code:'VS-P04',title:t('Resilient resource operations','تشغيل مرن للموارد'),summary:t('Give an operator a testable way to detect and reduce avoidable energy or water loss in one bounded process.','تمكين مشغّل من اكتشاف وتقليل فاقد الطاقة أو المياه القابل للتجنب في عملية محددة.'),image:'energy',beneficiary:t('Infrastructure operators, campuses and production facilities.','مشغلو البنية التحتية والمجمعات والمنشآت الإنتاجية.'),constraint:t('Data exists in separate systems, while baselines and responsibility for interventions remain unclear.','توجد البيانات في أنظمة منفصلة، بينما يبقى خط الأساس ومسؤول التدخل غير واضحين.'),hypothesis:t('Combining existing metering, process knowledge and decision rules may reveal a practical intervention before new infrastructure is needed.','قد يكشف ربط القياس الموجود ومعرفة العملية وقواعد القرار عن تدخل عملي قبل الحاجة لبنية جديدة.'),test:t('Proposed test: establish a representative baseline, simulate interventions and measure normalized resource use, false alerts and operator response time.','اختبار مقترح: تأسيس خط أساس ممثل، ومحاكاة التدخلات، وقياس استهلاك الموارد بعد ضبط ظروف التشغيل والإنذارات الخاطئة وزمن استجابة المشغّل.'),stop:t('Do not advance where savings cannot be distinguished from changes in weather, occupancy or production volume.','لا نتقدم عندما يتعذر فصل أثر التدخل عن تغير الطقس أو الإشغال أو حجم الإنتاج.'),transfer:t('The asset owner accepts the measurement method, intervention permissions and ongoing verification plan.','يعتمد مالك الأصل منهج القياس وصلاحيات التدخل وخطة التحقق المستمر.')},
 {slug:'science-to-capability',code:'VS-P05',title:t('From scientific evidence to capability','من الدليل العلمي إلى القدرة'),summary:t('Help an applied-research team identify whether a promising finding can support a reproducible, useful capability.','مساعدة فريق بحث تطبيقي على تحديد ما إذا كان اكتشاف واعد يدعم قدرة نافعة قابلة لإعادة الإثبات.'),image:'science',beneficiary:t('Research institutions and translation teams.','المؤسسات البحثية وفرق تحويل البحث إلى تطبيق.'),constraint:t('A published finding does not by itself establish reproducibility, implementation feasibility or real-world value.','النتيجة المنشورة لا تثبت وحدها قابلية التكرار أو التنفيذ أو القيمة في الواقع.'),hypothesis:t('An evidence map and an independent replication plan can identify the most consequential uncertainties before scaling.','يمكن لخريطة أدلة وخطة إعادة إثبات مستقلة تحديد أهم أوجه عدم اليقين قبل التوسع.'),test:t('Proposed test: select a non-clinical research case, document the evidence hierarchy and define an independent reproducibility experiment with a qualified specialist.','اختبار مقترح: اختيار حالة بحثية غير سريرية، وتوثيق مراتب الأدلة، وتصميم تجربة لإعادة الإثبات بالتعاون مع متخصص مؤهل.'),stop:t('Pause for irreproducible findings, unavailable critical data or unresolved ethical and access requirements.','تعليق المسار عند تعذر إعادة الإثبات أو غياب بيانات حاسمة أو عدم حسم المتطلبات الأخلاقية وصلاحيات الوصول.'),transfer:t('An accountable research lead accepts the protocol, evidence record and limits of use.','يعتمد قائد بحث مسؤول البروتوكول وسجل الأدلة وحدود الاستخدام.')},
 {slug:'compute-capability',code:'VS-P06',title:t('Compute and industrial capability pathways','مسارات قدرات الحوسبة والصناعة'),summary:t('Identify a realistic first capability in chips, materials or compute infrastructure by connecting global expertise and local demand.','تحديد قدرة أولى واقعية في الرقائق أو المواد أو بنية الحوسبة عبر ربط الخبرات العالمية بالطلب المحلي.'),image:'chips',beneficiary:t('Industrial strategy teams and capability-building institutions.','فرق الاستراتيجية الصناعية ومؤسسات بناء القدرات.'),constraint:t('Large ambitions often skip the demand, skills, supply dependencies and economics needed for a credible first step.','قد تتجاوز الطموحات الكبيرة الطلب والمهارات واعتماديات التوريد والاقتصاديات اللازمة لخطوة أولى قابلة للتنفيذ.'),hypothesis:t('A focused capability map can reveal an achievable entry point in design, testing, packaging, materials or infrastructure.','قد تكشف خريطة مركّزة للقدرات عن نقطة دخول ممكنة في التصميم أو الاختبار أو التغليف أو المواد أو البنية التحتية.'),test:t('Proposed test: compare three candidate entry points using verified demand, expert review, supplier dependencies and a cost range supported by sources.','اختبار مقترح: مقارنة ثلاث نقاط دخول عبر طلب موثّق ومراجعة خبراء واعتماديات الموردين ونطاق تكلفة مسند بمصادر.'),stop:t('Reject paths without a credible user, accessible expertise or a viable first demonstration.','استبعاد المسارات التي لا تملك مستفيدًا واضحًا أو خبرة يمكن الوصول إليها أو تجربة أولى قابلة للتنفيذ.'),transfer:t('A sponsoring institution must accept the capability roadmap and resource assumptions before any investment program is proposed.','تتبنى جهة راعية خريطة القدرة وافتراضات الموارد قبل اقتراح أي برنامج استثماري.')},
];
export const programEntries:Entry[]=concepts.map(c=>({section:'programs',slug:c.slug,code:c.code,title:c.title,summary:c.summary,category:t('Program concepts','تصورات برامج'),status:t('Proposed · not launched','مقترح · لم يُطلق'),image:c.image,action:'concept',facts:[{label:t('Program owner','مسؤول البرنامج'),value:t('Program manager — appointment pending','مدير برنامج — لم يُعيّن')},{label:t('Funding','التمويل'),value:t('Not committed','غير معتمد')},{label:t('Schedule','الجدول الزمني'),value:t('Set after scope and baseline approval','يُحدد بعد اعتماد النطاق وخط الأساس')}],blocks:[
 {title:t('The capability and its beneficiary','القدرة والمستفيد'),body:c.beneficiary},
 {title:t('The current limit','الحد الحالي'),body:c.constraint},
 {title:t('The hypothesis to test','الفرضية المطلوب اختبارها'),body:c.hypothesis},
 {title:t('Stage gates','مراحل وقرارات البرنامج'),items:[t('Frame: confirm the user, baseline, access and intended capability.','تحديد: تثبيت المستفيد وخط الأساس وصلاحيات الوصول والقدرة المطلوبة.'),t('Prove: run the smallest meaningful test with pre-agreed measures.','إثبات: تنفيذ أصغر اختبار مفيد بمقاييس معتمدة مسبقًا.'),t('Pilot: test in the intended operating context with an accountable owner.','تجريب: اختبار في سياق التشغيل المستهدف مع مسؤول واضح.'),t('Transition: accept evidence, operating responsibilities and rollback arrangements.','نقل للتشغيل: قبول الأدلة ومسؤوليات التشغيل وترتيبات الرجوع.')]},
 {title:t('Proposed evaluation','التقييم المقترح'),body:c.test},
 {title:t('Stop or change direction','متى نوقف المسار أو نغيره؟'),body:c.stop},
 {title:t('Who will operate the capability?','مَن سيشغّل القدرة؟'),body:c.transfer},
 {title:t('The team to assemble','الفريق المطلوب تجميعه'),items:[t('A program manager accountable for the capability and its evidence.','مدير برنامج مسؤول عن القدرة وأدلتها.'),t('A domain specialist, technical builder and independent reviewer.','متخصص بالمجال ومنفذ تقني ومراجع مستقل.'),t('A beneficiary representative who can define and accept real operating value.','ممثل للمستفيد يستطيع تحديد وقبول القيمة التشغيلية الفعلية.')]}
],related:[`/opportunities/${c.slug}`, '/programs/program-lifecycle','/work-with-us/prepare-a-concept']}));

export const opportunityEntries:Entry[]=concepts.map(c=>({section:'opportunities',slug:c.slug,code:c.code.replace('P','O'),title:c.title,summary:t('Explore contributing expertise, a test environment or a technical approach to this proposed capability.', 'استكشف المساهمة بخبرة أو بيئة اختبار أو مسار تقني لبناء هذه القدرة المقترحة.'),category:t('Exploratory collaboration','تعاون استكشافي'),status:t('Expression of interest','إبداء اهتمام'),image:c.image,action:'concept',facts:[{label:t('Linked program','البرنامج المرتبط'),value:c.title},{label:t('Deadline','الموعد النهائي'),value:t('No call or deadline announced','لا توجد دعوة رسمية أو مهلة معلنة')},{label:t('Award / budget','التعاقد / الميزانية'),value:t('Not offered or committed','غير مطروح أو معتمد')}],blocks:[
 {title:t('The question','السؤال'),body:c.summary},
 {title:t('Who could contribute?','مَن يمكنه المساهمة؟'),items:[t('A specialist with evidence of relevant work.','متخصص لديه دليل على عمل ذي صلة.'),t('An institution willing to discuss a bounded test environment.','مؤسسة ترغب في مناقشة بيئة اختبار محددة.'),t('A team able to build and explain a testable approach.','فريق يستطيع بناء وشرح مسار قابل للاختبار.')]},
 {title:t('What to prepare','ما المطلوب تحضيره؟'),items:[t('A plain-language description of your proposed contribution.','وصف واضح للمساهمة المقترحة.'),t('Evidence of relevant experience and the uncertainties you would resolve.','دليل الخبرة المرتبطة وأوجه عدم اليقين التي ستعمل على حسمها.'),t('A first experiment, required access, resources and expected output.','تجربة أولى وصلاحيات وموارد مطلوبة ومخرج متوقع.')]},
 {title:t('How interest is considered','كيف يُنظر في إبداء الاهتمام؟'),body:t('The proposed sequence is fit review, evidence review, a scoping conversation and a separately approved test. Sending a note does not create a contract, award or promise of selection.','المسار المقترح هو مراجعة الملاءمة ثم الأدلة، ومناقشة تحديد النطاق، واختبار يُعتمد بصورة منفصلة. إرسال مذكرة لا ينشئ تعاقدًا أو تمويلًا أو وعدًا بالاختيار.')},
 {title:t('The first proof','الإثبات الأول'),body:c.test}
],related:[`/programs/${c.slug}`,'/work-with-us/how-to-respond','/work-with-us/prepare-a-concept']}));
