import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight} from 'lucide-react';
import {programEntries} from '@/lib/institution/programs';
import {workshopEntries} from '@/lib/institution/workshops';
import {newsEntries} from '@/lib/institution/news';
import type {Locale} from '@/lib/institution/schema';
export default function InstitutionHome({locale}:{locale:Locale}){const ar=locale==='ar';const p=ar?'/ar':'';const session=workshopEntries[0];
 return <><section className="vs-section vs-home-programs"><div className="vs-section-heading"><div><p className="vs-eyebrow">{ar?'من السؤال إلى البرنامج':'FROM QUESTION TO PROGRAM'}</p><h2>{ar?'قدرات تستحق الاستكشاف':'Capabilities worth exploring'}</h2></div><Link className="vs-text-link" href={`${p}/programs`}>{ar?'كل البرامج':'All programs'}<ArrowRight size={20}/></Link></div><p className="vs-home-status">{ar?'تصورات مقترحة — لم تُطلق كبرامج ممولة.':'Proposed concepts — not launched or funded programs.'}</p><div className="vs-home-program-grid">{programEntries.slice(0,3).map(e=><Link href={`${p}/programs/${e.slug}`} key={e.slug}><div><Image src={`/field-${e.image}.jpg`} alt="" fill sizes="(max-width:760px) 100vw, 33vw"/></div><p className="vs-eyebrow">{e.code}</p><h3>{e.title[locale]}</h3><p>{e.summary[locale]}</p><span>{ar?'استكشف التصور':'Explore the concept'}<ArrowRight size={18}/></span></Link>)}</div></section><section className="vs-editorial vs-home-updates"><article className="vs-mission-card"><div className="vs-mini-heading"><h2>{ar?'ورش العمل':'Workshops'}</h2><Link href={`${p}/workshops`}>{ar?'الدورة الأسبوعية':'Weekly cycle'}<ArrowRight size={18}/></Link></div><div className="vs-editorial-image"><Image src="/field-industry.jpg" alt="" fill sizes="(max-width:760px) 100vw, 50vw"/></div><p className="vs-eyebrow">{ar?'الأسبوع الأول · صيغة مخططة':'WEEK 01 · PLANNED FORMAT'}</p><h3>{session.title[locale]}</h3><p>{session.summary[locale]}</p><p className="vs-workshop-home-note">{ar?'المخرج: Brief قدرة من صفحة واحدة. الموعد والميسّر يُعلنان بعد التأكيد.':'Output: a one-page capability brief. Date and host will be announced after confirmation.'}</p><Link className="vs-text-link" href={`${p}/workshops/${session.slug}`}>{ar?'التحضير وجدول العمل':'Preparation & agenda'}<ArrowRight size={20}/></Link></article><div className="vs-reading"><div className="vs-mini-heading"><h2>{ar?'الأخبار والتعلم':'News & learning'}</h2><Link href={`${p}/news`}>{ar?'كل المقالات':'All notes'}<ArrowRight size={18}/></Link></div>{newsEntries.slice(1,4).map(e=><Link className="vs-reading-row" href={`${p}/news/${e.slug}`} key={e.slug}><div className="vs-reading-image"><Image src={`/field-${e.image}.jpg`} alt="" fill sizes="(max-width:760px) 30vw, 16vw"/></div><div><p className="vs-eyebrow">{e.category[locale]}</p><h3>{e.title[locale]}</h3><p>{e.summary[locale]}</p></div></Link>)}</div></section></>;
}
