import Image from "next/image";
import InstitutionHome from "@/components/institution/home-sections";
import Link from "next/link";
import { ArrowRight, Building2, Landmark, Microscope, Users, Factory, Network } from "lucide-react";
import { CapabilityHeader } from "@/components/capability/navigation";
import CapabilityFooter from "@/components/capability/footer";
import CapabilityHero from "@/components/capability/hero";
import MethodSpotlight from "@/components/capability/method-spotlight";
import { communities, fields, type Locale } from "@/components/capability/content";

const icons = [Building2, Landmark, Microscope, Users, Factory, Network];

export default function HomePage({locale}: {locale:Locale}) {
  const ar=locale==="ar";const p=ar?"/ar":"";
  const reading=[
    {href:"/insights/physical-ai",image:"industry",category:ar?"تقرير · بيت القادة":"REPORT · LEADERS HOUSE",title:ar?"عندما يغادر الذكاء الاصطناعي الشاشة":"When AI leaves the screen",text:ar?"قراءة في الذكاء الاصطناعي المادي وما يفتحه من قدرات.":"A perspective on physical AI and the capabilities it could unlock."},
    {href:"/method#highest-level-one",image:"chips",category:ar?"مبدأ · منهجنا":"PRINCIPLE · OUR METHOD",title:"Highest Level One",text:ar?"نختار أفضل الخبرات والتقنيات المناسبة للمهمة، ونبني عليها.":"The highest achievable level using the best of what is possible today."},
    {href:"/about#what-we-build",image:"cities",category:ar?"رؤية · ما نبنيه":"PERSPECTIVE · WHAT WE BUILD",title:ar?"الشكل يتبع القدرة":"The form follows the capability",text:ar?"منظومة، منصة، برنامج، شراكة أو شركة جديدة. نبدأ من القدرة.":"A system, platform, program, partnership or new company. Start with the capability."},
  ];
  return <div className={`vs-site locale-${locale}`} lang={locale} dir={ar?"rtl":"ltr"}>
    <CapabilityHeader locale={locale} overlay/>
    <main id="main-content">
      <CapabilityHero locale={locale}/>
      <section className="vs-editorial" id="vision">
        <article className="vs-mission-card"><div className="vs-mini-heading"><h2>{ar?"السؤال الذي نبدأ منه":"Where we begin"}</h2><Link href={`${p}/about`} aria-label={ar?"عن VisionSeek":"About VisionSeek"}><ArrowRight/></Link></div><div className="vs-editorial-image"><Image src="/field-industry.jpg" alt={ar?"قدرات التصنيع والروبوتات داخل مصنع":"Robotics and manufacturing capabilities inside a factory"} fill sizes="(max-width:760px) 100vw, 50vw"/></div><p className="vs-eyebrow">{ar?"سؤال واحد يفتح مسارًا جديدًا":"ONE QUESTION. A NEW PATH."}</p><h3>{ar?"ما الذي أصبح ممكنًا اليوم، وقد يسبقك به غيرك غدًا؟":"What important capability should exist that does not exist today?"}</h3><p>{ar?"العالم مليء بالتقنيات والخبرات والفرص التي يمكن أن تنقل مؤسستك إلى مستوى جديد. وبينما تتأخر في استكشافها، قد يبني بها غيرك تفوقه. نكتشف معك الفرص التي تصنع الفارق، ونحوّلها إلى قدرات تمتلكها مؤسستك وتنافس بها.":"We start with the capability that should exist. We discover why it does not exist today, then bring together the people, knowledge, technologies and opportunities needed to make it real."}</p><Link className="vs-text-link" href={`${p}/method`}>{ar?"اكتشف منهجنا":"Explore our method"}<ArrowRight size={20}/></Link></article>
        <div className="vs-reading"><div className="vs-mini-heading"><h2>{ar?"من داخل VisionSeek":"Inside VisionSeek"}</h2><Link href={`${p}/insights`}>{ar?"بيت القادة":"Leaders House"}<ArrowRight size={18}/></Link></div>{reading.map(r=><Link className="vs-reading-row" href={`${p}${r.href}`} key={r.href}><div className="vs-reading-image"><Image src={`/field-${r.image}.jpg`} alt="" fill sizes="(max-width:760px) 30vw, 16vw"/></div><div><p className="vs-eyebrow">{r.category}</p><h3>{r.title}</h3><p>{r.text}</p><span className="vs-inline-arrow" aria-hidden="true">↗</span></div></Link>)}</div>
      </section>
      <InstitutionHome locale={locale}/>
      <MethodSpotlight locale={locale}/>
      <section className="vs-section vs-communities" id="communities"><div className="vs-section-heading"><div><p className="vs-eyebrow">{ar?"الأشخاص والمؤسسات وراء القدرة":"THE PEOPLE BEHIND THE CAPABILITY"}</p><h2>{ar?"معًا، يصبح الممكن أكبر.":"Possibility grows together."}</h2></div><p>{ar?"المعرفة لا تجتمع كلها داخل مؤسسة واحدة. نبني حول القدرة الفريق والشراكات التي تحتاجها فعلًا.":"No single institution holds all the knowledge. We bring together the team and partnerships a capability actually needs."}</p></div><div className="vs-community-grid">{communities.map((c,i)=>{const Icon=icons[i];return <Link href={`${p}/work-with-us#${c.id}`} key={c.id} className="vs-community-card"><Icon size={40} strokeWidth={1.25}/><h3>{ar?c.ar:c.en}</h3><p>{ar?c.textAr:c.textEn}</p><ArrowRight className="vs-card-arrow" size={22}/></Link>;})}</div></section>
      <section className="vs-section vs-fields" id="fields"><div className="vs-section-heading"><div><p className="vs-eyebrow">{ar?"مجالات نستكشفها":"FIELDS OF EXPLORATION"}</p><h2>{ar?"أين نبحث عن الممكن":"Where we look for possibility"}</h2></div><div><p>{ar?"من العلم والصناعة إلى البنية التحتية. مجالات نتابعها بحثًا عن قدرات تستحق البناء.":"From science and industry to infrastructure. Fields we explore for capabilities worth building."}</p><Link className="vs-text-link" href={`${p}/projects`}>{ar?"استكشف المجالات":"Explore the fields"}<ArrowRight size={20}/></Link></div></div><div className="vs-fields-grid">{fields.map(([id,en,arabic,img],i)=><Link href={`${p}/projects#${id}`} key={id} className="vs-field-card"><Image src={`/field-${img}.jpg`} alt="" fill sizes="(max-width:600px) 100vw, (max-width:1000px) 50vw, 25vw"/><div><span>0{i+1}</span><h3>{ar?arabic:en}</h3><ArrowRight size={21}/></div></Link>)}</div></section>
      <section className="vs-work-feature"><div className="vs-work-copy"><p className="vs-eyebrow">{ar?"اعمل مع VisionSeek":"WORK WITH VISIONSEEK"}</p><h2>{ar?"ابدأ بقدرة تستحق أن توجد.":"Begin with a capability worth building."}</h2><p>{ar?"قد ترى فرصة لم تصل إليها مؤسستك بعد، أو تملك خبرة تساعد في بنائها. لنحدد معًا القدرة التي تستحق أن نبدأ بها.":"You may be an institution with an unmet need, an expert with deep knowledge, or a partner who sees an opportunity. Begin by defining what should become possible."}</p><Link className="vs-button" href={`${p}/start`}>{ar?"ابنِ قدرة معنا":"Build a capability with us"}<ArrowRight size={20}/></Link></div><div className="vs-work-image"><Image src="/field-energy.jpg" alt={ar?"بنية تحتية للطاقة المتجددة":"Renewable energy infrastructure"} fill sizes="(max-width:760px) 100vw, 50vw"/></div></section>
      <section className="vs-section vs-contact" id="contact"><p className="vs-eyebrow">{ar?"ابدأ محادثة":"START A CONVERSATION"}</p><h2>{ar?"ما القدرة التي تريد بناءها قبل أن يسبقك إليها غيرك؟":"What should become possible?"}</h2><Link className="vs-button" href={`${p}/start`}>{ar?"ابنِ قدرة معنا":"Build a capability with us"}<ArrowRight size={20}/></Link><div className="vs-contact-links"><a href="mailto:abdelalim@visionseek.org"><span>{ar?"البريد الإلكتروني":"Email"}</span><strong>abdelalim@visionseek.org</strong><ArrowRight size={22}/></a><a href="https://wa.me/821042419606" target="_blank" rel="noreferrer"><span>{ar?"واتساب":"WhatsApp"}</span><strong dir="ltr">+82 10 4241 9606</strong><ArrowRight size={22}/></a><a href="https://www.linkedin.com/in/ahmed-abdelalim-462491160/" target="_blank" rel="noreferrer"><span>LinkedIn</span><strong>{ar?"أحمد عبدالعليم":"Ahmed Abdelalim"}</strong><ArrowRight size={22}/></a></div><Link className="vs-founder-link" id="founder" href={`${p}/about#founder`}>{ar?"تعرّف على المؤسس والرؤية":"Meet the founder and explore the vision"}<ArrowRight size={18}/></Link></section>
    </main><CapabilityFooter locale={locale}/>
  </div>;
}
