import Link from 'next/link';
import MedicalFeed from './medical-feed';
import {CapabilityHeader} from '@/components/capability/navigation';
import CapabilityFooter from '@/components/capability/footer';
import {pick,localePrefix,type PublicLocale} from './locale';
import styles from './focus.module.css';
// Sector is metadata, so the editorial space can expand without restoring cartoon personas.
export const leadersNotes=[
 {id:'capability-and-product',sector:'pharmaceuticals',title:{ar:'حين تنتقل التقنية، ما الذي ينبغي أن يبقى داخل المؤسسة؟',en:'When technology moves, what should stay inside the institution?',ko:'기술이 이전될 때 기관 안에 무엇이 남아야 할까요?'},body:{ar:'امتلاك منتج وامتلاك القدرة على استخدامه وتطويره نتيجتان مختلفتان. في الصناعة الدوائية، تمتد قيمة نقل القدرة إلى المعرفة التي يفهمها الفريق، والخبرة التي يستطيع تطبيقها، والقدرة على مواصلة العمل محليًا. هذه زاوية ننظر منها إلى أهمية نقل المعرفة والتدريب مع التقنية.',en:'Owning a product and having the capability to use and develop it are different outcomes. In pharmaceuticals, capability transfer includes knowledge a team understands, expertise it can apply, and the ability to sustain work locally. This is a perspective on why knowledge and training matter alongside technology.',ko:'제품을 보유하는 것과 이를 활용하고 발전시킬 역량을 갖추는 것은 서로 다른 결과입니다. 제약 분야의 역량 이전에는 팀이 이해하는 지식, 적용할 수 있는 전문성, 현지에서 업무를 지속할 수 있는 능력이 포함됩니다. 기술과 함께 지식과 교육이 중요한 이유를 살펴보는 관점입니다.'}},
 {id:'announcement-and-capability',sector:'health',title:{ar:'الإعلان عن تقنية ليس دليلًا على إمكانية نقلها.',en:'A technology announcement is not proof that it can be transferred.',ko:'기술 발표만으로 이전 가능성이 입증되지는 않습니다.'},body:{ar:'قد يصف الإعلان نتيجة واعدة، لكنه لا يوضح دائمًا من يملك الحقوق أو ما الذي ثبت في التشغيل أو ما يحتاجه تطبيقها في بيئة أخرى. عند قراءة حركة القطاع، من المفيد التمييز بين بحث منشور، وتقنية مستخدمة، وقدرة متاحة فعلًا للنقل. اختلاف هذه الحالات يغيّر معنى الفرصة للمؤسسة.',en:'An announcement may describe a promising result without establishing ownership rights, operating evidence or what application in another setting requires. When following the sector, it is useful to distinguish published research, technology in use and a capability actually available for transfer. These differences change what an opportunity means for an institution.',ko:'발표는 유망한 결과를 소개할 수 있지만 권리 보유자, 운영 근거, 다른 환경에서의 적용 요건까지 보여 주지는 않을 수 있습니다. 산업 동향을 볼 때 발표된 연구, 실제 활용 중인 기술, 실제로 이전 가능한 역량을 구분할 필요가 있습니다. 이 차이는 기관에 그 기회가 갖는 의미를 바꿉니다.'}},
];
export default function FocusLeaders({locale}:{locale:PublicLocale}) {
 const t=(ar:string,en:string,ko:string)=>pick(locale,ar,en,ko);const p=localePrefix(locale);
 return <div className={`vs-site locale-${locale}`} lang={locale} dir={locale==='ar'?'rtl':'ltr'}><CapabilityHeader locale={locale} path="/insights"/><main className={styles.page} id="main-content"><section className={styles.hero}><p className={styles.eyebrow}>VISIONSEEK / {t('بيت القادة','LEADERS HOUSE','리더스 하우스')}</p><h1>{t('ما وراء التقنية: حركة القدرات في الصحة والدواء.','Beyond the technology: capability transfer in health and pharmaceuticals.','기술을 넘어: 보건·제약 분야의 역량 이전.')}</h1><p className={styles.lead}>{t('قراءات للمصانع والمؤسسات والجهات الحكومية لفهم ما يمكن أن يعنيه التقدم التقني لامتلاك قدرة محلية. تركيزنا الحالي طبي ودوائي، مع مساحة للتوسع إلى مجالات أخرى.','Perspectives for manufacturers, institutions and government bodies on what technological progress could mean for local capability. Our current focus is health and pharmaceuticals, with room to expand into other fields.','기술의 진보가 현지 역량에 갖는 의미를 살펴보는 제조사, 기관 및 정부 관계자를 위한 글입니다. 현재는 보건·제약 분야에 집중하며 향후 다른 분야로 확장할 수 있습니다.')}</p></section><MedicalFeed locale={locale}/><section className={`${styles.section} ${styles.light}`}><p className={styles.eyebrow}>{t('قراءات تحريرية · VISIONSEEK','EDITORIAL PERSPECTIVES · VISIONSEEK','편집 관점 · VISIONSEEK')}</p><div className={`${styles.cards} ${styles.two}`}>{leadersNotes.map(note=><article id={note.id} key={note.id}><p className={styles.eyebrow}>{note.sector==='pharmaceuticals'?t('الصناعة الدوائية','Pharmaceuticals','제약'):t('الصحة ونقل القدرات','Health & capability transfer','보건 및 역량 이전')}</p><h2>{note.title[locale]}</h2><p>{note.body[locale]}</p></article>)}</div><p className={styles.note}>{t('هذه قراءات تحريرية، وليست أخبارًا عن صفقات أو مشروعات منفذة أو توصيات علاجية.','These are editorial perspectives, not reports of transactions, delivered projects or treatment recommendations.','이 글은 편집 관점이며 거래, 완료된 프로젝트 또는 치료 권고를 보고하는 내용이 아닙니다.')}</p></section><section className={styles.section}><h2>{t('أرشيف التقارير','Research archive','보고서 아카이브')}</h2><Link className={styles.link} href={`${p}/reports`}>{t('اقرأ التقارير ومراجعها','Read reports and their sources','보고서 및 출처 보기')} ↗</Link></section></main><CapabilityFooter locale={locale}/></div>;
}
