'use client';
import Image from 'next/image';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Bookmark,BookOpen,Check,ChevronLeft,ChevronRight,Clapperboard,Compass,Home,Search,Share2,ThumbsUp,X} from 'lucide-react';
import {Dialog,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {ReaderDialogContent} from '@/components/leaders/reader-dialog';
import {leadersClient,withMedia} from '@/lib/leaders/client';
import {isMedicalPublication,MEDICAL_PUBLISHING_ID} from '@/lib/leaders/medical-focus';
import {postText,safeLink,type LeaderPost} from '@/lib/leaders/types';
import {collectionOptions,emptyPreferences,normalizePreferences,toggleCollection,type CollectionId,type ReaderPreferences} from '@/lib/leaders/reader';
import {medicalReadings,medicalChannels,medicalChannel,readingPost,type MedicalChannel} from '@/lib/leaders/medical-edition';
import {MedicalPostCard,ReadingVisual} from './medical-post-card';
import {localePrefix,pick,type PublicLocale} from './locale';
import styles from './medical-feed.module.css';
const StoryPlayer=dynamic(()=>import('@/components/leaders/story-player').then(m=>m.StoryPlayer));
const ReelPlayer=dynamic(()=>import('@/components/leaders/reel-player').then(m=>m.ReelPlayer));
const PhotoViewer=dynamic(()=>import('@/components/leaders/photo-viewer').then(m=>m.PhotoViewer));
const PostMedia=dynamic(()=>import('@/components/leaders/media').then(m=>m.PostMedia));
type View='feed'|'explore'|'reels'|'saved';
const STORAGE='vs-leaders-reader-v1';
function readIds(key:string):string[]{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v.filter(s=>typeof s==='string'&&/^[\w-]{1,100}$/.test(s)):[];}catch{return [];}}
function present(post:LeaderPost):LeaderPost{return {...post,character_id:null};}
async function loadPage(before?:string){
 let q=leadersClient().from('leaders_posts').select('*').eq('status','published').eq('character_id',MEDICAL_PUBLISHING_ID).order('published_at',{ascending:false}).order('id',{ascending:false}).limit(25);
 if(before){const [date,id]=before.split('|');q=q.or(`published_at.lt.${date},and(published_at.eq.${date},id.lt.${id})`);}
 const {data,error}=await q;if(error)throw error;const rows=(data||[]) as LeaderPost[],page=rows.slice(0,24),last=page.at(-1);
 return {posts:await withMedia(page.filter(p=>isMedicalPublication(p))),more:rows.length>24,cursor:last?`${last.published_at}|${last.id}`:undefined};
}
export default function MedicalFeed({locale}:{locale:PublicLocale}){
 const t=(ar:string,en:string,ko:string)=>pick(locale,ar,en,ko),p=localePrefix(locale),mediaLocale=locale==='ar'?'ar':'en';
 const [view,setView]=useState<View>('feed'),[channel,setChannel]=useState<MedicalChannel>('all'),[query,setQuery]=useState(''),[latest,setLatest]=useState(false);
 const [live,setLive]=useState<LeaderPost[]>([]),[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[more,setMore]=useState(false),[cursor,setCursor]=useState<string>(),[busy,setBusy]=useState(false),[now,setNow]=useState(()=>Date.now());
 const [prefs,setPrefs]=useState<ReaderPreferences>(emptyPreferences),[liked,setLiked]=useState<string[]>([]),[seen,setSeen]=useState<string[]>([]),[collection,setCollection]=useState<CollectionId|'all'>('all');
 const [detail,setDetail]=useState<LeaderPost|null>(null),[saving,setSaving]=useState<LeaderPost|null>(null),[sharing,setSharing]=useState<LeaderPost|null>(null),[story,setStory]=useState(-1),[reel,setReel]=useState<string|null>(null),[photo,setPhoto]=useState<{url:string;title:string}|null>(null),[notice,setNotice]=useState(''),[shareUrl,setShareUrl]=useState('');
 const local=useMemo(()=>medicalReadings.map(r=>readingPost(r,locale)),[locale]);
 const all=useMemo(()=>[...new Map([...live.filter(post=>isMedicalPublication(post,now)).map(present),...local].map(post=>[post.id,post])).values()],[live,local,now]);
 const stories=useMemo(()=>[...all.filter(post=>post.kind==='story'),...medicalReadings.map(r=>({...readingPost(r,locale),id:`story-${r.id}`,kind:'story' as const,body:r.intro.ar+'\n\n'+r.question.ar,body_en:r.intro[locale]+'\n\n'+r.question[locale],highlight:true}))],[all,locale]);
 const videos=all.filter(post=>post.kind==='video'&&post.media_url);
 const refresh=useCallback(async()=>{try{const r=await loadPage();setLive(old=>[...r.posts,...old.filter(post=>!r.posts.some(n=>n.id===post.id))]);setCursor(r.cursor);setMore(r.more);setStatus('ready');}catch{setStatus('error');}},[]);
 // Restore URL/device state after hydration and start asynchronous publication loading.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{let active=true;void refresh();
  setLiked(readIds('vs-leaders-liked'));setSeen(readIds('vs-leaders-seen'));
  let restored=emptyPreferences;try{restored=normalizePreferences(JSON.parse(localStorage.getItem(STORAGE)||'null'),readIds('vs-leaders-saved'));for(const id of readIds('vs-medical-reading-saved-v1'))if(!restored.collections[id])restored.collections[id]=['later'];setPrefs(restored);}catch{}
  const params=new URLSearchParams(window.location.search),requestedView=params.get('view'),requestedPost=params.get('post');
  if(['feed','explore','reels','saved'].includes(requestedView||''))setView(requestedView as View);
  const requestedChannel=params.get('channel');if(medicalChannels.some(c=>c.id===requestedChannel))setChannel(requestedChannel as MedicalChannel);
  const reading=local.find(post=>post.id===requestedPost);if(reading)setDetail(reading);
  // Shared and saved publications can sit beyond the first page. Rehydrate them
  // under the same sector/status rules as the main feed.
  const ids=[...new Set([...Object.keys(restored.collections),...(requestedPost?[requestedPost]:[])])].filter(id=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id));
  if(ids.length)void (async()=>{try{const batches=[];for(let i=0;i<ids.length;i+=50)batches.push(ids.slice(i,i+50));const results=await Promise.all(batches.map(async batch=>{const {data,error}=await leadersClient().from('leaders_posts').select('*').eq('status','published').eq('character_id',MEDICAL_PUBLISHING_ID).in('id',batch);if(error)throw error;return (data||[]) as LeaderPost[];}));const rows=await withMedia(results.flat().filter(post=>isMedicalPublication(post)));if(!active)return;setLive(old=>[...new Map([...old,...rows].map(post=>[post.id,post])).values()]);const shared=rows.find(post=>post.id===requestedPost);if(shared){if(shared.kind==='video')setReel(shared.id);else setDetail(present(shared));}}catch{if(active)setNotice(pick(locale,'تعذر استعادة بعض المحفوظات. أعد المحاولة.','Some saved readings could not be restored. Retry.','저장한 글 일부를 불러오지 못했습니다. 다시 시도하세요.'));}})();
  const timer=setInterval(()=>setNow(Date.now()),30000);return()=>{active=false;clearInterval(timer);};
 },[local,locale,refresh]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer);},[notice]);
 const filtered=all.filter(post=>post.kind!=='story'&&(view!=='reels'||post.kind==='video')&&(view!=='saved'||!!prefs.collections[post.id]?.length)&&(collection==='all'||view!=='saved'||prefs.collections[post.id]?.includes(collection))&&(channel==='all'||medicalChannel(post)===channel)&&`${postText(post,mediaLocale).title} ${postText(post,mediaLocale).body}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 if(latest)filtered.sort((a,b)=>Date.parse(b.published_at||b.created_at)-Date.parse(a.published_at||a.created_at));
 function navigate(next:View){setView(next);setQuery('');setChannel('all');const url=new URL(window.location.href);url.searchParams.delete('post');url.searchParams.set('view',next);window.history.replaceState(null,'',url);window.scrollTo({top:0,behavior:'instant'});}
 function persist(next:ReaderPreferences){setPrefs(next);try{localStorage.setItem(STORAGE,JSON.stringify(next));localStorage.removeItem('vs-medical-reading-saved-v1');}catch{setNotice(t('تعذر الحفظ على هذا الجهاز.','Could not save on this device.','이 기기에 저장할 수 없습니다.'));}}
 function like(id:string){const ids=liked.includes(id)?liked.filter(v=>v!==id):[...liked,id];setLiked(ids);try{localStorage.setItem('vs-leaders-liked',JSON.stringify(ids));}catch{setNotice(t('تعذر حفظ التفاعل.','Could not save your reaction.','반응을 저장할 수 없습니다.'));}}
 function open(post:LeaderPost){setDetail(post);const url=new URL(window.location.href);url.searchParams.set('post',post.id);window.history.replaceState(null,'',url);}
 function close(){setDetail(null);const url=new URL(window.location.href);url.searchParams.delete('post');window.history.replaceState(null,'',url);}
 function share(post:LeaderPost){setSharing(post);setShareUrl(`${window.location.origin}${p}/insights?post=${encodeURIComponent(post.id)}`);}
 async function copy(){try{await navigator.clipboard.writeText(shareUrl);setNotice(t('تم نسخ رابط القراءة.','Reading link copied.','글 링크를 복사했습니다.'));}catch{setNotice(t('يمكنك تحديد الرابط ونسخه.','Select and copy the link.','링크를 선택해 복사하세요.'));}}
 function openStory(index:number){setStory(index);const ids=[...new Set([...seen,stories[index].id])];setSeen(ids);try{localStorage.setItem('vs-leaders-seen',JSON.stringify(ids));}catch{}}
 async function next(){setBusy(true);try{const r=await loadPage(cursor);setLive(old=>[...new Map([...old,...r.posts].map(post=>[post.id,post])).values()]);setMore(r.more);setCursor(r.cursor);}catch{setNotice(t('تعذر تحميل المزيد. حاول مرة أخرى.','Could not load more. Try again.','더 불러올 수 없습니다. 다시 시도하세요.'));}finally{setBusy(false);}}
 const nav=[{id:'feed' as const,icon:Home,label:t('الرئيسية','Feed','피드')},{id:'explore' as const,icon:Compass,label:t('اكتشف','Explore','둘러보기')},{id:'reels' as const,icon:Clapperboard,label:t('فيديوهات','Videos','영상')},{id:'saved' as const,icon:Bookmark,label:t('المحفوظات','Saved','저장한 글')}];
 const detailReading=medicalReadings.find(r=>r.id===detail?.id);
 return <div className={`${styles.app} locale-${locale}`} lang={locale} dir={locale==='ar'?'rtl':'ltr'}>
  <a className={styles.skip} href="#leaders-feed">{t('انتقل إلى المنشورات','Skip to feed','피드로 이동')}</a>
  <header className={styles.masthead}><Link className={styles.brand} href={`${p}/insights`}><Image src="/visionseek-symbol-color.png" width={38} height={38} alt=""/><span><strong>{t('بيت القادة','Leaders House','리더스 하우스')}</strong><small>BY VISIONSEEK</small></span></Link><p>{t('الصحة والدواء · رؤية أوسع لقرارك','HEALTH & PHARMA · A WIDER PERSPECTIVE','보건·제약 · 더 넓은 관점')}</p><nav aria-label={t('اللغة','Language','언어')}>{(['ar','en','ko'] as const).map(l=><Link key={l} aria-current={l===locale?'page':undefined} href={`${localePrefix(l)}/insights`}>{l==='ar'?'عربي':l==='en'?'EN':'한국어'}</Link>)}</nav></header>
  <div className={styles.layout}>
   <aside className={styles.sidebar}><div className={styles.sidebarTitle}>{t('مساحتك للمعرفة','YOUR READING SPACE','나의 읽기 공간')}</div><nav aria-label={t('تنقّل بيت القادة','Leaders House navigation','리더스 하우스 메뉴')}>{nav.map(n=><button key={n.id} aria-current={view===n.id?'page':undefined} onClick={()=>navigate(n.id)}><n.icon size={21}/>{n.label}</button>)}</nav><div className={styles.sidebarDivider}/><p className={styles.sidebarTitle}>{t('تابع ما يهمك','FOLLOW YOUR INTERESTS','관심 분야')}</p>{medicalChannels.slice(1).map(c=><button className={styles.channelButton} key={c.id} aria-pressed={channel===c.id} onClick={()=>{setView('feed');setChannel(c.id);setQuery('');}}><span/>{c.label[locale]}</button>)}<div className={styles.sidebarBottom}><Link href={p||'/'}>{t('موقع VisionSeek','VisionSeek website','VisionSeek 웹사이트')}<ArrowUpRight size={16}/></Link><p>{t('حفظك وتفاعلك على هذا الجهاز.','Saved readings and reactions stay on this device.','저장한 글과 반응은 이 기기에 보관됩니다.')}</p><Link href={`${p}/privacy`}>{t('الخصوصية','Privacy','개인정보')}</Link></div></aside>
   <main className={styles.center} id="main-content">
    {view==='feed'&&<><section className={styles.cover}><span>LEADERS HOUSE / HEALTH & PHARMA</span><h1>{t('انظر أبعد من المنتج.','See beyond the product.','제품 너머의 가능성을 보세요.')}</h1><p>{t('ما الذي يتغير في عالم الصحة والدواء، وماذا يمكن أن يعنيه لمؤسستك؟','What is changing in health and pharmaceuticals—and what could it mean for your institution?','보건·제약 분야의 변화는 귀 기관에 어떤 의미일까요?')}</p><div>{t('للمصنّعين والقادة وصنّاع القرار','FOR MANUFACTURERS, LEADERS & DECISION-MAKERS','제조사·기관 리더·정책 결정자를 위한 공간')}</div></section>
    <section className={styles.stories} aria-label={t('القصص والمختارات','Stories and highlights','스토리와 주요 글')}><div className={styles.sectionHeading}><strong>{t('في دقيقة · فكرة تستحق انتباهك','A MINUTE · A FRESH PERSPECTIVE','1분 · 새로운 관점')}</strong><BookOpen size={17}/></div><div className={styles.storyRail}>{stories.map((post,index)=>{const reading=medicalReadings.find(r=>`story-${r.id}`===post.id);return <button key={post.id} className={`${styles.storyCard} ${seen.includes(post.id)?styles.seen:''}`} onClick={()=>openStory(index)} aria-label={postText(post,mediaLocale).title}>{reading?<ReadingVisual reading={reading} locale={locale} compact/>:<div className={styles.liveStory}><BookOpen/><strong>{postText(post,mediaLocale).title}</strong></div>}<span className={styles.storyArrow}>{locale==='ar'?<ChevronLeft size={16}/>:<ChevronRight size={16}/>}</span></button>;})}</div></section></>}
    {view!=='feed'&&<section className={styles.viewHeading}><span>{t('بيت القادة','LEADERS HOUSE','리더스 하우스')}</span><h1>{view==='saved'?t('أفكار تعود إليها.','Ideas worth returning to.','다시 읽을 가치가 있는 생각.'):view==='reels'?t('رؤية أوسع. في فيديو قصير.','A wider perspective. In a short video.','짧은 영상, 더 넓은 관점.'):t('ما الذي يستحق انتباه مؤسستك؟','What deserves your institution’s attention?','귀 기관이 주목해야 할 것은 무엇일까요?')}</h1><p>{view==='saved'?t('ارجع لما حفظته، وخذ منه ما يستحق النقاش مع فريقك.','Return to what you saved and bring it to your team.','저장한 글을 다시 읽고 팀과 나누세요.'):t('قراءات ومصادر في نقل القدرات الصحية والدوائية.','Readings and sources on health and pharmaceutical capability transfer.','보건·제약 역량 이전에 관한 글과 출처입니다.')}</p></section>}
    <div className={styles.feedTools}><label className={styles.search}><Search size={18}/><input aria-label={t('ابحث في بيت القادة','Search Leaders House','리더스 하우스 검색')} placeholder={t('ابحث عن فكرة أو قدرة…','Search ideas or capabilities…','생각이나 역량 검색…')} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label={t('مسح البحث','Clear search','검색 지우기')} onClick={()=>setQuery('')}><X size={16}/></button>}</label><div className={styles.filters} aria-label={t('موضوع القراءة','Reading topic','글 주제')}>{medicalChannels.map(c=><button key={c.id} aria-pressed={channel===c.id} onClick={()=>setChannel(c.id)}>{c.label[locale]}</button>)}</div><div className={styles.order}><button aria-pressed={!latest} onClick={()=>setLatest(false)}>{t('مختارات لك','Selected for you','추천 글')}</button><button aria-pressed={latest} onClick={()=>setLatest(true)}>{t('الأحدث','Latest','최신')}</button><span>{t('الصحة والدواء','HEALTH & PHARMA','보건·제약')}</span></div></div>
    {view==='saved'&&<div className={styles.filters}><button aria-pressed={collection==='all'} onClick={()=>setCollection('all')}>{t('كل المحفوظات','All saved','모든 저장 글')}</button>{collectionOptions.map(c=><button key={c.id} aria-pressed={collection===c.id} onClick={()=>setCollection(c.id)}>{locale==='ko'?{later:'나중에 읽기',team:'팀과 논의',opportunities:'기회 검토'}[c.id]:c[locale]}</button>)}</div>}
    <section id="leaders-feed" className={styles.feed} aria-label={t('المنشورات الطبية والدوائية','Health & pharmaceutical feed','보건·제약 피드')}>
     {status==='error'&&<div className={styles.status} role="status">{t('تعذر تحميل أحدث المنشورات. القراءات التحريرية متاحة أدناه.','Recent posts could not load. Editorial readings remain available.','최신 게시물을 불러오지 못했습니다. 편집 글은 계속 볼 수 있습니다.')} <button onClick={()=>void refresh()}>{t('إعادة المحاولة','Retry','다시 시도')}</button></div>}
     {filtered.length===0&&<div className={styles.empty}>{view==='reels'?<Clapperboard size={36}/>:view==='saved'?<Bookmark size={36}/>:<Search size={36}/>}<h2>{view==='reels'?t('مساحة الفيديوهات الطبية جاهزة.','Ready for health and pharma videos.','보건·제약 영상을 위한 공간입니다.'):view==='saved'?t('احتفظ بالفكرة التي تستحق العودة.','Keep an idea worth returning to.','다시 읽고 싶은 생각을 저장하세요.'):t('لا توجد قراءة مطابقة.','No matching reading.','일치하는 글이 없습니다.')}</h2><p>{view==='reels'?t('تظهر هنا المقاطع الطبية المنشورة. افتح أي مقطع للتنقل بين الفيديوهات بالتمرير العمودي.','Published health videos appear here. Open a clip to browse vertically between videos.','게시된 보건·제약 영상이 여기에 표시됩니다. 영상을 열어 세로로 넘겨 보세요.'):view==='saved'?t('اضغط «حفظ» على أي منشور، واختر مجموعتك.','Choose Save on a post and select a collection.','게시물의 저장을 눌러 모음을 선택하세요.'):t('جرّب كلمة أخرى أو اعرض كل الموضوعات.','Try another term or view all topics.','다른 검색어나 모든 주제를 선택해 보세요.')}</p><button onClick={()=>navigate('feed')}>{t('استكشف القراءات','Explore readings','글 둘러보기')}</button></div>}
     {filtered.map(post=><MedicalPostCard key={post.id} post={post} locale={locale} saved={!!prefs.collections[post.id]?.length} liked={liked.includes(post.id)} onSave={()=>setSaving(post)} onLike={()=>like(post.id)} onShare={()=>share(post)} onRead={()=>open(post)} onVideo={()=>setReel(post.id)} onImage={url=>setPhoto({url,title:postText(post,mediaLocale).title})}/>)}
     {status==='loading'&&<p className={styles.status} role="status">{t('جارٍ تحميل أحدث المنشورات…','Loading recent posts…','최신 게시물 불러오는 중…')}</p>}{more&&<button className={styles.loadMore} onClick={()=>void next()} disabled={busy}>{t('تحميل المزيد','Load more','더 보기')}</button>}
     {!!filtered.length&&<div className={styles.end}><Check size={21}/><p>{t('فكرة واحدة قد تفتح نقاشًا مختلفًا مع فريقك.','One idea can open a different conversation with your team.','하나의 생각이 팀과 새로운 대화를 열 수 있습니다.')}</p></div>}
    </section>
   </main>
   <aside className={styles.context}><section className={styles.desk}><span>{t('ابدأ من هنا','START HERE','여기서 시작하세요')}</span><h2>{t('عدسة أوسع للصناعة الدوائية.','A wider lens on pharmaceuticals.','제약 산업을 보는 더 넓은 시야.')}</h2>{medicalReadings.slice(0,3).map((r,i)=><button key={r.id} onClick={()=>open(readingPost(r,locale))}><b>0{i+1}</b><strong>{r.title[locale]}</strong><ArrowUpRight size={16}/></button>)}</section><section className={styles.sourceDesk}><span>{t('مكتبة المصادر','SOURCE DESK','출처 자료실')}</span><h2>{t('من المؤسسات إلى فهمك.','From institutions to insight.','기관의 지식에서 통찰로.')}</h2>{[{name:'WHO · HTAP',href:medicalReadings[1].source!.url,label:t('نقل التقنيات الصحية','Health technology transfer','보건 기술 이전')},{name:'Medicines Patent Pool',href:medicalReadings[2].source!.url,label:t('التصنيع المحلي والإقليمي','Local & regional manufacturing','현지·지역 제조')},{name:'IVI · Korea',href:medicalReadings[3].source!.url,label:t('بناء الفرق والمعرفة','Building skills & knowledge','지식·인재 역량 강화')}].map(s=><a key={s.name} href={s.href} target="_blank" rel="noopener noreferrer"><strong>{s.name}<ArrowUpRight size={14}/></strong><small>{s.label}</small></a>)}<p>{t('مصادر مستقلة للقراءة؛ إدراجها لا يعني شراكة.','Independent reading sources; inclusion does not imply partnership.','독립적인 참고 출처이며 제휴를 의미하지 않습니다.')}</p></section><section className={styles.editorialNote}><Image src="/visionseek-symbol-color.png" width={28} height={28} alt=""/><h3>{t('معرفة تخدم قرارك.','Knowledge for your decisions.','판단을 돕는 지식.')}</h3><p>{t('قراءات في نقل التقنية والمعرفة. نفصل ما يقوله المصدر عن قراءتنا له.','Perspectives on technology and knowledge transfer. Source material and our interpretation are identified separately.','기술·지식 이전에 관한 관점입니다. 출처의 내용과 우리의 해석을 구분합니다.')}</p><Link href={`${p}/reports`}>{t('أرشيف التقارير','Report archive','보고서 아카이브')}<ArrowUpRight size={15}/></Link></section></aside>
  </div>
  <nav className={styles.mobileNav} aria-label={t('التنقل السريع','Quick navigation','빠른 메뉴')}>{nav.map(n=><button key={n.id} aria-current={view===n.id?'page':undefined} onClick={()=>navigate(n.id)}><n.icon size={21}/><span>{n.label}</span></button>)}<Link href={p||'/'}><Image src="/visionseek-symbol-color.png" width={23} height={23} alt=""/><span>VisionSeek</span></Link></nav>
  {photo&&<PhotoViewer photo={photo} locale={mediaLocale} onClose={()=>setPhoto(null)}/>}
  {story>=0&&stories[story]&&<StoryPlayer key={stories[story].id} posts={stories} index={story} locale={mediaLocale} onIndex={openStory} onClose={()=>setStory(-1)}/>}
  {reel&&videos.some(post=>post.id===reel)&&<ReelPlayer key={reel} posts={videos} start={videos.findIndex(post=>post.id===reel)} locale={mediaLocale} savedIds={Object.keys(prefs.collections)} blocked={!!detail||!!sharing||!!saving} onClose={()=>setReel(null)} onSave={setSaving} onShare={share} onRead={open}/>}
  <Dialog open={!!detail} onOpenChange={v=>{if(!v)close();}}><ReaderDialogContent className={styles.reader} dir={locale==='ar'?'rtl':'ltr'}><DialogTitle>{detail?postText(detail,mediaLocale).title:''}</DialogTitle><DialogDescription>{t('قراءة من بيت القادة · الصحة والدواء','Leaders House reading · Health & pharma','리더스 하우스 · 보건·제약')}</DialogDescription>{detail&&<>{detailReading&&<ReadingVisual reading={detailReading} locale={locale}/>}<p className={styles.readerBody}>{postText(detail,mediaLocale).body}</p>{detail.media_url&&<PostMedia post={detail} locale={mediaLocale} paused={!!saving||!!sharing}/>}<blockquote><small>{t('سؤال للنقاش مع فريقك','A QUESTION FOR YOUR TEAM','팀과 나눌 질문')}</small><p>{detailReading?.question[locale]||t('ماذا يمكن أن يعني هذا لمؤسستنا؟','What could this mean for our institution?','우리 기관에 어떤 의미가 있을까요?')}</p></blockquote>{safeLink(detail.source_url)&&<a className={styles.sourceLink} href={safeLink(detail.source_url)} target="_blank" rel="noopener noreferrer"><BookOpen size={18}/>{detail.source_label||t('المصدر','Source','출처')}<ArrowUpRight size={17}/></a>}<div className={styles.postActions}><button onClick={()=>setSaving(detail)}><Bookmark size={19}/>{t('حفظ','Save','저장')}</button><button onClick={()=>share(detail)}><Share2 size={19}/>{t('مشاركة','Share','공유')}</button><button onClick={()=>like(detail.id)} aria-pressed={liked.includes(detail.id)}><ThumbsUp size={19}/>{t('مفيد','Useful','유용해요')}</button></div></>}</ReaderDialogContent></Dialog>
  <Dialog open={!!saving} onOpenChange={v=>{if(!v)setSaving(null);}}><ReaderDialogContent className={`${styles.reader} ${styles.smallReader}`} dir={locale==='ar'?'rtl':'ltr'}><DialogTitle>{t('خذ الفكرة إلى نقاشك القادم.','Bring the idea to your next conversation.','다음 대화에 이 생각을 가져가세요.')}</DialogTitle><DialogDescription>{t('اختر مجموعة أو أكثر. الحفظ على هذا الجهاز.','Choose one or more collections. Saved on this device.','모음을 선택하세요. 이 기기에 저장됩니다.')}</DialogDescription>{saving&&collectionOptions.map(c=><label className={styles.collection} key={c.id}><input type="checkbox" checked={!!prefs.collections[saving.id]?.includes(c.id)} onChange={()=>persist(toggleCollection(prefs,saving.id,c.id))}/>{locale==='ko'?{later:'나중에 읽기',team:'팀과 논의',opportunities:'기회 검토'}[c.id]:c[locale]}</label>)}<button className={styles.primary} onClick={()=>setSaving(null)}>{t('تم','Done','완료')}</button></ReaderDialogContent></Dialog>
  <Dialog open={!!sharing} onOpenChange={v=>{if(!v)setSharing(null);}}><ReaderDialogContent className={`${styles.reader} ${styles.smallReader}`} dir={locale==='ar'?'rtl':'ltr'}><DialogTitle>{t('شاركها مع فريقك.','Share with your team.','팀과 공유하세요.')}</DialogTitle><DialogDescription>{sharing?postText(sharing,mediaLocale).title:''}</DialogDescription><label className={styles.shareLabel}>{t('رابط القراءة','Reading link','글 링크')}<input value={shareUrl} readOnly dir="ltr" onFocus={e=>e.currentTarget.select()}/></label><button className={styles.primary} onClick={()=>void copy()}>{t('نسخ الرابط','Copy link','링크 복사')}</button></ReaderDialogContent></Dialog>
  {notice&&<div className={styles.toast} role="status">{notice}</div>}
 </div>;
}
