import Link from 'next/link';
import {CapabilityHeader} from '@/components/capability/navigation';
import CapabilityFooter from '@/components/capability/footer';
import {pick,localePrefix,type PublicLocale} from './locale';
import styles from './focus.module.css';
export default function FocusReports({locale}:{locale:PublicLocale}) {
 const t=(ar:string,en:string,ko:string)=>pick(locale,ar,en,ko);const p=localePrefix(locale);
 return <div className={`vs-site locale-${locale}`} lang={locale} dir={locale==='ar'?'rtl':'ltr'}><CapabilityHeader locale={locale} path="/reports"/><main className={styles.page} id="main-content"><section className={styles.hero}><p className={styles.eyebrow}>VISIONSEEK / RESEARCH</p><h1>{t('أرشيف التقارير','Research archive','보고서 아카이브')}</h1><p className={styles.lead}>{t('إصدارات سابقة محفوظة بمراجعها وحدودها. وجود تقرير في الأرشيف لا يعرّف تخصص VisionSeek الحالي.','Previous publications preserved with their sources and limitations. An archived report does not define VisionSeek’s current specialization.','출처와 한계를 함께 보존한 이전 발행물입니다. 아카이브의 보고서가 VisionSeek의 현재 전문 분야를 정의하는 것은 아닙니다.')}</p></section><section className={`${styles.section} ${styles.light}`}><p className={styles.eyebrow}>{t('سبتمبر 2026 · إحاطة استراتيجية','SEPTEMBER 2026 · STRATEGIC BRIEF','2026년 9월 · 전략 브리프')}</p><h2>{t('الذكاء الاصطناعي المادي يتحول إلى بنية تحتية وطنية','Physical AI is becoming national infrastructure','국가 인프라로 발전하는 피지컬 AI')}</h2><p>{t('منظور استراتيجي سابق عن التقنية والقدرات المؤسسية. المراجعة المستقلة غير مثبتة؛ تُقرأ الإحاطة مع حدودها المنشورة.','An earlier strategic perspective on technology and institutional capabilities. Independent review is not established; read it with its published limitations.','기술과 기관 역량에 관한 이전의 전략적 관점입니다. 독립 검토는 확인되지 않았으므로 명시된 한계와 함께 읽어 주세요.')}</p><div className={styles.actions}><Link className={styles.link} href={`${locale==='ko'?'':p}/reports/physical-ai`}>{t('اقرأ الإحاطة','Read the brief','브리프 읽기 (영문)')} ↗</Link></div></section></main><CapabilityFooter locale={locale}/></div>;
}
