export type Locale = "en" | "ar";
export const steps = [
  { id: "define", en: "Define the Capability", ar: "نكتشف ما يصنع الفارق لمؤسستك", questionEn: "What should become possible?", questionAr: "ما القدرة التي تستحق أن تمتلكها؟", textEn: "Start with what an institution or government should be able to do. Not a product, a technology, or a ready-made solution. Define who needs to become capable of doing what.", textAr: "نستكشف طموح مؤسستك وما يتيحه العالم من فرص، ونحدد القدرة التي يمكن أن تغيّر ما تقدمه، وكيف تعمل، وأين تنافس.", outputEn: "A precise capability and the people it should serve.", outputAr: "قدرة محددة والأشخاص أو الجهات التي تحتاجها." },
  { id: "limit", en: "Understand the Limit", ar: "نفهم ما يقف بينك وبينها", questionEn: "Why is it not possible today?", questionAr: "ما الذي يمنع مؤسستك من امتلاكها اليوم؟", textEn: "Understand reality before building. Locate the actual constraint: technology, knowledge, organization, data, people, infrastructure, markets—or missing connections between things that already exist.", textAr: "قد تحتاج إلى خبرة، أو تقنية، أو شريك، أو تغيير في طريقة العمل. نحدد ما ينقصك بدقة، وما يحتاج إلى تطوير.", outputEn: "A clear constraint, supported by evidence.", outputAr: "حد حقيقي واضح تدعمه الأدلة." },
  { id: "path", en: "Find the Path", ar: "نرسم طريق امتلاكها", questionEn: "What could make it possible?", questionAr: "كيف نبني هذه القدرة داخل مؤسستك؟", textEn: "Explore a new technology, a different system, a connection across disciplines, an operating model or an unconventional partnership. The goal is to change what becomes possible.", textAr: "نحدد ما نستطيع الاستفادة منه، وما نحتاج إلى تطويره، ومَن نحتاج إلى إشراكه. ثم نضع خطوات واضحة للبناء والاختبار والتشغيل.", outputEn: "A testable path from the current limit to the capability.", outputAr: "مسار قابل للاختبار من الحد الحالي إلى القدرة المطلوبة." },
  { id: "people", en: "Assemble the Right People", ar: "نجمع الأشخاص المناسبين", questionEn: "Build the team the mission needs.", questionAr: "القدرة الكبيرة تحتاج الأشخاص المناسبين.", textEn: "Great capabilities need the right experts, researchers, engineers, companies and practitioners. Knowledge does not have to sit inside one institution. Assemble the team the mission actually needs, wherever that expertise exists.", textAr: "لا نفترض أن كل المعرفة يجب أن توجد داخل مؤسسة واحدة. نبحث عن أفضل الخبراء والباحثين والمهندسين والشركات والفرق المتخصصة وأصحاب الخبرة العملية. ثم نبني حول القدرة الفريق الذي تحتاجه فعلًا.", outputEn: "The right expertise, with clear roles and responsibilities.", outputAr: "الخبرات المناسبة بأدوار ومسؤوليات واضحة." },
  { id: "highest-level-one", en: "Bring the Best of What Exists", ar: "نجمع أفضل ما هو متاح", questionEn: "The Highest Level One principle.", questionAr: "مبدأ Highest Level One.", textEn: "What is the best available in the world today that could take this capability further? Look across research, AI models, technology, companies, infrastructure, industrial capabilities, markets and opportunities. Combine what fits—not simply what is newest. The highest achievable level using the best of what is possible today.", textAr: "نبحث عمّا يمكن الاستفادة منه من أبحاث وتقنيات وخبرات حول العالم. نختار ما يناسب المهمة، ونجمعه لبناء القدرة المطلوبة بأعلى مستوى نستطيع تحقيقه.", outputEn: "A justified selection of capabilities and opportunities.", outputAr: "اختيار مبرر لأفضل القدرات والفرص المناسبة للمهمة." },
  { id: "architect", en: "Architect the Capability", ar: "نصمم منظومة القدرة", questionEn: "Make the elements work as one.", questionAr: "امتلاك العناصر لا يعني امتلاك القدرة.", textEn: "Connect people, technology, knowledge, systems, partners and opportunities. Design how the parts work together, so separate elements become one coherent capability.", textAr: "يجب أن تعمل العناصر معًا. نصمم المنظومة التي تربط الأشخاص والتكنولوجيا والمعرفة والأنظمة والشركاء والفرص، بحيث تتحول العناصر المنفصلة إلى قدرة واحدة متماسكة.", outputEn: "A coherent system with explicit interfaces and ownership.", outputAr: "منظومة متماسكة بروابط ومسؤوليات محددة." },
  { id: "prove", en: "Prove It", ar: "نثبتها في الواقع", questionEn: "An idea is not a capability until it works.", questionAr: "الفكرة ليست قدرة حتى تعمل.", textEn: "Turn assumptions into tests. Define what must be proven, the quickest experiment that reveals the truth, the measures of success, and what would make us stop or change course. Prototype. Test. Measure. Learn.", textAr: "نحوّل الافتراضات إلى اختبارات. ما الذي يجب إثباته؟ ما التجربة الأسرع التي تكشف الحقيقة؟ ما معايير النجاح؟ وما الذي يجعلنا نوقف المسار أو نغيّره؟ نتقدم بالأدلة، لا بالحماس.", outputEn: "Measured evidence and a decision to proceed, adapt or stop.", outputAr: "دليل مقاس وقرار بالاستمرار أو التعديل أو التوقف." },
  { id: "operate", en: "Make It Operational", ar: "نجعلها قابلة للتشغيل", questionEn: "A capability belongs in the real world.", questionAr: "القدرة يجب أن تدخل الواقع.", textEn: "Move beyond the demonstration. Put the capability inside real institutions, real operations and real conditions. Build the responsibilities, tools, governance and operating model needed for sustained use.", textAr: "لا نريد نموذجًا جميلًا يعمل في العرض فقط. ندخل القدرة داخل المؤسسة والعمليات، مع الأشخاص الحقيقيين وفي الظروف الحقيقية. نبني طريقة التشغيل والمسؤوليات والأدوات والحوكمة التي تجعلها قابلة للاستخدام المستمر.", outputEn: "An operating capability with a responsible owner.", outputAr: "قدرة تعمل في الواقع ولها مسؤول واضح." },
  { id: "evolve", en: "Learn and Evolve", ar: "نتعلم ونطوّر", questionEn: "Today’s highest level is not tomorrow’s limit.", questionAr: "القدرة ليست مشروعًا ننتهي منه.", textEn: "Operation begins a new level of learning. Observe, measure, discover new limits and opportunities, and reconsider what has become possible. Operate. Learn. Evolve.", textAr: "بمجرد دخول القدرة الواقع يبدأ مستوى جديد من التعلم. نراقب ونقيس ونتعلم ونكتشف حدودًا وفرصًا جديدة، ثم نعيد النظر فيما أصبح ممكنًا ونطوّر القدرة من جديد. أعلى مستوى ممكن اليوم قد لا يكون أعلى مستوى ممكن غدًا.", outputEn: "An ongoing cycle of measured improvement.", outputAr: "دورة مستمرة من التعلم والتطوير المقاس." },
];
export const communities = [
  { id: "institutions", en: "Institutions", ar: "المؤسسات", textEn: "Build what your organization should become capable of doing.", textAr: "ابنِ ما يجب أن تصبح مؤسستك قادرة على فعله.", detailEn: "Begin with an important capability your institution cannot achieve today. We help define the constraint, design a credible path, test it and establish how it will operate.", detailAr: "نبدأ بقدرة مهمة لا تستطيع مؤسستك تحقيقها اليوم. نحدد المانع، ونصمم مسارًا يمكن اختباره، ثم نبني طريقة تشغيل القدرة داخل المؤسسة." },
  { id: "governments", en: "Governments", ar: "الحكومات", textEn: "Turn strategic ambition into capabilities that can operate.", textAr: "حوّل الطموح الاستراتيجي إلى قدرات قابلة للتشغيل.", detailEn: "Countries shape their future through the capabilities they build: manufacturing, decision-making, science, AI, coordination and competitiveness. We help frame the important capability and design the program and path to make it possible.", detailAr: "تبني الدول مستقبلها بقدرتها على التصنيع واتخاذ القرار واستخدام العلم وتوظيف الذكاء الاصطناعي والتنسيق والمنافسة وبناء قدرات أخرى. نساعد في تحديد القدرات المهمة وتصميم البرامج والمسارات التي تجعلها ممكنة." },
  { id: "researchers", en: "Researchers & Academia", ar: "الباحثون والجامعات", textEn: "Connect scientific knowledge with a mission that needs it.", textAr: "اربط المعرفة العلمية بمهمة تحتاج إليها.", detailEn: "Bring a research question, finding or scientific capability. Start by identifying the real-world capability it could enable and the evidence still needed to take it further.", detailAr: "ابدأ بسؤال بحثي أو اكتشاف أو قدرة علمية، وحدد معنا القدرة الواقعية التي يمكن أن تتيحها، والأدلة اللازمة للانتقال بها إلى المرحلة التالية." },
  { id: "experts", en: "Experts & Engineers", ar: "الخبراء والمهندسون", textEn: "Bring deep expertise to the team a capability needs.", textAr: "ضع خبرتك المتخصصة ضمن الفريق المناسب للمهمة.", detailEn: "We assemble expertise around the mission. Tell us what you know deeply, what you have built, and which capability you want to help make possible.", detailAr: "نجمع الخبرات حول المهمة. أخبرنا بتخصصك وما بنيته، والقدرة التي تريد المشاركة في جعلها ممكنة." },
  { id: "industry", en: "Industry & Technology", ar: "الصناعة والتكنولوجيا", textEn: "Put existing technology and industrial capacity to new use.", textAr: "افتح استخدامات جديدة للتقنيات والقدرات الصناعية.", detailEn: "A useful capability may already exist in a laboratory, factory or technology company. Explore where it fits, what must connect to it, and how its value can be tested in practice.", detailAr: "قد توجد القدرة بالفعل داخل مختبر أو مصنع أو شركة تقنية. نستكشف أين تلائم الحاجة، وما الذي يجب ربطه بها، وكيف يمكن اختبار قيمتها عمليًا." },
  { id: "entrepreneurs", en: "Entrepreneurs & Partners", ar: "رواد الأعمال والشركاء", textEn: "Give a promising capability the right form to grow.", textAr: "امنح القدرة الواعدة الشكل المناسب للنمو.", detailEn: "A capability may need a product, a platform, a partnership or a new company. The form follows the capability, its evidence and the conditions for sustainable operation.", detailAr: "قد تحتاج القدرة إلى منتج أو منصة أو شراكة أو شركة جديدة. نحدد الشكل بحسب القدرة وأدلتها وشروط تشغيلها المستمر." },
];
export const fields = [
  ["space", "Space & Aerospace", "الفضاء والطيران", "space"],
  ["drones", "Drones & Aerial Systems", "الدرونز والأنظمة الجوية", "drones"],
  ["cities", "Future Cities", "مدن المستقبل", "cities"],
  ["science", "Science & Health", "العلم والصحة", "science"],
  ["energy", "Energy & Climate", "الطاقة والمناخ", "energy"],
  ["robots", "Robotics & Smart Industry", "الروبوتات والصناعة الذكية", "industry"],
  ["agriculture", "Agriculture & Food", "الزراعة والغذاء", "food"],
  ["chips", "Chips & Materials", "الرقائق والمواد", "chips"],
];
