import Image from "next/image";
import {SectionNav} from "@/components/institution/pages";
import {getSection} from "@/lib/institution";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CapabilityHeader } from "./navigation";
import CapabilityFooter from "./footer";
import { steps, communities, type Locale } from "./content";

export default function InteriorPage({locale,kind}:{locale:Locale;kind:"method"|"about"|"work-with-us"}) {
  const ar=locale==="ar";const p=ar?"/ar":"";
  const copy={
    method:{label:ar?"هندسة الفرص":"ENGINEERING OPPORTUNITIES",title:ar?"من القدرة المطلوبة إلى واقع يعمل.":"From a capability that should exist to one that works.",intro:ar?"نحدد ما ينبغي أن يصبح ممكنًا، ثم نجمع أفضل الأشخاص والقدرات المتاحة، ونختبر ونشغّل ونطوّر باستمرار.":"Define what should become possible. Bring together the right people and the best available capabilities. Test, operate and keep evolving."},
    about:{label:ar?"عن VisionSeek":"ABOUT VISIONSEEK",title:ar?"نرى ما يمكن أن يكون. ونجعله ممكنًا.":"See what could be. Make it possible.",intro:ar?"نكتشف ما يصبح ممكنًا عندما تتصل الأفكار والتقنيات والأشخاص والأسواق والمؤسسات، ثم نحدد الشكل الصحيح لجعله واقعًا.":"We discover what becomes possible when ideas, technologies, people, markets and institutions connect. Then we find the right form to make it real."},
    "work-with-us":{label:ar?"اعمل معنا":"WORK WITH VISIONSEEK",title:ar?"القدرة الكبيرة تحتاج الأشخاص المناسبين.":"Important capabilities need the right people.",intro:ar?"نبدأ بسؤال: ما القدرة المهمة التي يجب أن توجد لكنها لا توجد اليوم؟ ثم نبني حولها الفريق والمعرفة والتقنيات والشراكات المناسبة.":"Start with a question: what important capability should exist that does not exist today? Build the right team, knowledge, technologies and partnerships around it."},
  }[kind];
  return <div className={`vs-site locale-${locale}`} lang={locale} dir={ar?"rtl":"ltr"}><CapabilityHeader locale={locale} path={`/${kind}`}/><main id="main-content"><section className="vs-interior-hero"><nav className="vs-breadcrumb" aria-label={ar?"مسار الصفحة":"Breadcrumb"}><Link href={p||"/"}>{ar?"الرئيسية":"Home"}</Link><span>/</span><span>{copy.label}</span></nav><p className="vs-eyebrow">{copy.label}</p><h1>{copy.title}</h1><p className="vs-interior-intro">{copy.intro}</p></section>
    {kind==="about" && <SectionNav section={getSection("about")!} locale={locale} path="/about"/>}
    {kind==="method" && <div className="vs-method-layout"><aside><h2>{ar?"منهجنا":"Our method"}</h2><nav aria-label={ar?"خطوات المنهج":"Method steps"}>{steps.map((s,i)=><a href={`#${s.id}`} key={s.id}><span>{String(i+1).padStart(2,"0")}</span>{ar?s.ar:s.en}</a>)}</nav></aside><div>{steps.map((s,i)=><section className="vs-method-step" id={s.id} key={s.id}><span className="vs-step-number">{String(i+1).padStart(2,"0")}</span><div><p className="vs-eyebrow">{ar?s.ar:s.en}</p><h2>{ar?s.questionAr:s.questionEn}</h2><p>{ar?s.textAr:s.textEn}</p>{s.id==="architect"&&<p className="vs-equation">{ar?"الأشخاص × التكنولوجيا × المعرفة × الأنظمة × الشركاء × الفرص":"People × Technology × Knowledge × Systems × Partners × Opportunities"}</p>}<div className="vs-output"><span>{ar?"المخرج":"OUTCOME"}</span><p>{ar?s.outputAr:s.outputEn}</p></div></div></section>)}</div></div>}
    {kind==="work-with-us" && <section className="vs-section vs-audience-list">{communities.map((c,i)=><article id={c.id} key={c.id}><span className="vs-step-number">{String(i+1).padStart(2,"0")}</span><div><h2>{ar?c.ar:c.en}</h2><p>{ar?c.detailAr:c.detailEn}</p><a className="vs-text-link" href={`mailto:abdelalim@visionseek.org?subject=${encodeURIComponent(`VisionSeek — ${c.en}`)}`}>{ar?"ابدأ محادثة":"Start a conversation"}<ArrowRight size={20}/></a></div></article>)}<div className="vs-conversation-note"><h2>{ar?"ماذا تخبرنا في البداية؟":"What should you share first?"}</h2><p>{ar?"القدرة المطلوبة، ومَن يحتاجها، وما الذي يمنعها اليوم، والخبرة أو الموارد التي يمكنك المساهمة بها. رسالة قصيرة تكفي لبدء النقاش.":"The capability you have in mind, who needs it, what prevents it today, and the expertise or resources you can contribute. A short message is enough to begin."}</p></div></section>}
    {kind==="about" && <><section className="vs-section vs-about-vision" id="vision"><p className="vs-eyebrow">{ar?"رؤيتنا":"OUR VISION"}</p><h2>{ar?"أن نبني مؤسسة عالمية توسّع ما يصبح ممكنًا.":"Build a global institution that expands what becomes possible."}</h2><p>{ar?"نساعد المؤسسات والحكومات على تحديد القدرات المهمة التي يجب أن توجد وتصميم المسارات التي تجعلها واقعًا. ننطلق من كوريا الجنوبية، ونربط المعرفة والتقنيات والخبرات والفرص عبر الحدود.":"We help institutions and governments define the important capabilities that should exist and design the paths to make them real. Based in South Korea, we connect knowledge, technologies, expertise and opportunities across borders."}</p></section><section className="vs-section vs-builds" id="what-we-build"><div><p className="vs-eyebrow">{ar?"ما نبنيه":"WHAT VISIONSEEK BUILDS"}</p><h2>{ar?"الشكل يتبع القدرة.":"The form follows the capability."}</h2><p>{ar?"لا نحدد شكل الحل قبل فهم القدرة. نختار الشكل الذي يجعلها قابلة للتحقق والتشغيل والتطور.":"We do not decide the form of a solution before understanding the capability. We choose the form that makes it testable, operational and able to evolve."}</p></div><ul>{(ar?["منظومة تشغيل جديدة","قدرة مؤسسية أو تقنية","منصة أو منتج","برنامج وطني","نظام ذكاء اصطناعي","شراكة أو شركة جديدة","مبادرة بحثية","بنية كاملة لم تكن موجودة"]:["A new operating system","An institutional or technical capability","A platform or product","A national program","An AI system","A partnership or new company","A research initiative","An entirely new infrastructure"]).map(t=><li key={t}>{t}</li>)}</ul></section><section className="vs-section vs-founder" id="founder"><div className="vs-founder-image"><Image src="/ahmed-abdelalim.jpg" alt={ar?"د. أحمد عبدالعليم، مؤسس VisionSeek":"Dr. Ahmed Abdelalim, founder of VisionSeek"} fill sizes="(max-width:760px) 100vw, 40vw"/></div><div><p className="vs-eyebrow">{ar?"المؤسس · الرؤية والاستراتيجية":"FOUNDER · VISION & STRATEGY"}</p><h2>{ar?"د. أحمد عبدالعليم":"Dr. Ahmed Abdelalim"}</h2><p>{ar?"أؤمن أن تغيير العالم لا يبدأ دائمًا باختراع شيء جديد، بل باكتشاف الرابط المفقود بين ما نعرفه وما نستطيع أن نصنعه. من خلال VisionSeek، أطمح إلى جمع التكنولوجيا والعلم والتصميم وريادة الأعمال في مشروعات تفتح إمكانات جديدة للإنسان والمجتمع.":"I believe changing the world does not always begin with inventing something new, but with discovering the missing connection between what we know and what we can build. Through VisionSeek, I aim to unite technology, science, design and entrepreneurship in projects that unlock new possibilities for people and society."}</p><blockquote>{ar?"المستقبل موجود بالفعل… لكنه لم يُربط بعد.":"The future is already here. It simply has not been connected yet."}</blockquote></div></section></>}
    <section className="vs-section vs-interior-close"><p className="vs-eyebrow">{ar?"السؤال التالي":"THE NEXT QUESTION"}</p><h2>{ar?"ما الذي يجب أن يصبح ممكنًا؟":"What should become possible?"}</h2><a className="vs-button" href="mailto:abdelalim@visionseek.org">{ar?"ابدأ محادثة":"Start a conversation"}<ArrowRight size={20}/></a><p className="vs-closing-line">Make It Possible.</p></section>
  </main><CapabilityFooter locale={locale}/></div>;
}
