"use client";
import Image from 'next/image';
import Link from 'next/link';
import {useState,useEffect,useRef} from 'react';
import {Menu,ChevronDown,ArrowRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger} from '@/components/ui/sheet';
import {institutionNav} from '@/lib/institution/navigation';
import type {Locale} from './content';
export function CapabilityHeader({locale,path='',overlay=false}:{locale:Locale;path?:string;overlay?:boolean}){
 const ar=locale==='ar';const p=ar?'/ar':'';const [open,setOpen]=useState(false);const [expanded,setExpanded]=useState<string|null>(null);const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const close=(event:PointerEvent)=>{if(ref.current&&!ref.current.contains(event.target as Node))setExpanded(null);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 const active=institutionNav.find(n=>n.path===expanded);
 return <header ref={ref} className={`vs-header vs-expanded-header ${overlay?'vs-header-overlay':''}`} onKeyDown={e=>{if(e.key==='Escape'){setExpanded(null);const trigger=ref.current?.querySelector<HTMLButtonElement>(`button[data-menu="${expanded}"]`);trigger?.focus();}}}>
 <a className="vs-skip" href="#main-content">{ar?'انتقل إلى المحتوى':'Skip to content'}</a><div className="vs-utility"><span>{ar?'هندسة الفرص':'ENGINEERING OPPORTUNITIES'}</span><nav aria-label={ar?'روابط مساعدة':'Utility navigation'}><Link href={`${p}/method`}>{ar?'منهجنا':'Our Method'}</Link><Link href={`${p}/projects`}>{ar?'المجالات':'Fields'}</Link><Link href={`${p}/insights`}>{ar?'بيت القادة':'Leaders House'}</Link><Link href={`${p}/#contact`}>{ar?'تواصل':'Contact'}</Link></nav></div>
 <div className="vs-nav-wrap"><Link href={p||'/'} className="vs-logo" aria-label={ar?'VisionSeek — الرئيسية':'VisionSeek — home'}><Image src="/visionseek-logo-v2.png" alt="VisionSeek" width={1920} height={440} priority/></Link><nav className="vs-desktop-nav" aria-label={ar?'التنقل الرئيسي':'Primary navigation'}>{institutionNav.map(n=><div className="vs-nav-group" key={n.path}><Link href={`${p}${n.path}`} aria-current={path===n.path?'page':undefined} onClick={()=>setExpanded(null)}>{ar?n.ar:n.en}</Link><button data-menu={n.path} aria-label={ar?`قائمة ${n.ar}`:`${n.en} menu`} aria-expanded={expanded===n.path} aria-controls="institution-menu" onClick={()=>setExpanded(expanded===n.path?null:n.path)}><ChevronDown size={13}/></button></div>)}<Link className="vs-language" href={`${ar?'':'/ar'}${path}`||'/'} hrefLang={ar?'en':'ar'}>{ar?'EN':'العربية'}</Link></nav>
 <Link className="vs-start-nav" href={`${p}/start`}>{ar?'ابنِ قدرة معنا':'Build with us'}</Link><div className="vs-mobile-menu"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="vs-menu-button"><Menu size={22}/><span>{ar?'القائمة':'Menu'}</span></SheetTrigger><SheetContent side={ar?'left':'right'} className="vs-menu-sheet vs-full-menu" dir={ar?'rtl':'ltr'}><SheetTitle>VisionSeek</SheetTitle><SheetDescription>{ar?'اكتشف ما يمكن أن يصبح ممكنًا.':'See what could be. Make it possible.'}</SheetDescription><nav aria-label={ar?'قائمة الهاتف':'Mobile navigation'}>{institutionNav.map(n=><details key={n.path}><summary>{ar?n.ar:n.en}<ChevronDown size={15}/></summary><Link href={`${p}${n.path}`} onClick={()=>setOpen(false)}>{ar?'نظرة عامة':'Overview'}<ArrowRight size={15}/></Link>{n.children.filter(c=>c[0]!==n.path).map(([href,en,arabic])=><Link key={href} href={`${p}${href}`} onClick={()=>setOpen(false)}>{ar?arabic:en}</Link>)}</details>)}<Link href={`${ar?'':'/ar'}${path}`||'/'} onClick={()=>setOpen(false)}>{ar?'English':'العربية'}</Link><Link href={`${p}/insights`} onClick={()=>setOpen(false)}>{ar?'بيت القادة':'Leaders House'}</Link><Link href={`${p}/#contact`} onClick={()=>setOpen(false)}>{ar?'تواصل':'Contact'}</Link></nav></SheetContent></Sheet></div></div>
 {active&&<nav id="institution-menu" className="vs-mega-menu" aria-label={ar?active.ar:active.en}><div><p className="vs-eyebrow">VISIONSEEK</p><h2>{ar?active.ar:active.en}</h2><Link href={`${p}${active.path}`} onClick={()=>setExpanded(null)} className="vs-text-link">{ar?'استكشف القسم':'Explore section'}<ArrowRight size={18}/></Link></div><div>{active.children.map(([href,en,arabic])=><Link key={href} href={`${p}${href}`} onClick={()=>setExpanded(null)}>{ar?arabic:en}<ArrowRight size={17}/></Link>)}</div></nav>}
 </header>;
}
