'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {ArrowUpRight,BookOpen,Check,FilePlus2,RefreshCw,Send,ShieldCheck,Sparkles} from 'lucide-react';
import {leadersClient} from '@/lib/leaders/client';
import {characterById} from '@/lib/leaders/characters';
import {CharacterPortrait} from './characters';
import {sourceCatalog,type EditorialDraft,type EditorialItem,type EditorialState} from '@/lib/leaders/editorial/schema';
import type {Locale} from '@/lib/leaders/types';
import styles from './editorial-room.module.css';
const labels:Record<EditorialState,[string,string]>={inbox:['مصدر جديد','New source'],generating:['تجهيز المسودة','Drafting'],draft:['مسودة','Draft'],review:['قيد المراجعة','In review'],approved:['معتمد','Approved'],rejected:['مستبعد','Rejected'],handed_off:['في الاستوديو','In studio']};
const errors:Record<string,[string,string]>={MODEL_NOT_CONFIGURED:['التوليد ينتظر ربط OpenRouter. يمكنك إعداد المسودة يدويًا.','Connect OpenRouter to generate. Manual drafting is available.'],ROOM_NOT_INSTALLED:['قاعدة بيانات الغرفة لم تُجهّز بعد.','Room database not installed.'],DUPLICATE_SOURCE:['المصدر موجود لهذه الشخصية. افتحه من القائمة.','This character already has this source. Open it from the queue.'],REVISION_CONFLICT:['المادة تغيّرت في جلسة أخرى. حدّث الغرفة.','Item changed in another session. Refresh the room.'],STATE_CONFLICT:['الخطوة غير متاحة في الحالة الحالية. حدّث الغرفة.','Action unavailable in this state. Refresh.'],GENERATION_BUSY:['التوليد جارٍ. أعد المحاولة بعد دقيقتين إذا انقطع.','Generation in progress. Retry after two minutes if interrupted.'],REVIEW_REQUIRED:['راجع الدليل واحفظ المسودة، وأضف سبب قرار المراجعة.','Check the evidence, save the draft and add your review rationale.'],INVALID_INPUT:['أكمل الحقول. النص يحتاج 50 حرفًا والدليل 100 حرف على الأقل.','Complete the fields. Body needs 50 characters; excerpt needs 100.'],EVIDENCE_MISMATCH:['الاقتباس غير مطابق للمصدر. انسخ المقتطف بدقة.','Quote does not match the source. Copy the exact passage.'],SIGN_IN_REQUIRED:['انتهت الجلسة. أعد الدخول للاستوديو.','Session expired. Sign in again.'],EDITOR_REQUIRED:['الحساب لا يملك صلاحية الغرفة.','Editor access required.'],SOURCE_UNAVAILABLE:['تعذرت قراءة الرابط. الصق المقتطف يدويًا.','Could not read the source. Paste its excerpt manually.'],MODEL_ACCESS_FAILED:['راجع اتصال حساب OpenRouter.','Check OpenRouter access.'],MODEL_CREDIT_REQUIRED:['راجع رصيد حساب النموذج.','Check model account credit.'],MODEL_RATE_LIMITED:['النموذج مشغول. حاول لاحقًا.','Model rate limited. Try later.'],MODEL_OUTPUT_INVALID:['المسودة لم تجتز فحص البنية. حاول مجددًا.','Generated draft failed validation. Retry.']};
const empty:EditorialDraft={title:'',body:'',title_en:'',body_en:'',why_it_matters:'',next_step:'',claims:[{claim:'',evidence_quote:''}],limitations:['']};
export default function EditorialRoom({locale}:{locale:Locale}){
 const ar=locale==='ar',base=ar?'/ar':'';const t=(a:string,b:string)=>ar?a:b;
 const [items,setItems]=useState<EditorialItem[]>([]),[id,setId]=useState<string|null>(null),[character,setCharacter]=useState<'tiko'|'labo'>('tiko'),[filter,setFilter]=useState('all');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[adding,setAdding]=useState(false),[dirty,setDirty]=useState(false);
 const [generation,setGeneration]=useState<{configured:boolean;model:string|null}>({configured:false,model:null});
 const [draft,setDraft]=useState<EditorialDraft>(empty),[checked,setChecked]=useState(false),[note,setNote]=useState('');
 const [source,setSource]=useState({source_url:'',source_label:'',source_title:'',source_excerpt:''});
 const current=items.find(i=>i.id===id),identity=characterById(character)!;
 const msg=useCallback((code:string)=>errors[code]?.[locale==='ar'?0:1]||(locale==='ar'?'تعذّر إتمام العملية. أعد المحاولة.':'Could not complete the action. Retry.'),[locale]);
 const api=useCallback(async(path='',method='GET',body?:unknown)=>{const {data:{session}}=await leadersClient().auth.getSession();if(!session)throw new Error('SIGN_IN_REQUIRED');const response=await fetch(`/api/leaders/editorial${path}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'REQUEST_FAILED');return data;},[]);
 const reload=useCallback(async()=>{setLoading(true);try{const data=await api();setItems(data.items);setGeneration(data.generation);setError('');}catch(e){setError(msg(e instanceof Error?e.message:''));}finally{setLoading(false);}},[api,msg]);
 useEffect(()=>{let alive=true;void api().then(data=>{if(alive){setItems(data.items);setGeneration(data.generation);}}).catch(e=>{if(alive)setError(msg(e instanceof Error?e.message:''));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[api,msg]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function leave(){return !dirty||window.confirm(t('ترك التغييرات غير المحفوظة؟','Discard unsaved changes?'));}
 function accept(item:EditorialItem){setItems(old=>[item,...old.filter(x=>x.id!==item.id)]);setId(item.id);setDraft(item.draft||{...empty,title:item.source_title});setChecked(item.source_checked);setNote(item.review_note||'');setDirty(false);setAdding(false);setCharacter(item.character_id);setFilter('all');}
 async function run(task:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(msg(e instanceof Error?e.message:''));}finally{setBusy(false);}}
 async function create(e:FormEvent){e.preventDefault();await run(async()=>{const data=await api('','POST',{...source,character_id:character});accept(data.item);setSource({source_url:'',source_label:'',source_title:'',source_excerpt:''});setNotice(t('حُفظ المصدر في الغرفة الخاصة.','Source saved privately.'));});}
 async function action(name:string){if(!current)return;if(name!=='save'&&dirty){setError(t('احفظ تعديلاتك أولًا.','Save your edits first.'));return;}await run(async()=>{const data=await api(`/${current.id}`,'PATCH',{action:name,revision:current.revision,...(name==='save'?{draft,source_checked:checked}:{}),...(['approve','reject'].includes(name)?{note}:{})});accept(data.item);setNotice(name==='handoff'?t('أُرسلت مسودة للاستوديو. لم تُنشر للجمهور.','Draft sent to the studio. It is not public.'):t('تم حفظ الخطوة.','Step saved.'));});}
 function change<K extends keyof EditorialDraft>(key:K,value:EditorialDraft[K]){setDraft(d=>({...d,[key]:value}));setDirty(true);}
 const editable=current&&['inbox','draft','review','approved','rejected'].includes(current.status);
 return <div className={styles.room}>
 <section className={styles.hero}><div><span className={styles.eyebrow}>{t('غرفة الشخصيات · تجربة التشغيل الأولى','CHARACTER ROOM · FIRST OPERATING PILOT')}</span><h1>{t('من المصدر إلى فكرة تستحق النشر.','From source to an idea worth publishing.')}</h1><p>{t('مساحة تيكو ولابو للبحث والكتابة والمراجعة. كل مسودة تبدأ بدليل، وتنتهي بقرار واضح.','Tiko and Labo’s space for research, writing and review. Every draft starts with evidence and ends with a clear decision.')}</p></div><span className={styles.private}><ShieldCheck size={16}/>{t('خاص بالمحرّرين','Editors only')}</span></section>
 <div className={styles.toolbar}><div className={styles.characters}>{(['tiko','labo'] as const).map(key=>{const c=characterById(key)!;return <button key={key} disabled={busy} aria-pressed={character===key} onClick={()=>{if(leave()){setCharacter(key);setId(null);setDirty(false);setAdding(false);}}}><CharacterPortrait character={c} size={44}/><span><strong>{c.name[locale]}</strong><small>{c.sector[locale]}</small></span></button>;})}</div><button className={styles.secondary} disabled={busy||loading} onClick={()=>{if(leave()){setId(null);setDirty(false);void reload();}}}><RefreshCw size={16}/>{t('تحديث','Refresh')}</button></div>
 <div className={styles.connection}><span className={generation.configured?styles.connected:styles.pending}/><strong>{generation.configured?t('إعدادات النموذج متاحة','Model settings available'):t('التوليد الآلي ينتظر الربط','AI drafting awaits connection')}</strong><span>{generation.model||t('يمكنك إعداد المسودات يدويًا الآن.','You can draft manually now.')}</span>{!generation.configured&&<details><summary>{t('إعداد الاتصال','Connection setup')}</summary><p>{t('أضف OPENROUTER_API_KEY وLEADERS_EDITORIAL_MODEL إلى متغيرات الخادم في Vercel ثم أعد النشر. لا تضع المفاتيح هنا.','Set OPENROUTER_API_KEY and LEADERS_EDITORIAL_MODEL as Vercel server variables and redeploy. Do not paste keys here.')}</p></details>}</div>
 {error&&<div className={styles.error} role="alert">{error}</div>}{notice&&<div className={styles.notice} role="status">{notice}</div>}{busy&&<p role="status" className={styles.busy}>{t('جاري تنفيذ الخطوة…','Working…')}</p>}
 <div className={styles.layout}><aside className={styles.queue}><h2>{t('طاولة العمل','Work queue')} <small>{items.filter(i=>i.character_id===character).length}</small></h2><button className={styles.primary} disabled={busy} onClick={()=>{if(leave()){setAdding(true);setId(null);setDirty(false);}}}><FilePlus2 size={17}/>{t('إضافة مصدر','Add source')}</button><label>{t('الحالة','Status')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('كل المواد','All items')}</option>{Object.entries(labels).map(([key,l])=><option key={key} value={key}>{l[ar?0:1]}</option>)}</select></label>{loading?<p>{t('جاري التحميل…','Loading…')}</p>:items.filter(i=>i.character_id===character&&(filter==='all'||i.status===filter)).map(item=><button className={styles.queueItem} key={item.id} disabled={busy} aria-pressed={id===item.id} onClick={()=>{if(leave())accept(item);}}><span className={styles.badge} data-state={item.status}>{labels[item.status][ar?0:1]}</span><strong>{item.draft?.title||item.source_title}</strong><small>{item.source_label}</small></button>)}{!loading&&!items.some(i=>i.character_id===character&&(filter==='all'||i.status===filter))&&<p className={styles.muted}>{t('لا توجد مواد في هذه القائمة.','No items in this queue.')}</p>}</aside>
 <section className={styles.workspace} aria-label={t('إعداد المادة','Editorial workspace')}>
 {adding?<><div className={styles.panelHead}><h2>{t('ابدأ من المصدر','Start with the source')}</h2><span>{identity.name[locale]}</span></div><div className={styles.catalog}><strong>{t('مصادر مقترحة للتجربة','Sources for the pilot')}</strong>{sourceCatalog.filter(s=>s.character_id===character).map(s=><div key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.label} · {s.title}<ArrowUpRight size={14}/></a><button className={styles.secondary} disabled={busy} onClick={()=>{if(leave())void run(async()=>{const data=await api('/sources','POST',{id:s.id});accept(data.item);setNotice(t('جُلب النص. راجعه قبل كتابة المسودة.','Text imported. Review it before drafting.'));});}}><BookOpen size={15}/>{t('جلب المصدر','Import')}</button></div>)}</div><form className={styles.form} onSubmit={create}><fieldset disabled={busy}><legend>{t('أو أضف مصدرًا بنفسك','Or add your own source')}</legend>{(['source_url','source_label','source_title'] as const).map((key,index)=><label key={key}>{[t('رابط المصدر','Source URL'),t('الجهة الناشرة','Publisher'),t('عنوان المادة الأصلية','Original title')][index]}<input required type={key==='source_url'?'url':'text'} value={source[key]} maxLength={key==='source_url'?2000:key==='source_label'?120:180} onChange={e=>{setSource(s=>({...s,[key]:e.target.value}));setDirty(true);}}/></label>)}<label>{t('مقتطف الدليل','Evidence excerpt')}<textarea required minLength={100} maxLength={16000} rows={8} value={source.source_excerpt} onChange={e=>{setSource(s=>({...s,source_excerpt:e.target.value}));setDirty(true);}}/><small>{t('الصق الجزء الذي ستعتمد عليه. حفظ الرابط لا يعني التحقق من محتواه.','Paste the relevant passage. Saving a link does not verify its content.')}</small></label><button className={styles.primary}><Check size={17}/>{t('حفظ المصدر','Save source')}</button></fieldset></form></>:current?<>
 <div className={styles.panelHead}><div><span className={styles.badge} data-state={current.status}>{labels[current.status][ar?0:1]}</span><h2>{current.source_title}</h2></div><a href={current.source_url} target="_blank" rel="noreferrer">{current.source_label}<ArrowUpRight size={16}/></a></div><div className={styles.steps}>{t('١ المصدر  ←  ٢ المسودة  ←  ٣ المراجعة  ←  ٤ الاستوديو','1 Source → 2 Draft → 3 Review → 4 Studio')}</div><details className={styles.evidence}><summary><BookOpen size={17}/>{t('اقرأ الدليل الأصلي','Read the source evidence')} <small>{current.source_method==='fetched'?t('جُلب من الرابط','Fetched from URL'):t('أُدخل يدويًا','Entered manually')}</small></summary><p dir="auto">{current.source_excerpt}</p></details>{current.last_error&&<p className={styles.error}>{msg(current.last_error)}</p>}
 {current.status==='handed_off'?<div className={styles.welcome}><ShieldCheck size={38}/><h3>{t('المسودة في استوديو المحتوى','Draft in the content studio')}</h3><p>{t('تنتظر المعاينة وقرار النشر.','Awaiting preview and a publishing decision.')}</p><Link className={styles.primary} href={`${base}/insights/studio?edit=${current.post_id}`}>{t('فتح المسودة في الاستوديو','Open draft in studio')}</Link></div>:<>
 <div className={styles.draftTop}><h3>{t('صياغة الفكرة','Shape the idea')}</h3><button className={styles.secondary} disabled={busy||!generation.configured||!['inbox','draft','rejected','generating'].includes(current.status)} onClick={()=>{if(!leave())return;void run(async()=>{try{const data=await api(`/${current.id}`,'POST',{revision:current.revision});accept(data.item);setNotice(t('راجع المسودة؛ مطابقة الاقتباس لا تثبت صحة الاستنتاج.','Review the draft; matching quotes does not prove conclusions.'));}finally{await reload();}});}}><Sparkles size={16}/>{t('تجهيز مسودة بالذكاء الاصطناعي','Draft with AI')}</button></div>{current.status==='generating'&&<p className={styles.muted}>{t('التوليد جارٍ. حدّث الغرفة لرؤية النتيجة؛ أعد المحاولة بعد دقيقتين إذا انقطع.','Drafting. Refresh for results; retry after two minutes if interrupted.')}</p>}
 <form className={styles.form} onSubmit={e=>{e.preventDefault();void action('save');}}><fieldset disabled={busy||!editable}>
 <label>{t('العنوان العربي','Arabic title')}<input required value={draft.title} maxLength={180} onChange={e=>change('title',e.target.value)}/></label>
 {([{key:'body',ar:'نص المنشور',en:'Post body',min:50,max:5000,rows:8},{key:'why_it_matters',ar:'لماذا يهم القائد؟',en:'Why does it matter?',min:15,max:1200,rows:3},{key:'next_step',ar:'خطوة عملية مقترحة',en:'Suggested next step',min:10,max:1000,rows:3}] as const).map(f=><label key={f.key}>{f[locale]}<textarea required value={draft[f.key]} minLength={f.min} maxLength={f.max} rows={f.rows} onChange={e=>change(f.key,e.target.value)}/></label>)}
 <details><summary>{t('النسخة الإنجليزية','English version')}</summary><label>Title<input dir="ltr" value={draft.title_en} maxLength={180} onChange={e=>change('title_en',e.target.value)}/></label><label>Body<textarea dir="ltr" rows={5} value={draft.body_en} maxLength={5000} onChange={e=>change('body_en',e.target.value)}/></label></details>
 <div className={styles.claims}><h3>{t('ما الدليل على ما نقوله؟','What supports our claims?')}</h3>{draft.claims.map((c,i)=><div className={styles.claim} key={i}><label>{t('الادعاء','Claim')} {i+1}<textarea required rows={2} minLength={5} maxLength={700} value={c.claim} onChange={e=>change('claims',draft.claims.map((v,n)=>n===i?{...v,claim:e.target.value}:v))}/></label><label>{t('اقتباس قصير مطابق للمصدر','Short exact quote from the source')}<textarea required dir="auto" rows={2} minLength={10} maxLength={700} value={c.evidence_quote} onChange={e=>change('claims',draft.claims.map((v,n)=>n===i?{...v,evidence_quote:e.target.value}:v))}/></label>{draft.claims.length>1&&<button type="button" className={styles.secondary} onClick={()=>change('claims',draft.claims.filter((_,n)=>n!==i))}>{t('حذف الادعاء','Remove claim')}</button>}</div>)}{draft.claims.length<5&&<button type="button" className={styles.secondary} onClick={()=>change('claims',[...draft.claims,{claim:'',evidence_quote:''}])}>{t('إضافة ادعاء ودليل','Add claim and evidence')}</button>}</div>
 <label>{t('حدود الدليل وما لم نتأكد منه','Limitations and unknowns')}<textarea required minLength={5} maxLength={3500} rows={3} value={draft.limitations.join('\n')} onChange={e=>change('limitations',e.target.value.split('\n'))}/></label><label className={styles.checkbox}><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setDirty(true);}}/><span>{t('راجعت المصدر والادعاءات وحدود الاستنتاج، وميّزت رأينا عن كلام المصدر.','I checked the source, claims and limitations and separated interpretation from source statements.')}</span></label><button className={styles.primary}><Check size={17}/>{t('حفظ المسودة','Save draft')}{dirty?' •':''}</button></fieldset></form>
 <div className={styles.review}><h3>{t('قرار المراجعة','Review decision')}</h3><p className={styles.muted}>{t('أي تعديل وحفظ للنص يعيده للمسودة ويُلغي الاعتماد السابق.','Editing and saving returns the item to draft and clears approval.')}</p><label>{t('سبب القرار أو ملاحظات المراجع','Review rationale or feedback')}<textarea rows={3} value={note} disabled={busy} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><div className={styles.actions}>{current.status==='draft'&&<button className={styles.primary} disabled={busy||dirty||!current.source_checked} onClick={()=>void action('request_review')}><Send size={16}/>{t('إرسال للمراجعة','Send for review')}</button>}{current.status==='review'&&<button className={styles.primary} disabled={busy||dirty||note.trim().length<10} onClick={()=>void action('approve')}><ShieldCheck size={17}/>{t('اعتماد المسودة','Approve draft')}</button>}{current.status==='approved'&&<button className={styles.primary} disabled={busy||dirty} onClick={()=>void action('handoff')}>{t('إرسال كمسودة للاستوديو','Send draft to studio')}</button>}{['inbox','draft','review','approved'].includes(current.status)&&<button className={styles.secondary} disabled={busy||dirty||note.trim().length<10} onClick={()=>void action('reject')}>{t('استبعاد مع السبب','Reject with rationale')}</button>}{['review','approved','rejected'].includes(current.status)&&<button className={styles.secondary} disabled={busy||dirty} onClick={()=>void action('reopen')}>{t('إعادة للعمل','Return to drafting')}</button>}</div></div></>}
 <details className={styles.history}><summary>{t('سجل الخطوات','Step history')} · {current.history.length}</summary>{current.history.slice(-20).reverse().map((h,i)=><p key={i}><code>{h.action}</code><time>{new Date(h.at).toLocaleString(ar?'ar-EG':'en-GB')}</time></p>)}{current.model&&<p>{t('النموذج','Model')}: {current.model}</p>}</details>
 </>:<div className={styles.welcome}><CharacterPortrait character={identity} size={110}/><span className={styles.eyebrow}>{identity.name[locale]}</span><h2>{t('ما الفكرة التي تستحق وقت القائد؟','Which idea deserves a leader’s time?')}</h2><p>{t('اختر مادة من طاولة العمل، أو أضف مصدرًا جديدًا. ستبقى المادة هنا حتى تراجعها وتعتمدها.','Choose an item or add a source. It stays here until reviewed and approved.')}</p><button className={styles.primary} disabled={busy} onClick={()=>setAdding(true)}><FilePlus2 size={18}/>{t('إضافة أول مصدر','Add a source')}</button></div>}
 </section></div></div>;
}
