'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Bookmark,Check,ChevronLeft,ChevronRight,Clapperboard,Compass,Heart,Home,Plus,Search,Send,Sparkles,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {LeaderPost,Locale,Topic,isVisible,postText,safeLink,topics} from '@/lib/leaders/types';
import {seedPosts,seedStories} from '@/lib/leaders/seed';
import {leadersClient,loadPosts,withMedia} from '@/lib/leaders/client';
import {PostMedia} from './media';
import {StoryPlayer} from './story-player';
import styles from './leaders.module.css';
type View='feed'|'reels'|'saved'|'explore';
function readList(key:string):string[]{try {const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a.filter(v=>typeof v==='string'):[];}catch{return [];}}
function PostCard({post,locale,saved,liked,onSave,onLike,onShare,onOpen,compact=false,paused=false}:{post:LeaderPost;locale:Locale;saved:boolean;liked:boolean;onSave:()=>void;onLike:()=>void;onShare:()=>void;onOpen:()=>void;compact?:boolean;paused?:boolean}) {
 const ar=locale==='ar';const [expanded,setExpanded]=useState(false);const t=postText(post,locale);const source=safeLink(post.source_url);const topic=topics.find(i=>i.id===post.topic);
 return <article className={`${styles.post} ${compact?styles.reelPost:''}`} id={`post-${post.id}`}>
  <header className={styles.postHeader}><span className={styles.avatar}><Image src="/visionseek-symbol-color.png" width={34} height={34} alt=""/></span><div><strong>VisionSeek <Check size={13}/></strong><span>{ar?'فكرة للقادة':'A thought for leaders'} · {topic?.[locale]}</span></div>{post.featured && <span className={styles.featured}><Sparkles size={13}/>{ar?'مختار':'Selected'}</span>}</header>
  {post.media_url ? <div className={styles.visual}><PostMedia post={post} locale={locale} immersive={compact} paused={paused}/>{post.media_type?.startsWith('video/')?<span className={styles.videoTag}><Clapperboard size={14}/>{ar?'فيديو قصير':'Short video'}</span>:<button className={styles.imageTitle} onClick={onOpen}><span>{topic?.[locale]}</span><h2>{t.title}</h2><ArrowUpRight size={22}/></button>}</div> : <button className={`${styles.quoteCard} ${styles[post.topic]}`} onClick={onOpen}><span>{topic?.[locale]}</span><h2>{t.title}</h2><div><span>VISIONSEEK</span><ArrowUpRight size={23}/></div></button>}
  <div className={styles.postActions}><button aria-label={liked?(ar?'إلغاء الإعجاب':'Unlike'):(ar?'أعجبني':'Like')} aria-pressed={liked} className={liked?styles.liked:''} onClick={onLike}><Heart fill={liked?'currentColor':'none'}/></button><button aria-label={ar?'مشاركة المنشور':'Share post'} onClick={onShare}><Send/></button><button className={`${styles.saveButton} ${saved?styles.saved:''}`} aria-label={saved?(ar?'إزالة من المحفوظات':'Remove bookmark'):(ar?'حفظ المنشور':'Save post')} aria-pressed={saved} onClick={onSave}><Bookmark fill={saved?'currentColor':'none'}/></button></div>
  <div className={styles.postCaption}>{post.media_type?.startsWith('video/') && <h2>{t.title}</h2>}<p className={expanded?undefined:styles.captionClamp}>{t.body}</p>{t.body.length>140 && <button className={styles.textButton} onClick={()=>setExpanded(!expanded)}>{expanded?(ar?'عرض أقل':'Show less'):(ar?'أكمل الفكرة':'Read more')}</button>}{source && <a className={styles.source} href={locale==='en'&&source.startsWith('/ar/')?source.slice(3):source} target={source.startsWith('https:')?'_blank':undefined} rel="noopener noreferrer">{post.source_label|| (ar?'المصدر':'Source')} <ArrowUpRight size={14}/></a>}<small>{ar?'من تحرير VisionSeek':'VisionSeek editorial'}{post.published_at && <> · <time dateTime={post.published_at}>{new Intl.DateTimeFormat(ar?'ar':'en',{day:'numeric',month:'short',timeZone:'Asia/Seoul'}).format(new Date(post.published_at))}</time></>}</small></div>
 </article>;
}
export default function LeadersFeed({locale}:{locale:Locale}) {
 const ar=locale==='ar',base=ar?'/ar':'';const [view,setView]=useState<View>('feed');const [topic,setTopic]=useState<Topic|'all'>('all');const [query,setQuery]=useState('');const [live,setLive]=useState<LeaderPost[]>([]);const [connected,setConnected]=useState(false);const [saved,setSaved]=useState<string[]>([]);const [liked,setLiked]=useState<string[]>([]);const [seen,setSeen]=useState<string[]>([]);const [story,setStory]=useState(-1);const [detail,setDetail]=useState<LeaderPost|null>(null);const [notice,setNotice]=useState('');const [loadError,setLoadError]=useState(false);const [busy,setBusy]=useState(true);const [hasMore,setHasMore]=useState(false);const [cursor,setCursor]=useState<string|undefined>();const [now,setNow]=useState(()=>Date.now());
 const refresh=useCallback(async()=>{setBusy(true);try{const rows=await loadPosts();setLive(rows);setConnected(true);setCursor(rows.at(-1)?.created_at);setHasMore(rows.length===24);setLoadError(false);}catch{setLoadError(true);}finally{setBusy(false);}},[]);
 // Hydrate browser-only preferences after the server render.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setSaved(readList('vs-leaders-saved'));setLiked(readList('vs-leaders-liked'));setSeen(readList('vs-leaders-seen'));void refresh();const interval=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(interval);},[refresh]);
 useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timeout);},[notice]);
 const allPosts=useMemo(()=>(connected?live:[...seedPosts,...seedStories]).filter(p=>isVisible(p,now)), [live,now,connected]);
 const stories=allPosts.filter(p=>p.kind==='story');const posts=allPosts.filter(p=>p.kind!=='story');
 useEffect(()=>{let ignore=false;const params=new URLSearchParams(window.location.search);const id=params.get('post');if(!id)return;async function openShared(){try{const {data,error}=await leadersClient().from('leaders_posts').select('*').eq('id',id).eq('status','published').maybeSingle();if(error||!data||!isVisible(data as LeaderPost))return;const [p]=await withMedia([data as LeaderPost]);if(!ignore)setDetail(p);}catch{}}void openShared();return()=>{ignore=true;};},[]);
 const filtered=posts.filter(p=> (view!=='saved'||saved.includes(p.id)) && (view!=='reels'||p.kind==='video') && (topic==='all'||p.topic===topic) && (!query||`${postText(p,locale).title} ${postText(p,locale).body}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())));
 function toggle(list:string[],setter:(v:string[])=>void,key:string,id:string){const next=list.includes(id)?list.filter(v=>v!==id):[id,...list];setter(next);try{localStorage.setItem(key,JSON.stringify(next));}catch{setNotice(ar?'تعذر الحفظ على هذا الجهاز.':'Could not save on this device.');}}
 async function share(post:LeaderPost){const url=`${window.location.origin}${base}/insights?post=${encodeURIComponent(post.id)}`;try{if(navigator.share)await navigator.share({title:postText(post,locale).title,url});else{await navigator.clipboard.writeText(url);setNotice(ar?'تم نسخ رابط المنشور':'Post link copied');}}catch(e){if(!(e instanceof Error && e.name==='AbortError')){setNotice(ar?'تعذرت المشاركة. انسخ الرابط من شريط العنوان بعد فتح المنشور.':'Sharing failed. Open the post and copy its address.');}}}
 function openDetail(p:LeaderPost){setDetail(p);const url=new URL(window.location.href);url.searchParams.set('post',p.id);window.history.replaceState(null,'',url);}
 const closeDetail=()=>{setDetail(null);const url=new URL(window.location.href);url.searchParams.delete('post');window.history.replaceState(null,'',url);};
 const openStory=useCallback((n:number)=>{setStory(n);const id=stories[n]?.id;if(id)setSeen(prev=>{const next=[...new Set([...prev,id])];try{localStorage.setItem('vs-leaders-seen',JSON.stringify(next));}catch{}return next;});},[stories]);
 const closeStory=useCallback(()=>setStory(-1),[]);
 async function more(){setBusy(true);try{const rows=await loadPosts({before:cursor});setLive(prev=>[...prev,...rows.filter(p=>!prev.some(v=>v.id===p.id))]);setCursor(rows.at(-1)?.created_at);setHasMore(rows.length===24);setLoadError(false);}catch{setLoadError(true);}finally{setBusy(false);}}
 const nav=[{id:'feed' as const,icon:Home,label:ar?'الرئيسية':'Home'},{id:'explore' as const,icon:Compass,label:ar?'اكتشف':'Explore'},{id:'reels' as const,icon:Clapperboard,label:ar?'فيديوهات':'Videos'},{id:'saved' as const,icon:Bookmark,label:ar?'المحفوظات':'Saved'}];
 return <main className={styles.app} dir={ar?'rtl':'ltr'} lang={locale}>
  <a href="#leaders-feed" className={styles.skip}>{ar?'انتقل إلى المحتوى':'Skip to content'}</a>
  <aside className={styles.sidebar}><Link href={`${base}/insights`} className={styles.brand}><span className={styles.brandSymbol}><Image src="/visionseek-symbol-color.png" width={42} height={42} alt="VisionSeek"/></span><span><strong>{ar?'بيت القادة':'Leaders House'}</strong><small>BY VISIONSEEK</small></span></Link><nav aria-label={ar?'تنقّل بيت القادة':'Leaders House navigation'}>{nav.map(n=><button key={n.id} className={view===n.id?styles.navActive:''} aria-current={view===n.id?'page':undefined} onClick={()=>{setView(n.id);setQuery('');setTopic('all');}}><n.icon/><span>{n.label}</span></button>)}<Link className={styles.createButton} href={`${base}/insights/studio`}><Plus/><span>{ar?'إنشاء محتوى':'Create'}</span></Link></nav><div className={styles.sidebarBottom}><Link href={base||'/'}>{ar?'العودة إلى VisionSeek':'Back to VisionSeek'}<ArrowUpRight size={16}/></Link><Link href={ar?'/insights':'/ar/insights'}>{ar?'English':'العربية'}</Link><p>{ar?'أفكار تستحق وقتك.':'Ideas worth your time.'}</p></div></aside>
  <div className={styles.mainColumn}><header className={styles.feedTop}><div><p>LEADERS HOUSE</p><h1>{view==='saved'?(ar?'أفكار تحتفظ بها':'Your saved ideas'):view==='reels'?(ar?'دقائق توسّع رؤيتك':'A wider perspective'):view==='explore'?(ar?'فكرتك القادمة هنا':'Your next idea'):ar?'خطوة أبعد. كل يوم.':'One step further. Every day.'}</h1></div><Link href={`${base}/insights/studio`} className={styles.mobileCreate} aria-label={ar?'إنشاء محتوى':'Create content'}><Plus/></Link><span className={styles.edition}>{ar?'لمن يصنعون القرار':'FOR DECISION MAKERS'}</span></header>
   {view==='feed' && <section className={styles.stories} aria-label={ar?'الستوريز والمختارات':'Stories and highlights'}><Link className={styles.storyItem} href={`${base}/insights/studio?type=story`}><span className={`${styles.storyRing} ${styles.addStory}`}><Plus/></span><span>{ar?'أضف ستوري':'Add story'}</span></Link>{stories.map((p,i)=><button className={styles.storyItem} key={p.id} onClick={()=>openStory(i)}><span className={`${styles.storyRing} ${seen.includes(p.id)?styles.seen:''}`}><span className={`${styles.storyThumb} ${styles[p.topic]}`}>{p.media_url&&!p.media_type?.startsWith('video/')?<Image src={p.media_url} alt="" fill sizes="72px" unoptimized={p.media_url.startsWith('https:')}/>:<Sparkles size={27}/>}</span></span><span>{topics.find(t=>t.id===p.topic)?.[locale]}</span></button>)}</section>}
   {(view==='explore'||query) && <label className={styles.search}><Search size={19}/><input aria-label={ar?'ابحث في الأفكار':'Search ideas'} placeholder={ar?'فكرة، قرار، أو تحدٍّ يشغلك…':'An idea, a decision, a challenge…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label={ar?'مسح البحث':'Clear search'}><X size={16}/></button>}</label>}
   <div className={styles.filters} aria-label={ar?'الموضوعات':'Topics'}><button className={topic==='all'?styles.filterActive:''} onClick={()=>setTopic('all')}>{ar?'الكل':'All'}</button>{topics.map(t=><button className={topic===t.id?styles.filterActive:''} key={t.id} onClick={()=>setTopic(t.id)}>{t[locale]}</button>)}</div>
   <section id="leaders-feed" className={styles.feed} aria-busy={busy} aria-label={ar?'المنشورات':'Posts'}>{view==='saved'&&<p className={styles.savedHint}>{ar?'محفوظاتك خاصة بهذا المتصفح.':'Your saved ideas stay in this browser.'}</p>}{loadError&&<div className={styles.connectionNotice}><span>{ar?'تعذر جلب أحدث المنشورات. يمكنك تصفح المختارات الحالية.':'Could not load the latest posts. The current selection is available.'}</span><button onClick={()=>void refresh()}>{ar?'إعادة المحاولة':'Retry'}</button></div>}
    {!filtered.length&&!busy && <div className={styles.empty}><span>{view==='reels'?<Clapperboard size={32}/>:view==='saved'?<Bookmark size={32}/>:<Search size={32}/>}</span><h2>{view==='reels'?(ar?'مساحة لفكرة تستحق المشاهدة':'Room for an idea worth watching'):view==='saved'?(ar?'احتفظ بما تريد العودة إليه':'Keep ideas to return to'):(ar?'جرّب موضوعًا آخر':'Try another topic')}</h2><p>{view==='reels'?(ar?'ستظهر الفيديوهات القصيرة هنا فور نشرها.':'Short videos will appear here as soon as they are published.'):view==='saved'?(ar?'اضغط علامة الحفظ تحت أي منشور لتجده هنا.':'Tap the bookmark under a post to find it here.'):(ar?'لا توجد منشورات تطابق هذا البحث.':'No posts match this search.')}</p>{view==='reels'?<Link href={`${base}/insights/studio?type=video`}>{ar?'انشر أول فيديو':'Publish the first video'}<Plus size={16}/></Link>:<button onClick={()=>{setView('feed');setTopic('all');setQuery('');}}>{ar?'تصفّح الأفكار':'Browse ideas'}</button>}</div>}
    {filtered.map(p=><PostCard key={p.id} post={p} locale={locale} compact={view==='reels'} paused={story>=0||!!detail} saved={saved.includes(p.id)} liked={liked.includes(p.id)} onSave={()=>toggle(saved,setSaved,'vs-leaders-saved',p.id)} onLike={()=>toggle(liked,setLiked,'vs-leaders-liked',p.id)} onShare={()=>void share(p)} onOpen={()=>openDetail(p)}/>)}
    {busy&&<div className={styles.loading} role="status">{ar?'جاري تحميل المحتوى…':'Loading…'}</div>}{hasMore&&<button className={styles.loadMore} onClick={()=>void more()} disabled={busy}>{ar?'المزيد من الأفكار':'More ideas'}</button>}{filtered.length>0&&!hasMore&&!busy&&<div className={styles.feedEnd}><Check size={20}/><h3>{ar?'أصبحت أقرب لفكرتك القادمة.':'You’re one idea closer.'}</h3><p>{ar?'اختر فكرة واحدة وجرّبها مع فريقك.':'Choose one idea to try with your team.'}</p></div>}
   </section>
  </div>
  <aside className={styles.contextColumn}><div className={styles.authorCard}><Image src="/ahmed-abdelalim.jpg" alt={ar?'د. أحمد عبد العليم':'Dr. Ahmed Abdelalim'} width={52} height={52}/><div><strong>{ar?'د. أحمد عبد العليم':'Dr. Ahmed Abdelalim'}</strong><span>{ar?'مؤسس VisionSeek':'Founder, VisionSeek'}</span></div></div><div className={styles.dailyQuestion}><span>{ar?'سؤال يستحق التوقف':'PAUSE ON THIS'}</span><h2>{ar?'ما الذي أصبح ممكنًا اليوم، وقد يسبقك به غيرك غدًا؟':'What became possible today that someone else could use to move ahead tomorrow?'}</h2><Link href={`${base}/start`}>{ar?'ابنِ قدرة معنا':'Build with us'}{ar?<ChevronLeft size={19}/>:<ChevronRight size={19}/>}</Link></div><div className={styles.topicList}><h3>{ar?'وسّع زاوية رؤيتك':'Widen your lens'}</h3>{topics.map((t,i)=><button key={t.id} onClick={()=>{setTopic(t.id);setView('feed');setQuery('');}}><span>0{i+1}</span><strong>{t[locale]}</strong><ArrowUpRight size={16}/></button>)}</div><div className={styles.smallLinks}><Link href={`${base}/about`}>{ar?'عن VisionSeek':'About'}</Link><Link href={`${base}/privacy`}>{ar?'الخصوصية':'Privacy'}</Link><Link href={`${base}/terms`}>{ar?'الشروط':'Terms'}</Link><span>© VisionSeek 2026</span></div></aside>
  <nav className={styles.mobileNav} aria-label={ar?'التنقل السريع':'Quick navigation'}>{nav.map(n=><button key={n.id} aria-label={n.label} className={view===n.id?styles.navActive:''} onClick={()=>{setView(n.id);setTopic('all');setQuery('');window.scrollTo({top:0,behavior:'smooth'});}}><n.icon/><span>{n.label}</span></button>)}<Link href={base||'/'} aria-label="VisionSeek"><Image src="/visionseek-symbol-color.png" width={25} height={25} alt=""/><span>VisionSeek</span></Link></nav>
  {notice&&<div className={styles.toast} role="status">{notice}</div>}
  {story>=0&&<StoryPlayer key={stories[story]?.id} posts={stories} index={story} onIndex={openStory} onClose={closeStory} locale={locale}/>}
  <Dialog open={!!detail} onOpenChange={v=>{if(!v)closeDetail();}}><DialogContent className={styles.postDialog} dir={ar?'rtl':'ltr'}><DialogTitle className="sr-only">{detail?postText(detail,locale).title:''}</DialogTitle><DialogDescription className="sr-only">{ar?'منشور من بيت القادة':'A post from Leaders House'}</DialogDescription>{detail&&<PostCard post={detail} locale={locale} saved={saved.includes(detail.id)} liked={liked.includes(detail.id)} onSave={()=>toggle(saved,setSaved,'vs-leaders-saved',detail.id)} onLike={()=>toggle(liked,setLiked,'vs-leaders-liked',detail.id)} onShare={()=>void share(detail)} onOpen={()=>{}}/>}</DialogContent></Dialog>
 </main>;
}
