'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Bookmark,Check,ChevronDown,Clapperboard,Compass,Heart,Home,MoreHorizontal,Play,Search,Send,SlidersHorizontal,FileText,ExternalLink,X} from 'lucide-react';
import {Dialog,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {LeaderPost,Locale,Topic,isVisible,postText,safeLink,topics} from '@/lib/leaders/types';
import {seedPosts} from '@/lib/leaders/seed';
import {editionAll,editionDate,editionPosts} from '@/lib/leaders/edition';
import {capabilityLink,collectionOptions,emptyPreferences,normalizePreferences,rankPosts,sortByNewest,setTopicPreference,toggleCollection,type CollectionId,type ReaderPreferences} from '@/lib/leaders/reader';
import {leadersClient,loadPosts,withMedia} from '@/lib/leaders/client';
import {PostMedia} from './media';
import {StoryPlayer} from './story-player';
import {ReelPlayer} from './reel-player';
import sharedStyles from './leaders.module.css';
import feedStyles from './feed.module.css';
const styles={...sharedStyles,...feedStyles};
import {StoryRail} from './story-rail';
import {ReaderDialogContent as DialogContent} from './reader-dialog';
type View='feed'|'reels'|'saved'|'explore';
const STORAGE='vs-leaders-reader-v1';
function readList(key:string):string[]{try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a.filter(v=>typeof v==='string'):[];}catch{return [];}}
function PostCard({post,locale,saved,liked,onSave,onLike,onShare,onOpen,onVideo,onOptions}:{post:LeaderPost;locale:Locale;saved:boolean;liked:boolean;paused:boolean;onSave:()=>void;onLike:()=>void;onShare:()=>void;onOpen:()=>void;onVideo:()=>void;onOptions:()=>void}){
 const ar=locale==='ar',t=postText(post,locale),source=safeLink(post.source_url),topic=topics.find(i=>i.id===post.topic),video=post.kind==='video';
 const cover=post.cover_url||(video?(locale==='en'?post.poster_url_en:post.poster_url)||post.poster_url:post.media_url);
 const paragraphs=t.body.split('\n\n');
 const relevant=paragraphs.find(p=>p.startsWith(ar?'ما يهم مؤسستك:':'Why it matters:'));
 const summary=(relevant||paragraphs[0]||'').replace(/^(ما يهم مؤسستك:|Why it matters:)\s*/,'');
 const date=post.published_at?new Intl.DateTimeFormat(ar?'ar':'en',{day:'numeric',month:'short',timeZone:'Asia/Seoul'}).format(new Date(post.published_at)):'';
 return <article className={styles.post} id={`post-${post.id}`}>
  <header className={styles.postHeader}>
   <span className={styles.avatar}><Image src="/visionseek-symbol-color.png" width={30} height={30} alt=""/></span>
   <div className={styles.authorMeta}><strong>VisionSeek <span className={styles.editorialBadge}>{ar?'تحرير':'Editorial'}</span></strong><span>{topic?.[locale]}{date&&<> · <time dateTime={post.published_at!}>{date}</time></>}</span></div>
   <button className={styles.postMenu} aria-label={ar?'تفضيلات هذا الموضوع':'Topic preferences'} onClick={onOptions}><MoreHorizontal size={22}/></button>
  </header>
  <div className={styles.postCopy}>
   <h2><button className={styles.titleButton} onClick={video?onVideo:onOpen}>{t.title}</button></h2>
   {!video&&<><p className={styles.captionClamp}>{summary}</p><button className={styles.readBrief} onClick={onOpen}>{ar?'قراءة الفكرة':'Read the brief'}<ArrowUpRight size={15}/></button></>}
  </div>
  {cover?<button className={`${styles.visual} ${video?styles.videoVisual:''}`} onClick={video?onVideo:onOpen} aria-label={`${video?(ar?'شاهد الفيديو':'Watch video'):(ar?'اقرأ الفكرة':'Read brief')}: ${t.title}`}>
   <Image src={cover} alt="" fill sizes="(max-width:760px) 100vw,600px" unoptimized={cover.startsWith('https:')}/>
   {video&&<><span className={styles.videoShade}/><span className={styles.videoEntryPlay}><Play fill="currentColor" size={24}/></span><span className={styles.videoEntryHint}><Clapperboard size={16}/>{ar?'فيديو قصير':'Short video'}<span>{ar?'شاهد الفكرة':'Watch the idea'}</span></span></>}
  </button>:video?<button className={`${styles.visual} ${styles.videoFallback}`} onClick={onVideo}><Play size={30}/><span>{ar?'شاهد الفيديو':'Watch video'}</span></button>:null}
  {source&&<a className={styles.sourceLine} href={locale==='en'&&source.startsWith('/ar/')?source.slice(3):source} target={source.startsWith('https:')?'_blank':undefined} rel="noopener noreferrer"><FileText size={15}/><span>{post.source_label||(ar?'المصدر':'Source')}</span><ExternalLink size={13}/></a>}
  <div className={styles.postActions}>
   <button aria-label={liked?(ar?'إلغاء الإعجاب':'Unlike'):(ar?'أعجبني':'Like')} aria-pressed={liked} className={liked?styles.liked:''} onClick={onLike}><Heart size={20} fill={liked?'currentColor':'none'}/><span>{ar?'أعجبني':'Like'}</span></button>
   <button aria-label={ar?'حفظ في مجموعة':'Save to collection'} aria-pressed={saved} className={saved?styles.saved:''} onClick={onSave}><Bookmark size={20} fill={saved?'currentColor':'none'}/><span>{saved?(ar?'محفوظ':'Saved'):(ar?'حفظ':'Save')}</span></button>
   <button aria-label={ar?'مشاركة المنشور':'Share post'} onClick={onShare}><Send size={19}/><span>{ar?'مشاركة':'Share'}</span></button>
  </div>
 </article>;
}
export default function LeadersFeed({locale}:{locale:Locale}){
 const ar=locale==='ar',base=ar?'/ar':'';
 const [view,setView]=useState<View>('feed');const [topicsOpen,setTopicsOpen]=useState(false);const [order,setOrder]=useState<'for-you'|'latest'>('for-you');const [sharedPost,setSharedPost]=useState<LeaderPost|null>(null);const [topic,setTopic]=useState<Topic|'all'>('all');const [query,setQuery]=useState('');
 const [live,setLive]=useState<LeaderPost[]>([]);const [savedPosts,setSavedPosts]=useState<LeaderPost[]>([]);const [connected,setConnected]=useState(false);
 const [savedReload,setSavedReload]=useState(0);
 const [prefs,setPrefs]=useState<ReaderPreferences>(emptyPreferences);const [liked,setLiked]=useState<string[]>([]);const [seen,setSeen]=useState<string[]>([]);
 const [story,setStory]=useState(-1);const [reel,setReel]=useState<string|null>(null);const [detail,setDetail]=useState<LeaderPost|null>(null);
 const [savePost,setSavePost]=useState<LeaderPost|null>(null);const [optionsPost,setOptionsPost]=useState<LeaderPost|null>(null);const [settings,setSettings]=useState(false);const [collection,setCollection]=useState<CollectionId|'all'>('all');
 const [shareItem,setShareItem]=useState<{post:LeaderPost;url:string}|null>(null);const [notice,setNotice]=useState('');const [loadError,setLoadError]=useState(false);const [savedError,setSavedError]=useState(false);const [busy,setBusy]=useState(true);const [hasMore,setHasMore]=useState(false);const [cursor,setCursor]=useState<string>();const [now,setNow]=useState(()=>Date.now());
 const refresh=useCallback(async()=>{setBusy(true);try{const rows=await loadPosts();setLive(rows);setSavedPosts([]);setSavedReload(v=>v+1);setConnected(true);setCursor(rows.at(-1)?.created_at);setHasMore(rows.length===24);setLoadError(false);}catch{setLoadError(true);}finally{setBusy(false);}},[]);
 // Synchronize persisted browser state after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{let value:unknown;try{value=JSON.parse(localStorage.getItem(STORAGE)||'null');}catch{}setPrefs(normalizePreferences(value,readList('vs-leaders-saved')));setLiked(readList('vs-leaders-liked'));setSeen(readList('vs-leaders-seen'));try{if(localStorage.getItem('vs-leaders-order')==='latest')setOrder('latest');}catch{}void refresh();const interval=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(interval);},[refresh]);
 useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timeout);},[notice]);
 const allPosts=useMemo(()=>{const merged=[...(sharedPost?[sharedPost]:[]),...savedPosts,...editionAll,...(connected?live:seedPosts)];return [...new Map(merged.map(p=>[p.id,p])).values()].filter(p=>isVisible(p,now));},[live,now,connected,savedPosts,sharedPost]);
 const stories=allPosts.filter(p=>p.kind==='story');const posts=allPosts.filter(p=>p.kind!=='story');
 const savedKey=Object.keys(prefs.collections).sort().join(',');
 useEffect(()=>{let cancelled=false;const ids=savedKey.split(',').filter(id=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id));if(!ids.length)return;
  async function fetchSaved(){try{const chunks=[];for(let i=0;i<ids.length;i+=50)chunks.push(ids.slice(i,i+50));const rows=await Promise.all(chunks.map(async batch=>{const {data,error}=await leadersClient().from('leaders_posts').select('*').eq('status','published').in('id',batch);if(error)throw error;return data as LeaderPost[];}));const media=await withMedia(rows.flat());if(!cancelled){setSavedPosts(media.filter(p=>isVisible(p)));setSavedError(false);}}catch{if(!cancelled)setSavedError(true);}}
  void fetchSaved();return()=>{cancelled=true;};
 },[savedKey,savedReload]);
 // Hydrate a shared URL; the server has no browser location.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{let ignore=false;const id=new URLSearchParams(window.location.search).get('post');if(!id)return;const local=editionAll.find(p=>p.id===id);if(local){if(local.kind==='video')setReel(local.id);else setDetail(local);return;}
  async function openShared(){try{const {data,error}=await leadersClient().from('leaders_posts').select('*').eq('id',id).eq('status','published').maybeSingle();if(error||!data||!isVisible(data as LeaderPost))return;const [p]=await withMedia([data as LeaderPost]);if(!ignore){setSharedPost(p);if(p.kind==='video')setReel(p.id);else setDetail(p);}}catch{}}void openShared();return()=>{ignore=true;};
 },[]);
 const orderPosts=(items:LeaderPost[])=>order==='latest'?sortByNewest(items):rankPosts(items,prefs);
 const filtered=(view==='saved'?sortByNewest:orderPosts)(posts.filter(p=>(view!=='saved'||!!prefs.collections[p.id]?.length)&&(view!=='reels'||p.kind==='video')&&(topic==='all'||p.topic===topic)&&(view!=='saved'||collection==='all'||prefs.collections[p.id]?.includes(collection))&&(!query||`${postText(p,locale).title} ${postText(p,locale).body}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))));
 const videos=orderPosts(posts.filter(p=>p.kind==='video'&&!!p.media_url));
 const paused=story>=0||!!detail||!!reel||!!savePost||!!optionsPost||settings||!!shareItem;
 function persist(next:ReaderPreferences){setPrefs(next);try{localStorage.setItem(STORAGE,JSON.stringify(next));localStorage.setItem('vs-leaders-saved',JSON.stringify(Object.keys(next.collections)));}catch{setNotice(ar?'تعذر الحفظ على هذا الجهاز.':'Could not save on this device.');}}
 function prefer(t:Topic,choice:'more'|'less'|'neutral'){persist(setTopicPreference(prefs,t,choice));setOptionsPost(null);setNotice(ar?'تم تحديث ترتيب الموضوعات.':'Topic ranking updated.');}
 function like(id:string){const next=liked.includes(id)?liked.filter(x=>x!==id):[...liked,id];setLiked(next);try{localStorage.setItem('vs-leaders-liked',JSON.stringify(next));}catch{}}
 function selectOrder(next:'for-you'|'latest'){setOrder(next);try{localStorage.setItem('vs-leaders-order',next);}catch{}}
 function share(post:LeaderPost){setShareItem({post,url:`${window.location.origin}${base}/insights?post=${encodeURIComponent(post.id)}`});}
 async function copyShared(){if(!shareItem)return;try{await navigator.clipboard.writeText(shareItem.url);setNotice(ar?'تم نسخ رابط المنشور':'Post link copied');}catch{setNotice(ar?'حدّد الرابط وانسخه يدويًا.':'Select the link and copy it manually.');}}
 async function nativeShare(){if(!shareItem)return;try{await navigator.share({title:postText(shareItem.post,locale).title,url:shareItem.url});}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setNotice(ar?'يمكنك نسخ الرابط ومشاركته.':'You can copy and share the link.');}}

 function openDetail(p:LeaderPost){setDetail(p);const url=new URL(window.location.href);url.searchParams.set('post',p.id);window.history.replaceState(null,'',url);}
 function closeDetail(){setDetail(null);const url=new URL(window.location.href);url.searchParams.delete('post');window.history.replaceState(null,'',url);}
 function openStory(n:number){setStory(n);const id=stories[n]?.id;if(id){const next=[...new Set([...seen,id])];setSeen(next);try{localStorage.setItem('vs-leaders-seen',JSON.stringify(next));}catch{}}}
 async function more(){setBusy(true);try{const rows=await loadPosts({before:cursor});setLive(prev=>[...prev,...rows.filter(p=>!prev.some(v=>v.id===p.id))]);setCursor(rows.at(-1)?.created_at);setHasMore(rows.length===24);setLoadError(false);}catch{setLoadError(true);}finally{setBusy(false);}}
 function navigate(next:View){setView(next);setTopic('all');setTopicsOpen(next==='explore');setQuery('');window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 const nav=[{id:'feed' as const,icon:Home,label:ar?'الرئيسية':'Home'},{id:'explore' as const,icon:Compass,label:ar?'اكتشف':'Explore'},{id:'reels' as const,icon:Clapperboard,label:ar?'فيديوهات':'Videos'},{id:'saved' as const,icon:Bookmark,label:ar?'المحفوظات':'Saved'}];
 return <main className={styles.app} dir={ar?'rtl':'ltr'} lang={locale}>
  <a href="#leaders-feed" className={styles.skip}>{ar?'انتقل إلى المحتوى':'Skip to content'}</a>
  <aside className={styles.sidebar}><Link href={`${base}/insights`} className={styles.brand}><span className={styles.brandSymbol}><Image src="/visionseek-symbol-color.png" width={42} height={42} alt="VisionSeek"/></span><span><strong>{ar?'بيت القادة':'Leaders House'}</strong><small>BY VISIONSEEK</small></span></Link><nav aria-label={ar?'تنقّل بيت القادة':'Leaders House navigation'}>{nav.map(n=><button key={n.id} className={view===n.id?styles.navActive:''} aria-current={view===n.id?'page':undefined} onClick={()=>navigate(n.id)}><n.icon/><span>{n.label}</span></button>)}<button onClick={()=>setSettings(true)}><SlidersHorizontal/><span>{ar?'اهتماماتي':'My interests'}</span></button></nav><div className={styles.sidebarBottom}><Link href={base||'/'}>{ar?'العودة إلى VisionSeek':'Back to VisionSeek'}<ArrowUpRight size={16}/></Link><Link href={ar?'/insights':'/ar/insights'}>{ar?'English':'العربية'}</Link><p>{ar?'أفكار تستحق وقتك.':'Ideas worth your time.'}</p></div></aside>
  <div className={styles.mainColumn}>
   <header className={styles.mobileHeader}><Link href={`${base}/insights`} className={styles.mobileBrand}><Image src="/visionseek-symbol-color.png" width={32} height={32} alt=""/><strong>{ar?'بيت القادة':'Leaders House'}</strong></Link><div><Link href={ar?'/insights':'/ar/insights'} aria-label={ar?'Switch to English':'التبديل للعربية'}>{ar?'EN':'عربي'}</Link><button aria-label={ar?'ابحث في بيت القادة':'Search Leaders House'} onClick={()=>navigate('explore')}><Search size={21}/></button></div></header>
   <header className={`${styles.feedTop} ${view==='feed'?styles.homeIntro:''}`}><div><p>{ar?'بيت القادة · VISIONSEEK':'LEADERS HOUSE · VISIONSEEK'}</p><h1>{view==='saved'?(ar?'أفكار تتحول إلى خطوات':'Ideas to act on'):view==='reels'?(ar?'فكرة تستحق دقيقة':'A minute worth your time'):view==='explore'?(ar?'ما الذي يشغل مؤسستك؟':'What matters to your organization?'):ar?'اكتشف ما يستحق أن تبدأه.':'Discover what is worth starting.'}</h1></div><button className={styles.interestsButton} aria-label={ar?'تعديل اهتماماتي':'Edit my interests'} onClick={()=>setSettings(true)}><SlidersHorizontal size={20}/></button></header>
   {view==='feed'&&<>
    <StoryRail posts={stories} locale={locale} seen={seen} onOpen={openStory}/>

   </>}
   {view!=='saved'&&<div className={styles.orderBar} role="group" aria-label={ar?'ترتيب المنشورات':'Feed order'}><button aria-pressed={order==='for-you'} onClick={()=>selectOrder('for-you')}>{ar?'لك':'For you'}</button><button aria-pressed={order==='latest'} onClick={()=>selectOrder('latest')}>{ar?'الأحدث':'Latest'}</button><button className={styles.mobileTopicsToggle} aria-expanded={topicsOpen} aria-controls="reader-topics" onClick={()=>setTopicsOpen(!topicsOpen)}><SlidersHorizontal size={16}/>{topic==='all'?(ar?'الموضوعات':'Topics'):topics.find(t=>t.id===topic)?.[locale]}<ChevronDown size={15}/></button></div>}
   {(view==='explore'||view==='saved')&&<label className={styles.search}><Search size={19}/><input aria-label={ar?'ابحث في الأفكار':'Search ideas'} placeholder={ar?'فكرة، قرار، أو تحدٍّ يشغلك…':'An idea, decision or challenge…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label={ar?'مسح البحث':'Clear search'}><X size={16}/></button>}</label>}
   {view==='saved'?<div className={styles.filters} aria-label={ar?'مجموعات الحفظ':'Saved collections'}><button aria-pressed={collection==='all'} className={collection==='all'?styles.filterActive:''} onClick={()=>setCollection('all')}>{ar?'الكل':'All'}</button>{collectionOptions.map(c=><button aria-pressed={collection===c.id} className={collection===c.id?styles.filterActive:''} key={c.id} onClick={()=>setCollection(c.id)}>{c[locale]}</button>)}</div>:<div id="reader-topics" className={`${styles.filters} ${styles.topicFilters} ${topicsOpen?styles.topicsOpen:''}`} aria-label={ar?'الموضوعات':'Topics'}><button aria-pressed={topic==='all'} className={topic==='all'?styles.filterActive:''} onClick={()=>setTopic('all')}>{ar?'الكل':'All'}</button>{topics.map(t=><button aria-pressed={topic===t.id} className={topic===t.id?styles.filterActive:''} key={t.id} onClick={()=>setTopic(t.id)}>{t[locale]}</button>)}</div>}
   {view==='feed'&&order==='for-you'&&(prefs.interests.length>0||prefs.less.length>0)&&<p className={styles.rankingHint}>{ar?'الموضوعات التي اخترتها تظهر أولًا. يمكنك تغييرها في اهتماماتي.':'Your preferred topics appear first. Change them in My interests.'}</p>}
   <section id="leaders-feed" className={styles.feed} aria-busy={busy} aria-label={ar?'المنشورات':'Posts'}>
    {view==='saved'&&<p className={styles.savedHint}>{ar?'مجموعاتك محفوظة على هذا المتصفح. قد تختفي المواد المؤرشفة أو غير المتاحة.':'Collections stay in this browser. Archived or unavailable posts may disappear.'}</p>}
    {(loadError||(view==='saved'&&savedError))&&<div className={styles.connectionNotice}><span>{ar?'تعذر جلب بعض المنشورات. المختارات التحريرية متاحة.':'Some posts could not load. The editorial selection is available.'}</span><button onClick={()=>void refresh()}>{ar?'إعادة المحاولة':'Retry'}</button></div>}
    {!filtered.length&&!busy&&<div className={styles.empty}><Bookmark size={28}/><h2>{view==='saved'?(ar?'ابدأ بمجموعة لفكرتك القادمة':'Start a collection for your next idea'):(ar?'لا توجد نتائج في هذا الموضوع بعد':'No results for this topic yet')}</h2><p>{ar?'تصفح المختارات واحفظ ما يستحق العودة إليه.':'Browse the selection and save what is worth revisiting.'}</p><button onClick={()=>navigate('feed')}>{ar?'تصفح الأفكار':'Browse ideas'}</button></div>}
    {view==='reels'?<div className={styles.videoShelf}>{filtered.map(p=><button className={styles.videoTile} key={p.id} onClick={()=>setReel(p.id)}>{(p.cover_url||p.poster_url||p.media_type?.startsWith('image/'))&&<Image src={p.cover_url||(locale==='en'?p.poster_url_en:p.poster_url)||p.poster_url||p.media_url!} alt="" fill sizes="(max-width:760px) 50vw, 290px"/>}<span><Play size={26}/><strong>{postText(p,locale).title}</strong><small>{ar?'افتح واسحب بين المقاطع':'Open and swipe between clips'}</small></span></button>)}</div>:filtered.map(p=><PostCard key={p.id} post={p} locale={locale} paused={paused} saved={!!prefs.collections[p.id]?.length} liked={liked.includes(p.id)} onSave={()=>setSavePost(p)} onLike={()=>like(p.id)} onShare={()=>void share(p)} onOpen={()=>openDetail(p)} onVideo={()=>setReel(p.id)} onOptions={()=>setOptionsPost(p)}/>)}
    {busy&&<div className={styles.loading} role="status">{ar?'جاري تحميل المحتوى…':'Loading…'}</div>}{hasMore&&<button className={styles.loadMore} onClick={()=>void more()} disabled={busy}>{ar?'المزيد من الأفكار':'More ideas'}</button>}{filtered.length>0&&!hasMore&&!busy&&<div className={styles.feedEnd}><Check size={20}/><h3>{ar?'ما الفكرة التي ستأخذها إلى فريقك؟':'Which idea will you take to your team?'}</h3><p>{ar?'احفظها في مجموعة، أو شاركها لبدء النقاش.':'Save it to a collection or share it to start a conversation.'}</p></div>}
   </section>
  </div>
  <aside className={styles.contextColumn}><section className={styles.editorialPicks}><div className={styles.picksHeading}><span>{ar?'من اختيارنا':'THE EDITOR’S PICKS'}</span><time dateTime={editionDate}>{new Intl.DateTimeFormat(ar?'ar':'en',{day:'numeric',month:'long'}).format(new Date(editionDate))}</time></div>{editionPosts.map((p,i)=><button key={p.id} onClick={()=>openDetail(p)}><span>0{i+1}</span><strong>{postText(p,locale).title}</strong><ArrowUpRight size={15}/></button>)}</section><div className={styles.authorCard}><Image src="/ahmed-abdelalim.jpg" alt={ar?'د. أحمد عبد العليم':'Dr. Ahmed Abdelalim'} width={52} height={52}/><div><strong>{ar?'د. أحمد عبد العليم':'Dr. Ahmed Abdelalim'}</strong><span>{ar?'مؤسس VisionSeek':'Founder, VisionSeek'}</span></div></div><div className={styles.dailyQuestion}><span>{ar?'من الفكرة إلى القدرة':'FROM IDEA TO CAPABILITY'}</span><h2>{ar?'أي فرصة تستحق أن تتحرك مؤسستك نحوها؟':'Which opportunity deserves your organization’s next move?'}</h2><Link href={`${base}/start`}>{ar?'ابنِ قدرة معنا':'Build with us'}<ArrowUpRight size={18}/></Link></div><div className={styles.topicList}><h3>{ar?'وسّع زاوية رؤيتك':'Widen your lens'}</h3>{topics.map((t,i)=><button key={t.id} onClick={()=>{setTopic(t.id);setView('feed');setQuery('');}}><span>0{i+1}</span><strong>{t[locale]}</strong><ArrowUpRight size={16}/></button>)}</div><div className={styles.smallLinks}><Link href={`${base}/about`}>{ar?'عن VisionSeek':'About'}</Link><Link href={`${base}/privacy`}>{ar?'الخصوصية':'Privacy'}</Link><Link href={`${base}/terms`}>{ar?'الشروط':'Terms'}</Link><span>© VisionSeek 2026</span></div></aside>
  <nav className={styles.mobileNav} aria-label={ar?'التنقل السريع':'Quick navigation'}>{nav.map(n=><button key={n.id} aria-label={n.label} aria-current={view===n.id?'page':undefined} className={view===n.id?styles.navActive:''} onClick={()=>navigate(n.id)}><n.icon/><span>{n.label}</span></button>)}<button onClick={()=>setSettings(true)} aria-label={ar?'اهتماماتي':'My interests'}><SlidersHorizontal/><span>{ar?'اهتماماتي':'Interests'}</span></button></nav>
  {story>=0&&<StoryPlayer key={stories[story]?.id} posts={stories} index={story} onIndex={openStory} onClose={()=>setStory(-1)} locale={locale}/>}
  {reel&&videos.some(p=>p.id===reel)&&<ReelPlayer key={reel} posts={videos} start={Math.max(0,videos.findIndex(p=>p.id===reel))} locale={locale} savedIds={Object.keys(prefs.collections)} blocked={!!detail||!!savePost||!!shareItem} onClose={()=>setReel(null)} onSave={setSavePost} onShare={p=>void share(p)} onRead={openDetail}/>}
  <Dialog open={!!detail} onOpenChange={open=>{if(!open)closeDetail();}}><DialogContent className={styles.postDialog} dir={ar?'rtl':'ltr'}><DialogTitle>{detail?postText(detail,locale).title:''}</DialogTitle><DialogDescription>{ar?'الفكرة ومصدرها وخطوة لتطبيقها.':'The brief, its source and a practical next step.'}</DialogDescription>{detail&&<>{detail.media_url&&<PostMedia post={detail} locale={locale} paused={!!savePost||!!shareItem}/>}<p className={styles.detailBody}>{postText(detail,locale).body}</p>{safeLink(detail.source_url)&&<a className={styles.source} href={safeLink(detail.source_url)} target={detail.source_url?.startsWith('https:')?'_blank':undefined} rel="noopener noreferrer">{detail.source_label|| (ar?'المصدر':'Source')}<ArrowUpRight size={16}/></a>}<div className={styles.detailActions}><button onClick={()=>setSavePost(detail)}><Bookmark size={18}/>{ar?'حفظ في مجموعة':'Save to collection'}</button><button onClick={()=>void share(detail)}><Send size={18}/>{ar?'مشاركة':'Share'}</button></div><Link className={styles.applyLink} href={capabilityLink(detail,locale)}>{ar?'ناقش تطبيق الفكرة في مؤسستك':'Explore this for your organization'}<ArrowUpRight size={17}/></Link></>}</DialogContent></Dialog>
  <Dialog open={!!savePost} onOpenChange={open=>{if(!open)setSavePost(null);}}><DialogContent className={styles.readerDialog} dir={ar?'rtl':'ltr'}><DialogTitle>{ar?'احفظ الفكرة حيث ستستخدمها':'Save the idea where you will use it'}</DialogTitle><DialogDescription>{ar?'يمكنك اختيار أكثر من مجموعة. الحفظ على هذا الجهاز.':'Choose more than one collection. Saved on this device.'}</DialogDescription>{savePost&&collectionOptions.map(c=><label className={styles.collectionChoice} key={c.id}><input type="checkbox" checked={!!prefs.collections[savePost.id]?.includes(c.id)} onChange={()=>persist(toggleCollection(prefs,savePost.id,c.id))}/><span>{c[locale]}</span></label>)}<button className={styles.primary} onClick={()=>setSavePost(null)}>{ar?'تم':'Done'}</button></DialogContent></Dialog>
  <Dialog open={settings||!!optionsPost} onOpenChange={open=>{if(!open){setSettings(false);setOptionsPost(null);}}}><DialogContent className={styles.readerDialog} dir={ar?'rtl':'ltr'}><DialogTitle>{ar?'ماذا تريد أن ترى أكثر؟':'What would you like to see more of?'}</DialogTitle><DialogDescription>{ar?'اختيارك يغيّر ترتيب الموضوعات على هذا الجهاز. تستطيع تغييره أو إعادته للوضع الافتراضي.':'Your choices change topic order on this device. Adjust or reset them at any time.'}</DialogDescription>{topics.filter(t=>!optionsPost||optionsPost.topic===t.id).map(t=><fieldset className={styles.topicPreference} key={t.id}><legend>{t[locale]}</legend>{([{id:'more',ar:'المزيد',en:'More'},{id:'neutral',ar:'عادي',en:'Default'},{id:'less',ar:'أقل',en:'Less'}] as const).map(c=><button key={c.id} aria-pressed={c.id==='more'?prefs.interests.includes(t.id):c.id==='less'?prefs.less.includes(t.id):!prefs.interests.includes(t.id)&&!prefs.less.includes(t.id)} onClick={()=>prefer(t.id,c.id)}>{c[locale]}</button>)}</fieldset>)}<div className={styles.detailActions}><button onClick={()=>{persist({...prefs,interests:[],less:[]});setOptionsPost(null);}}>{ar?'إعادة ضبط الاهتمامات':'Reset interests'}</button><Link href={base||'/'}>{ar?'موقع VisionSeek':'VisionSeek website'}<ArrowUpRight size={15}/></Link><button onClick={()=>{setSettings(false);setOptionsPost(null);}}>{ar?'تم':'Done'}</button></div></DialogContent></Dialog>
  <Dialog open={!!shareItem} onOpenChange={open=>{if(!open)setShareItem(null);}}><DialogContent className={styles.readerDialog} dir={ar?'rtl':'ltr'}><DialogTitle>{ar?'شارك الفكرة':'Share the idea'}</DialogTitle><DialogDescription>{shareItem?postText(shareItem.post,locale).title:''}</DialogDescription><label className={styles.shareLabel}>{ar?'رابط المنشور':'Post link'}<input dir="ltr" readOnly value={shareItem?.url||''} onFocus={e=>e.currentTarget.select()}/></label><div className={styles.detailActions}><button onClick={()=>void copyShared()}>{ar?'نسخ الرابط':'Copy link'}</button>{shareItem&&typeof navigator.share==='function'&&<button onClick={()=>void nativeShare()}>{ar?'مشاركة عبر الجهاز':'Share using device'}</button>}</div></DialogContent></Dialog>
  {notice&&<div className={styles.toast} role="status">{notice}</div>}
 </main>;
}
