'use client';
import Image from 'next/image';
import Link from 'next/link';
import {FormEvent,useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {Archive,ArrowUpRight,Check,Clapperboard,Eye,FileText,ImagePlus,LoaderCircle,LogOut,Plus,Save,Send,Upload} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {leadersClient,loadPosts,uploadMedia,validateMedia,videoDuration} from '@/lib/leaders/client';
import {LeaderPost,Locale,PostKind,Topic,topics,safeLink} from '@/lib/leaders/types';
import {PostMedia} from './media';
import styles from './leaders.module.css';
import EditorialRoom from './editorial-room';
import {characters} from '@/lib/leaders/characters';
const OWNER_EMAIL='abdelalim@visionseek.org';
type Draft={id?:string;character_id?:string|null;title:string;title_en:string;body:string;body_en:string;kind:PostKind;topic:Topic;source_url:string;source_label:string;highlight:boolean;featured:boolean;media_path:string|null;media_type:string|null;media_url?:string;published_at:string|null};
const emptyDraft:Draft={character_id:null,title:'',title_en:'',body:'',body_en:'',kind:'note',topic:'leadership',source_url:'',source_label:'',highlight:false,featured:false,media_path:null,media_type:null,published_at:null};
export default function LeadersStudio({locale,room=false}:{locale:Locale;room?:boolean}){
 const ar=locale==='ar',base=ar?'/ar':'';const [now]=useState(()=>Date.now());const [session,setSession]=useState<Session|null>(null);const [checking,setChecking]=useState(true);const [editor,setEditor]=useState(false);const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [posts,setPosts]=useState<LeaderPost[]>([]);const [draft,setDraft]=useState<Draft>({...emptyDraft});const [file,setFile]=useState<File|null>(null);const [previewUrl,setPreviewUrl]=useState<string>();const [progress,setProgress]=useState<number|null>(null);const [preview,setPreview]=useState(false);const [tab,setTab]=useState<'published'|'draft'|'archived'>('published');const [dirty,setDirty]=useState(false);const controller=useRef<AbortController|null>(null);const pendingUpload=useRef<{file:File;path:string}|null>(null);
 const t=(arabic:string,english:string)=>ar?arabic:english;
 // Synchronize browser URL, authentication, or file object URL with React.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const type=new URLSearchParams(window.location.search).get('type');if(type==='story'||type==='video')setDraft(v=>({...v,kind:type}));let alive=true;const client=leadersClient();void client.auth.getSession().then(({data})=>{if(alive){setSession(data.session);setChecking(false);}}).catch(()=>{if(alive){setError('تعذر الاتصال بخدمة الدخول. أعد تحميل الصفحة.');setChecking(false);}});const {data}=client.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>{alive=false;data.subscription.unsubscribe();controller.current?.abort();};},[]);
 // Synchronize browser URL, authentication, or file object URL with React.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!session){setEditor(false);return;}let alive=true;async function check(){try{const {data,error}=await leadersClient().from('leaders_editors').select('user_id').eq('user_id',session!.user.id).maybeSingle();if(!alive)return;if(error)throw error;setEditor(!!data);if(data){const rows=await loadPosts({studio:true,limit:200});if(alive){setPosts(rows);const editId=new URLSearchParams(window.location.search).get('edit');const post=rows.find(p=>p.id===editId);if(post)setDraft({...post,title_en:post.title_en||'',body_en:post.body_en||'',source_url:post.source_url||'',source_label:post.source_label||''});}}else setError('هذا الحساب لا يملك صلاحية النشر.');}catch{if(alive)setError('تعذر التحقق من صلاحية النشر. أعد تحميل الصفحة للمحاولة.');}}void check();return()=>{alive=false;};},[session]);
 // Synchronize browser URL, authentication, or file object URL with React.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!file){setPreviewUrl(undefined);return;}const url=URL.createObjectURL(file);setPreviewUrl(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function change<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(d=>({...d,[key]:value}));setDirty(true);setError('');}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await leadersClient().auth.signInWithPassword({email:OWNER_EMAIL,password});if(error)throw error;setPassword('');}catch{setError(t('تعذر الدخول. راجع كلمة المرور والاتصال وحاول مجددًا.','Could not sign in. Check your password and connection.'));}finally{setBusy(false);}}
 async function chooseFile(next:File|undefined){if(!next)return;setError('');try{validateMedia(next);if(next.type.startsWith('video/')){const duration=await videoDuration(next);if(duration>90)throw new Error('الفيديو أطول من 90 ثانية. اختر مقطعًا أقصر.');}pendingUpload.current=null;setFile(next);setDraft(d=>({...d,kind:d.kind==='story'?'story':next.type.startsWith('video/')?'video':'image'}));setDirty(true);}catch(e){setError(e instanceof Error?e.message:'تعذر قراءة الملف.');}}
 function reset(){if(dirty&&!window.confirm(t('توجد تغييرات لم تُحفظ. هل تريد بدء منشور جديد؟','Discard unsaved changes and start a new post?')))return;setDraft({...emptyDraft});setFile(null);pendingUpload.current=null;setDirty(false);setError('');setNotice('');}
 function edit(p:LeaderPost){if(dirty&&!window.confirm(t('توجد تغييرات لم تُحفظ. هل تريد فتح المنشور الآخر؟','Discard unsaved changes and open this post?')))return;setDraft({...p,title_en:p.title_en||'',body_en:p.body_en||'',source_url:p.source_url||'',source_label:p.source_label||''});setFile(null);pendingUpload.current=null;setDirty(false);setError('');setNotice('');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(status:'published'|'draft'){
  if(!session||!editor)return;setError('');setNotice('');
  if(!draft.title.trim()){setError(t('اكتب عنوانًا أو فكرة رئيسية للمنشور.','Add a title or main idea.'));return;}
  if(draft.source_url&&!safeLink(draft.source_url)){setError(t('استخدم رابط مصدر يبدأ بـ https://.','Use a source URL starting with https://.'));return;}
  const type=file?.type||draft.media_type;
  if((draft.kind==='image'||draft.kind==='video')&&!file&&!draft.media_path&&!draft.media_url){setError(t('اختر ملفًا قبل الحفظ.','Choose a file before saving.'));return;}
  if(draft.kind==='video'&&!type?.startsWith('video/')){setError(t('اختر ملف فيديو لهذا النوع من المنشورات.','Choose a video file for this post.'));return;}
  if(draft.kind==='image'&&!type?.startsWith('image/')){setError(t('اختر صورة لهذا النوع من المنشورات.','Choose an image for this post.'));return;}
  setBusy(true);controller.current=new AbortController();
  try{
   let mediaPath=draft.media_path;
   if(file&&draft.kind!=='note'){if(pendingUpload.current?.file===file)mediaPath=pendingUpload.current.path;else{setProgress(0);mediaPath=await uploadMedia(file,session.user.id,setProgress,controller.current.signal);pendingUpload.current={file,path:mediaPath};}}
   if(controller.current.signal.aborted)throw new DOMException('Cancelled','AbortError');
   const publishTime=status==='published'?(draft.published_at||new Date().toISOString()):draft.published_at;
   const expires=draft.kind==='story'&&!draft.highlight&&status==='published'?new Date(Date.now()+24*60*60*1000).toISOString():null;
   const payload={character_id:draft.character_id||null,title:draft.title.trim(),title_en:draft.title_en.trim()||null,body:draft.body.trim(),body_en:draft.body_en.trim()||null,kind:draft.kind,topic:draft.topic,source_url:draft.source_url.trim()||null,source_label:draft.source_label.trim()||null,highlight:draft.kind==='story'&&draft.highlight,featured:draft.featured,author_id:session.user.id,status,published_at:publishTime,expires_at:expires,updated_at:new Date().toISOString(),media_path:draft.kind==='note'?null:mediaPath,media_type:draft.kind==='note'?null:(file?.type||draft.media_type),media_url:draft.kind==='note'||file||draft.media_path?null:(draft.media_url?.startsWith('/field-')?draft.media_url:null)};
   const result=draft.id?await leadersClient().from('leaders_posts').update(payload).eq('id',draft.id).select('*').single():await leadersClient().from('leaders_posts').insert(payload).select('*').single();
   if(result.error)throw new Error('تعذر حفظ المنشور. الملف المرفوع جاهز؛ أعد المحاولة دون إغلاق الصفحة.');
   setDirty(false);setFile(null);pendingUpload.current=null;setDraft({...emptyDraft});setTab(status);setNotice(status==='published'?t('تم النشر. المحتوى متاح الآن في بيت القادة.','Published. Your content is now live in Leaders House.'):t('تم حفظ المسودة. يمكنك العودة إليها قبل النشر.','Draft saved. You can return to it before publishing.'));
   setPosts(await loadPosts({studio:true,limit:200}));
  }catch(e){setError(e instanceof Error&&e.name==='AbortError'?t('تم إلغاء الرفع. محتوى المنشور ما زال موجودًا.','Upload cancelled. Your text is still here.'):e instanceof Error?e.message:t('تعذر الحفظ. حاول مجددًا.','Could not save. Try again.'));}finally{setBusy(false);setProgress(null);controller.current=null;}
 }
 async function archive(p:LeaderPost){setBusy(true);setError('');try{const status=p.status==='archived'?'draft':'archived';const {error}=await leadersClient().from('leaders_posts').update({status,updated_at:new Date().toISOString()}).eq('id',p.id).select('id').single();if(error)throw error;setPosts(prev=>prev.map(x=>x.id===p.id?{...x,status}:x));setNotice(status==='archived'?t('نُقل إلى الأرشيف. يمكنك استعادته.','Archived. You can restore it.'):t('استُعيد إلى المسودات.','Restored to drafts.'));}catch{setError(t('تعذر تحديث المنشور. حاول مجددًا.','Could not update the post.'));}finally{setBusy(false);}}
 const previewPost:LeaderPost={...draft,id:draft.id||'preview',status:'draft',expires_at:null,created_at:new Date(now).toISOString(),title_en:draft.title_en||null,body_en:draft.body_en||null,source_url:draft.source_url||null,source_label:draft.source_label||null,media_url:previewUrl||draft.media_url,media_type:file?.type||draft.media_type};
 if(checking)return <main className={`${styles.studio} ${room&&editor?styles.editorialStudio:''}`} dir={ar?'rtl':'ltr'}><div className={styles.loading}>{t('جاري التحقق من الدخول…','Checking your session…')}</div></main>;
 return <main className={`${styles.studio} ${room&&editor?styles.editorialStudio:''}`} dir={ar?'rtl':'ltr'} lang={locale}><header className={styles.studioHeader}><Link href={`${base}/insights`} className={styles.brand}><span className={styles.brandSymbol}><Image src="/visionseek-symbol-color.png" width={36} height={36} alt="VisionSeek"/></span><span><strong>{t('بيت القادة','Leaders House')}</strong><small>{t('استوديو المحتوى','CONTENT STUDIO')}</small></span></Link><div><Link href={`${base}/insights/studio${room?'':'/characters'}`}>{room?t('استوديو المحتوى','Content studio'):t('غرفة الشخصيات','Character room')}</Link><Link href={`${base}/insights`}>{t('شاهد بيت القادة','View Leaders House')}<ArrowUpRight size={17}/></Link>{session&&<button onClick={()=>{if(!dirty||window.confirm(t('الخروج دون حفظ التغييرات؟','Sign out without saving?')))void leadersClient().auth.signOut();}} aria-label={t('تسجيل الخروج','Sign out')}><LogOut size={20}/></button>}</div></header>
 {!session?<section className={styles.login}><span className={styles.loginIcon}><Plus size={30}/></span><p>VISIONSEEK CREATOR STUDIO</p><h1>{t('فكرة منك. خطوة لقائد.','Your idea. A leader’s next step.')}</h1><p>{t('ادخل بحساب VisionSeek لرفع الفيديوهات والصور ونشر الستوريز والأفكار.','Sign in to publish videos, images, stories, and ideas.')}</p><form onSubmit={login}><label>{t('البريد الإلكتروني','Email')}<input value={OWNER_EMAIL} readOnly autoComplete="username" type="email"/></label><label>{t('كلمة المرور','Password')}<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" required minLength={8}/></label><button className={styles.primary} disabled={busy}>{busy?<LoaderCircle className={styles.spinning} size={18}/>:<ArrowUpRight size={18}/>} {t('دخول إلى الاستوديو','Enter the studio')}</button></form><p className={styles.loginHint}>{t('استخدم كلمة مرور حسابك الحالي في VisionSeek.','Use your existing VisionSeek account password.')}</p>{error&&<p className={styles.formError} role="alert">{error}</p>}</section>:!editor?<section className={styles.login}><h1>{t('صلاحية النشر','Publishing access')}</h1><p role="status">{error||t('جاري التحقق من حسابك…','Checking your account…')}</p><button onClick={()=>window.location.reload()}>{t('إعادة المحاولة','Retry')}</button></section>:room?<EditorialRoom locale={locale}/>:<>
 <section className={styles.studioIntro}><div><p>{t('استوديو بيت القادة','LEADERS HOUSE STUDIO')}</p><h1>{t('ماذا تريد أن يراه القادة اليوم؟','What should leaders see today?')}</h1></div><button className={styles.secondary} onClick={reset} disabled={busy}><Plus size={18}/>{t('منشور جديد','New post')}</button></section>
 <div className={styles.studioGrid}><section className={styles.editor}><form onSubmit={e=>{e.preventDefault();void save('published');}}><fieldset disabled={busy}><legend className="sr-only">{t('إعداد المحتوى','Create content')}</legend><div className={styles.kindPicker}>{([{id:'note',icon:FileText,ar:'فكرة',en:'Idea'},{id:'image',icon:ImagePlus,ar:'صورة',en:'Image'},{id:'video',icon:Clapperboard,ar:'فيديو',en:'Video'},{id:'story',icon:Plus,ar:'ستوري',en:'Story'}] as const).map(k=><button type="button" key={k.id} aria-pressed={draft.kind===k.id} className={draft.kind===k.id?styles.kindActive:''} onClick={()=>change('kind',k.id)}><k.icon size={21}/><span>{k[locale]}</span></button>)}</div>
 {draft.kind!=='note'&&<div className={styles.uploadBox}><Upload size={29}/><strong>{file?file.name:t('ارفع فيديو أو صورة','Upload a video or image')}</strong><p>{t('فيديو حتى 90 ثانية · حجم الملف حتى 50 ميجابايت','Video up to 90 seconds · File up to 50 MB')}</p><label className={styles.secondary}>{t('اختر ملفًا','Choose a file')}<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" onChange={e=>{void chooseFile(e.target.files?.[0]);e.target.value='';}}/></label>{(file||draft.media_url)&&<div className={styles.uploadPreview}><PostMedia key={previewPost.media_url} post={previewPost} locale={locale} paused/>{file&&<button type="button" onClick={()=>{setFile(null);pendingUpload.current=null;}}>{t('إلغاء اختيار الملف','Clear file')}</button>}</div>}</div>}
 <label>{t('العنوان أو الفكرة الرئيسية','Title or main idea')}<input value={draft.title} onChange={e=>change('title',e.target.value)} maxLength={180} required placeholder={t('فكرة واضحة تستحق أن يتوقف عندها القائد…','An idea worth pausing on…')}/><small>{draft.title.length}/180</small></label>
 <label>{t('تفاصيل المنشور','Caption')}<textarea value={draft.body} onChange={e=>change('body',e.target.value)} maxLength={5000} rows={6} placeholder={t('لماذا تهم هذه الفكرة؟ وما الذي يستطيع القائد فعله بعدها؟','Why does this matter? What can a leader do next?')}/></label>
 <label>{t('هوية النشر','Publishing identity')}<select value={draft.character_id||''} onChange={e=>change('character_id',e.target.value||null)}><option value="">VisionSeek</option>{characters.map(c=><option key={c.id} value={c.id}>{c.name[locale]} · {c.sector[locale]}</option>)}</select></label>
 <label>{t('الموضوع','Topic')}<select value={draft.topic} onChange={e=>change('topic',e.target.value as Topic)}>{topics.map(x=><option key={x.id} value={x.id}>{x[locale]}</option>)}</select></label>
 <details className={styles.extraFields}><summary>{t('مصدر وترجمة إنجليزية (اختياري)','Source and English translation (optional)')}</summary><label>{t('رابط المصدر','Source URL')}<input value={draft.source_url} onChange={e=>change('source_url',e.target.value)} placeholder="https://" dir="ltr"/></label><label>{t('اسم المصدر','Source name')}<input value={draft.source_label} onChange={e=>change('source_label',e.target.value)} maxLength={120}/></label><label>English title<input value={draft.title_en} onChange={e=>change('title_en',e.target.value)} maxLength={180} dir="ltr"/></label><label>English caption<textarea value={draft.body_en} onChange={e=>change('body_en',e.target.value)} maxLength={5000} rows={4} dir="ltr"/></label></details>
 {draft.kind==='story'&&<label className={styles.checkLabel}><input type="checkbox" checked={draft.highlight} onChange={e=>change('highlight',e.target.checked)}/><span>{t('ثبّت الستوري في المختارات','Keep this story as a highlight')}<small>{t('الستوري العادية تختفي بعد 24 ساعة من النشر.','Regular stories disappear 24 hours after publishing.')}</small></span></label>}
 <label className={styles.checkLabel}><input type="checkbox" checked={draft.featured} onChange={e=>change('featured',e.target.checked)}/><span>{t('ضع علامة «مختار» على المنشور','Mark this post as selected')}</span></label>
 </fieldset>
 {progress!==null&&<div className={styles.uploadProgress}><div><span>{progress<100?t('جاري رفع الملف','Uploading'):t('جاري حفظ المنشور','Saving post')}</span><span>{progress}%</span></div><progress max={100} value={progress}/><button type="button" onClick={()=>controller.current?.abort()} disabled={progress===100}>{t('إلغاء الرفع','Cancel upload')}</button></div>}
 {error&&<p className={styles.formError} role="alert">{error}</p>}{notice&&<p className={styles.formSuccess} role="status"><Check size={18}/>{notice}</p>}
 <div className={styles.editorActions}><button type="submit" className={styles.primary} disabled={busy}>{busy?<LoaderCircle className={styles.spinning} size={18}/>:<Send size={18}/>} {t('نشر الآن','Publish now')}</button><button type="button" className={styles.secondary} disabled={busy} onClick={()=>void save('draft')}><Save size={17}/>{t('حفظ مسودة','Save draft')}</button><button type="button" className={styles.iconButton} disabled={busy} onClick={()=>setPreview(true)} aria-label={t('معاينة المنشور','Preview post')}><Eye size={20}/></button></div></form></section>
 <aside className={styles.studioGuide}><span>01 / CREATE</span><h2>{t('فكرة واحدة. أثر واضح.','One idea. A clear takeaway.')}</h2><p>{t('ابدأ بما يهم القائد، اختصر الطريق إلى الفكرة، واختم بخطوة يستطيع تجربتها.','Start with what matters to a leader. Get to the idea quickly. Close with something they can try.')}</p><ul><li>{t('الفيديو الرأسي 9:16 مناسب للهاتف.','Vertical 9:16 video works well on phones.')}</li><li>{t('أضف ترجمة مكتوبة داخل الفيديو لمن يشاهد دون صوت.','Include captions in your video for people watching without sound.')}</li><li>{t('اربط المعلومات المنقولة بمصدرها.','Link to sources for information you share.')}</li><li>{t('المسودات تظهر لك وحدك قبل النشر.','Drafts are visible only to you before publication.')}</li></ul><Link href={`${base}/insights`}>{t('افتح تجربة الزائر','Open the reader experience')}<ArrowUpRight size={18}/></Link></aside></div>
 <section className={styles.contentLibrary}><div className={styles.libraryHeading}><h2>{t('مكتبة المحتوى','Content library')}</h2><div className={styles.libraryTabs}>{(['published','draft','archived'] as const).map(v=><button key={v} className={tab===v?styles.filterActive:''} onClick={()=>setTab(v)}>{v==='published'?t('منشور','Published'):v==='draft'?t('مسودات','Drafts'):t('الأرشيف','Archived')} <span>{posts.filter(p=>p.status===v).length}</span></button>)}</div></div>{!posts.some(p=>p.status===tab)&&<p className={styles.libraryEmpty}>{t('لا يوجد محتوى في هذا القسم بعد.','No content in this section yet.')}</p>}{posts.filter(p=>p.status===tab).map(p=><article key={p.id} className={styles.libraryRow}><span className={styles.libraryIcon}>{p.kind==='video'?<Clapperboard/>:p.kind==='note'?<FileText/>:<ImagePlus/>}</span><div><h3>{p.title}</h3><small>{topics.find(x=>x.id===p.topic)?.[locale]} · {p.kind==='story'?(p.highlight?t('ستوري مثبتة','Highlight'):p.expires_at&&Date.parse(p.expires_at)<now?t('ستوري منتهية','Expired story'):t('ستوري 24 ساعة','24-hour story')):p.kind==='video'?t('فيديو','Video'):p.kind==='image'?t('صورة','Image'):t('فكرة','Idea')}</small></div><button disabled={busy} onClick={()=>edit(p)}>{t('تعديل','Edit')}</button><button className={styles.iconButton} disabled={busy} onClick={()=>void archive(p)} aria-label={p.status==='archived'?t('استعادة إلى المسودات','Restore to drafts'):t('أرشفة المنشور','Archive post')}><Archive size={19}/></button></article>)}</section>
 <Dialog open={preview} onOpenChange={setPreview}><DialogContent className={styles.previewDialog} dir={ar?'rtl':'ltr'}><DialogTitle>{t('معاينة قبل النشر','Preview before publishing')}</DialogTitle><DialogDescription>{t('هذه معاينة فقط. لم يتم نشر المحتوى.','This is a preview. The content has not been published.')}</DialogDescription>{previewPost.media_url&&draft.kind!=='note'&&<PostMedia post={previewPost} locale={locale} paused/>}<h2>{draft.title||t('عنوان المنشور','Post title')}</h2><p className={styles.previewBody}>{draft.body}</p></DialogContent></Dialog>
 </>}
 </main>;
}
