export const transferCopy = {
 ar: {
  eyebrow: 'من قدرات العالم إلى واقع مؤسستك',
  headline: 'ننقل القدرات المتقدمة من العالم إلى مؤسستك.',
  intro: 'نكتشف التقنيات والخبرات التي تحقق ما تحتاجه، ونجمع المعرفة والشركاء والبنية التحتية والتنفيذ، حتى تصبح قدرة تعمل داخل مؤسستك.',
  primary: 'ابنِ حلولك معنا', secondary: 'شاهد كيف تتحول القدرة إلى واقع',
  bridgeTitle: 'موجودة في العالم. تعمل عندك.',
  bridgeIntro: 'قد تكون التقنية متاحة، لكن تشغيلها في مؤسسة جديدة يحتاج أكثر من الوصول إليها. هنا يبدأ عمل VisionSeek.',
  bridge: [ ['قدرة موجودة عالميًا', 'تقنية متقدمة، معرفة متخصصة، أو نظام أثبت فائدته في سياق آخر.'], ['VisionSeek تجمع ما ينقص', 'نحدد احتياجك، ونصمم مسار النقل والتكييف، ونربط أصحاب التقنية والخبرة بالتنفيذ.'], ['قدرة تعمل داخل مؤسستك', 'فريق يستطيع استخدامها، وبنية تدعمها، ونتائج تُختبر في ظروف التشغيل الفعلية.'] ],
  methodTitle: 'من اكتشاف القدرة إلى تشغيلها على أرض الواقع.',
  methodIntro: 'كل خطوة تقرّبنا من نتيجة محددة تستطيع مؤسستك تحقيقها.',
  steps: [ ['نكتشف القدرة', 'نبحث عالميًا عن التقنيات والمعرفة التي تفتح مجالًا لنتيجة مهمة.', 'قدرات جديرة بالفحص'], ['نحدد أين تصنع الفرق', 'نربط القدرة باحتياج فعلي، ونفهم ما تملكه المؤسسة وما ينقصها.', 'احتياج واضح وفجوة محددة'], ['نصمم طريق نقلها', 'نحدد ما يحتاج ترخيصًا أو تكييفًا أو بناءً، ومن يتولى كل جزء.', 'مسار قابل للتنفيذ'], ['نجمع عناصر التشغيل', 'نربط التقنية بالشركاء والفريق والبنية التحتية ومتطلبات السوق.', 'عناصر تعمل معًا'], ['نشغّل ونثبت النتيجة', 'نختبر في البيئة المستهدفة، ونقيس الأداء، ونحدد ما يلزم لاستمرار التشغيل.', 'دليل على قدرة تعمل'] ],
  assembleTitle: 'التقنية وحدها لا تكفي.',
  assembleIntro: 'نبني الروابط التي تجعل العناصر المتفرقة تعمل كقدرة واحدة.',
  ingredients: [ ['التكنولوجيا', 'اختيار التقنية وتكييفها مع المهمة'], ['المعرفة', 'نقل الخبرة وتعلّم استخدامها'], ['الأشخاص والشركاء', 'أصحاب القدرة وفريق التنفيذ والتشغيل'], ['البنية التحتية', 'البيانات والتجهيزات والأنظمة الداعمة'], ['الوصول إلى السوق', 'متطلبات الاستخدام والعملاء والتنظيم'], ['التنفيذ', 'دمج واختبار وتدريب وتسليم للتشغيل'] ],
  outcomeLabel: 'النتيجة التي نبني من أجلها', outcome: 'قدرة جديدة تستطيع مؤسستك تشغيلها وتطويرها.',
  exampleLabel: 'مثال توضيحي · الذكاء الاصطناعي الصناعي', exampleTitle: 'من تقنية تكشف العيوب إلى قدرة تضبط جودة الإنتاج.',
  example: 'قد يوجد نظام رؤية متقدم في مكان آخر. لكي يعمل على خط إنتاجك، نربط التقنية ببيانات المصنع والتجهيزات وفريق الجودة وشريك التنفيذ، ثم نختبر دقته في ظروفك الفعلية.',
  exampleNote: 'مثال لشرح طريقة العمل، وليس إعلانًا عن مشروع منفّذ.',
  ecosystemTitle: 'كل جزء في VisionSeek يخدم الوصول إلى هذه النتيجة.',
  ecosystem: [ ['البرامج', 'مسارات منظّمة تربط احتياج المؤسسة بالقدرات المناسبة لها. ابدأ ببرنامج HLO.'], ['فرص البحث والتطوير', 'أسئلة وفجوات تحتاج مساهمة الباحثين وأصحاب التقنيات.'], ['المشاريع', 'ملفات تُجمع حولها عناصر الحل، وتُعرض فيها الفكرة وحالة العمل.'], ['التقارير', 'معرفة موثقة تساعد على فهم القدرة وتقييم قرار استخدامها.'], ['اعمل معنا', 'ابدأ من احتياج مؤسستك، أو من تقنية وخبرة يمكنك المساهمة بهما.'] ],
  hloTitle: 'HLO — اكتشف ما يمكن أن يرفع مستوى مؤسستك.', hloBody: 'يربط برنامج Highest Level One طموح مؤسستك بما وصل إليه العالم من فرص وقدرات، لتحديد ما يستحق التطبيق وكيف نختبره.', hloLink: 'اكتشف برنامج HLO',
  leadersTitle: 'بيت القادة', leadersBody: 'للمديرين التنفيذيين والقادة وصنّاع القرار: أفكار وقراءات تساعدك على رؤية ما يتغير وما يستحق التحرك.', leadersLink: 'ادخل بيت القادة',
  contactTitle: 'ما الذي تحتاج مؤسستك أن تصبح قادرة على فعله؟', contactBody: 'شاركنا النتيجة التي تحتاجها. أو أخبرنا عن تقنية أو معرفة تملكها ويمكن أن تصنع فرقًا في مكان آخر.', about: 'تعرّف على VisionSeek ورؤية مؤسسها'
 },
 en: {
  eyebrow: 'GLOBAL CAPABILITIES. LOCAL OPERATION.',
  headline: 'We move critical capabilities to where they need to exist.',
  intro: 'We find advanced capabilities around the world and connect the technology, knowledge, partners, infrastructure and implementation needed to make them work in your institution.',
  primary: 'Build your solutions with us', secondary: 'See how a capability becomes operational',
  bridgeTitle: 'Exists in the world. Works here.',
  bridgeIntro: 'A technology may already exist. Making it work in a new institution takes more than access. This is where VisionSeek comes in.',
  bridge: [ ['A capability exists globally', 'Advanced technology, specialist knowledge or a system that has demonstrated value in another context.'], ['VisionSeek connects what is missing', 'We identify your need, architect the transfer and adaptation, and connect technology and expertise with implementation.'], ['A capability works in your institution', 'People who can use it, infrastructure that supports it, and results validated in real operating conditions.'] ],
  methodTitle: 'From capability discovery to real-world deployment.', methodIntro: 'Each step brings us closer to a specific outcome your institution can deliver.',
  steps: [ ['Discover', 'Find technologies and knowledge around the world that could enable an important outcome.', 'Capabilities worth evaluating'], ['Identify need', 'Connect the capability to a real need. Understand what the institution has and what is missing.', 'A defined need and capability gap'], ['Architect the transfer', 'Determine what needs licensing, adaptation or development, and who delivers each part.', 'An executable transfer path'], ['Connect capabilities', 'Bring together technology, partners, people, infrastructure and market requirements.', 'Connected operating elements'], ['Deploy & validate', 'Test in the target environment, measure performance and establish what sustained operation requires.', 'Evidence of a working capability'] ],
  assembleTitle: 'Technology alone is not enough.', assembleIntro: 'We build the connections that turn separate elements into one working capability.',
  ingredients: [ ['Technology', 'Select and adapt technology to the task'], ['Knowledge', 'Transfer expertise and learn to apply it'], ['People & partners', 'Capability owners, delivery and operating teams'], ['Infrastructure', 'Data, equipment and supporting systems'], ['Market access', 'Users, customers and regulatory requirements'], ['Implementation', 'Integration, testing, training and operational handover'] ],
  outcomeLabel: 'THE OUTCOME WE BUILD TOWARD', outcome: 'A new capability your institution can operate and develop.',
  exampleLabel: 'ILLUSTRATIVE EXAMPLE · INDUSTRIAL AI', exampleTitle: 'From defect-detection technology to production quality control.',
  example: 'An advanced vision system may exist elsewhere. To make it work on your production line, we connect it with factory data, equipment, the quality team and an implementation partner, then validate its accuracy in your conditions.', exampleNote: 'An illustration of our approach, not a claim of a delivered project.',
  ecosystemTitle: 'Every part of VisionSeek serves this outcome.',
  ecosystem: [ ['Programs', 'Structured paths connecting institutional needs with relevant capabilities. Start with HLO.'], ['R&D Opportunities', 'Questions and gaps that need contributions from researchers and technology owners.'], ['Projects', 'Work that brings solution elements together, with its concept and status made visible.'], ['Reports', 'Sourced knowledge to understand capabilities and inform decisions about their use.'], ['Work with Us', 'Start with your institutional need, or contribute technology and expertise.'] ],
  hloTitle: 'HLO — discover what could raise your institution’s level.', hloBody: 'Highest Level One connects institutional ambition with global opportunities and capabilities, to identify what is worth applying and how to test it.', hloLink: 'Explore the HLO program',
  leadersTitle: 'Leaders House', leadersBody: 'For executives, leaders and decision-makers: perspectives that help you see what is changing and where to act.', leadersLink: 'Enter Leaders House',
  contactTitle: 'What does your institution need to be able to do?', contactBody: 'Tell us the outcome you need. Or share technology or expertise that could make a difference in another setting.', about: 'Meet VisionSeek and explore the founder’s vision'
 }
} as const;
